import { Scholarship } from './types';

export const scholarships: Scholarship[] = [
  // ========================================
  // 1. TAMIL NADU STATE GOVERNMENT SCHEMES
  // ========================================
  
  // Gender-Based Scholarships
  {
    id: 'tn-pudhumai-penn',
    name: 'Pudhumai Penn Scheme',
    provider: 'Tamil Nadu Government (UMIS)',
    type: 'government',
    amount: '₹1,000/month (Until Degree Ends)',
    eligibility: ['Girl Students', 'Studied 6th-12th in Govt Schools', 'UG Students'],
    deadline: 'Always Open',
    deadlineStatus: 'always-open',
    educationLevel: ['ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'female',
    state: 'Tamil Nadu',
    description: 'Monthly financial support for girl students who studied from 6th to 12th in government schools. Continues until degree completion.',
    applicationUrl: 'https://umis.tn.gov.in',
    helpline: '044-25361520',
    documents: ['School TC (Govt School)', 'College Admission Letter', 'Aadhaar Card', 'Bank Passbook', 'Photo'],
    howToApply: ['Apply through UMIS portal', 'Submit govt school TC (6th-12th)', 'Bank account verification', 'Monthly disbursement begins'],
    benefits: [{ label: 'Monthly Amount', value: '₹1,000' }, { label: 'Annual Total', value: '₹12,000' }, { label: 'Duration', value: 'Until Degree Ends' }]
  },
  {
    id: 'tn-tamil-pudhalvan',
    name: 'Tamil Pudhalvan Scheme',
    provider: 'Tamil Nadu Government (UMIS)',
    type: 'government',
    amount: '₹1,000/month (Until Degree Ends)',
    eligibility: ['Boy Students', 'Studied 6th-12th in Govt Schools', 'UG Students'],
    deadline: 'Always Open',
    deadlineStatus: 'always-open',
    educationLevel: ['ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'male',
    state: 'Tamil Nadu',
    description: 'Monthly financial support for boy students who studied from 6th to 12th in government schools. Continues until degree completion.',
    applicationUrl: 'https://umis.tn.gov.in',
    helpline: '044-25361520',
    documents: ['School TC (Govt School)', 'College Admission Letter', 'Aadhaar Card', 'Bank Passbook', 'Photo'],
    howToApply: ['Apply through UMIS portal', 'Submit govt school TC (6th-12th)', 'Bank account verification', 'Monthly disbursement begins'],
    benefits: [{ label: 'Monthly Amount', value: '₹1,000' }, { label: 'Annual Total', value: '₹12,000' }, { label: 'Duration', value: 'Until Degree Ends' }]
  },

  // Community-Based Scholarships
  {
    id: 'tn-bc-mbc-post-matric',
    name: 'BC/MBC Post-Matric Scholarship',
    provider: 'BC/MBC Welfare Department, TN (TNSSP)',
    type: 'government',
    amount: 'Tuition Fee + Exam Fee Coverage',
    eligibility: ['BC/MBC/DNC Category', 'Family Income < ₹2.5 Lakhs', 'Post-Matric Studies'],
    deadline: 'Dec 31, 2026',
    deadlineStatus: 'closing-soon',
    educationLevel: ['12th-passed', 'ug', 'pg', 'diploma', 'professional'],
    category: ['bc-mbc', 'obc'],
    incomeLimit: '2.5',
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Full tuition and exam fee coverage for BC/MBC/DNC students with family income below ₹2.5 Lakhs.',
    applicationUrl: 'https://bcmbcmw.tn.gov.in',
    helpline: '044-25670065',
    documents: ['BC/MBC Certificate', 'Income Certificate (< ₹2.5L)', 'Aadhaar Card', 'Marksheets', 'Bank Details'],
    howToApply: ['Register on TNSSP portal', 'Fill application form', 'Upload documents', 'College verification', 'Fee reimbursement'],
    benefits: [{ label: 'Tuition Fee', value: 'Full Coverage' }, { label: 'Exam Fee', value: 'Covered' }, { label: 'Income Limit', value: '< ₹2.5 Lakhs' }]
  },
  {
    id: 'tn-sc-st-post-matric',
    name: 'SC/ST Post-Matric Scholarship',
    provider: 'Adi Dravidar Welfare Dept, TN (TNSSP)',
    type: 'government',
    amount: 'Full Fee Reimbursement + Hostel Support',
    eligibility: ['SC/ST/SCC Category', 'Family Income < ₹2.5 Lakhs', 'Post-Matric Studies'],
    deadline: 'Dec 31, 2026',
    deadlineStatus: 'closing-soon',
    educationLevel: ['12th-passed', 'ug', 'pg', 'diploma', 'professional'],
    category: ['sc', 'st'],
    incomeLimit: '2.5',
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Complete fee reimbursement and hostel support for SC/ST/SCC students pursuing post-matric education.',
    applicationUrl: 'https://adwelfare.tn.gov.in',
    helpline: '044-25670065',
    documents: ['SC/ST/SCC Certificate', 'Income Certificate (< ₹2.5L)', 'Aadhaar Card', 'Marksheets', 'Hostel Admission (if applicable)', 'Bank Details'],
    howToApply: ['Register on TNSSP portal', 'Submit caste certificate', 'Income verification', 'College attestation', 'Full fee reimbursement'],
    benefits: [{ label: 'Fee Reimbursement', value: 'Full Amount' }, { label: 'Hostel Support', value: 'Additional Allowance' }, { label: 'Income Limit', value: '< ₹2.5 Lakhs' }]
  },

  // First Graduate Scholarship
  {
    id: 'tn-first-graduate',
    name: 'First Graduate (FG) Scholarship',
    provider: 'Tamil Nadu Government (TNSSP)',
    type: 'government',
    amount: 'Significant Tuition Fee Concession',
    eligibility: ['First Generation College Student', 'TN Domicile', 'UG Studies'],
    deadline: 'Jan 15, 2026',
    deadlineStatus: 'one-month',
    educationLevel: ['ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Special tuition fee concession for first generation college students - those who are the first in their family to pursue higher education.',
    applicationUrl: 'https://scholarships.gov.in',
    helpline: '1800-121-3513',
    documents: ['Parent Education Declaration', 'Income Certificate', 'College Bonafide', 'Aadhaar Card', 'Bank Passbook'],
    howToApply: ['Apply on TNSSP portal', 'Submit first graduate declaration', 'Parent education affidavit', 'College verification', 'Fee concession applied'],
    benefits: [{ label: 'Fee Concession', value: 'Significant' }, { label: 'Criteria', value: 'First in Family' }, { label: 'For', value: 'UG Students' }]
  },

  // Merit-Based Scholarship
  {
    id: 'tn-7-5-horizontal-reservation',
    name: '7.5% Horizontal Reservation Scheme',
    provider: 'Tamil Nadu Government',
    type: 'government',
    amount: '100% Fees Paid by Government',
    eligibility: ['Govt School Students (6th-12th)', 'Professional Courses (Engg/Medical)', 'JEE/NEET Qualified'],
    deadline: 'Based on Counseling',
    deadlineStatus: 'open',
    educationLevel: ['professional'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Special 7.5% horizontal reservation in professional courses for government school students who studied from 6th to 12th in TN government schools.',
    applicationUrl: 'https://tnea.ac.in',
    helpline: '044-22300500',
    documents: ['School TC (Govt School 6th-12th)', 'JEE/NEET Score Card', '12th Marksheet', 'Aadhaar Card', 'Community Certificate'],
    howToApply: ['Qualify in JEE/NEET', 'Apply under 7.5% quota during counseling', 'Submit govt school proof', 'Seat allotment', 'Full fees covered'],
    benefits: [{ label: 'Fee Coverage', value: '100% by Government' }, { label: 'Quota', value: '7.5% Seats Reserved' }, { label: 'Courses', value: 'Engineering/Medical' }]
  },

  // Tech/Digital Scheme
  {
    id: 'tn-ulagam-ungal-kaiyil',
    name: 'Ulagam Ungal Kaiyil (Free Laptop)',
    provider: 'Tamil Nadu Government',
    type: 'government',
    amount: 'Free Laptop (~₹30,000 Value)',
    eligibility: ['Final Year Students', 'Government Colleges', 'UG Courses'],
    deadline: 'Academic Year Based',
    deadlineStatus: 'open',
    educationLevel: ['ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Free laptop distribution scheme for final year students in government and government-aided colleges to enhance digital literacy.',
    applicationUrl: 'https://tn.gov.in',
    helpline: '044-25361520',
    documents: ['College ID Card', 'Final Year Bonafide', 'Aadhaar Card', 'Photo'],
    howToApply: ['Automatic eligibility for final year students', 'College prepares list', 'Government verification', 'Laptop distribution event'],
    benefits: [{ label: 'Benefit', value: 'Free Laptop' }, { label: 'Value', value: '~₹30,000' }, { label: 'For', value: 'Final Year Students' }]
  },

  // Additional TN State Schemes
  {
    id: 'tn-moovalur',
    name: 'Moovalur Ramamirtham Scheme',
    provider: 'Tamil Nadu Government',
    type: 'government',
    amount: '₹1,000/month',
    eligibility: ['Female Students', 'Government School Background', 'UG Studies'],
    deadline: 'Always Open',
    deadlineStatus: 'always-open',
    educationLevel: ['ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'female',
    state: 'Tamil Nadu',
    description: 'Monthly financial support for girl students from government schools pursuing higher education.',
    applicationUrl: 'https://scholarships.gov.in',
    helpline: '044-25361520',
    documents: ['School TC', 'College Admission', 'Aadhaar Card', 'Bank Account', 'Photo'],
    howToApply: ['Apply through college', 'Submit govt school TC', 'Bank verification', 'Monthly disbursement'],
    benefits: [{ label: 'Monthly Amount', value: '₹1,000' }, { label: 'Annual Total', value: '₹12,000' }, { label: 'For', value: 'Girl Students' }]
  },
  {
    id: 'tn-minority-welfare',
    name: 'Minority Welfare Scholarship',
    provider: 'Minority Welfare Department, TN',
    type: 'government',
    amount: 'Up to ₹15,000/year',
    eligibility: ['Minority Community', 'Income < ₹2 Lakh', 'TN Domicile'],
    deadline: 'Feb 15, 2026',
    deadlineStatus: 'open',
    educationLevel: ['12th-passed', 'ug', 'pg', 'diploma'],
    category: ['minority'],
    incomeLimit: '2',
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Scholarship for minority community students pursuing higher education.',
    applicationUrl: 'https://scholarships.gov.in',
    helpline: '1800-121-3513',
    documents: ['Minority Certificate', 'Income Certificate', 'Aadhaar Card', 'College Bonafide', 'Bank Details'],
    howToApply: ['Apply on NSP', 'Submit minority proof', 'Income verification', 'College attestation', 'Disbursement'],
    benefits: [{ label: 'Annual Amount', value: 'Up to ₹15,000' }, { label: 'Income Limit', value: '< ₹2 Lakh' }, { label: 'Community', value: 'Minority' }]
  },
  {
    id: 'tn-tribal-welfare',
    name: 'Tribal Welfare Scholarship',
    provider: 'Tribal Welfare Department, TN',
    type: 'government',
    amount: 'Up to ₹40,000/year',
    eligibility: ['ST Category', 'TN Domicile', 'Higher Education'],
    deadline: 'Feb 28, 2026',
    deadlineStatus: 'open',
    educationLevel: ['12th-passed', 'ug', 'pg', 'professional'],
    category: ['st'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Comprehensive scholarship for tribal students pursuing higher education.',
    applicationUrl: 'https://tribalwelfare.tn.gov.in',
    helpline: '044-28544490',
    documents: ['ST Certificate', 'Income Certificate', 'Admission Letter', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply through tribal welfare office', 'Submit ST certificate', 'Document verification', 'Scholarship release'],
    benefits: [{ label: 'Annual Amount', value: 'Up to ₹40,000' }, { label: 'Hostel', value: 'Additional Allowance' }, { label: 'Books', value: 'Grant Included' }]
  },
  {
    id: 'tn-differently-abled',
    name: 'Differently Abled Scholarship',
    provider: 'Dept for Welfare of Differently Abled, TN',
    type: 'government',
    amount: 'Up to ₹25,000/year',
    eligibility: ['40%+ Disability', 'TN Domicile', 'Any Course'],
    deadline: 'Mar 15, 2026',
    deadlineStatus: 'open',
    educationLevel: ['12th-passed', 'ug', 'pg', 'diploma', 'professional'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Scholarship for students with disabilities pursuing education.',
    applicationUrl: 'https://welfare.tn.gov.in',
    helpline: '044-25670066',
    documents: ['Disability Certificate', 'Medical Certificate', 'Admission Letter', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply on welfare portal', 'Submit disability certificate', 'Medical verification', 'Scholarship disbursement'],
    benefits: [{ label: 'Annual Amount', value: 'Up to ₹25,000' }, { label: 'Special Aids', value: 'Additional Support' }, { label: 'Transport', value: 'Allowance' }]
  },

  // ========================================
  // 2. CENTRAL GOVERNMENT SCHOLARSHIPS (NSP)
  // ========================================
  
  {
    id: 'pm-usp-central-sector',
    name: 'PM-USP (Central Sector Scheme)',
    provider: 'Ministry of Education, Govt of India',
    type: 'government',
    amount: '₹12,000/year (UG) | ₹20,000/year (PG)',
    eligibility: ['Top 20th Percentile in 12th Board', 'Income < ₹8 Lakh', 'UG/PG Students'],
    deadline: 'Dec 31, 2026',
    deadlineStatus: 'closing-soon',
    educationLevel: ['ug', 'pg'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    incomeLimit: '8',
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Central Sector Scholarship for students in the top 20th percentile of their 12th Board examination. Apply through NSP with One Time Registration (OTR).',
    applicationUrl: 'https://scholarships.gov.in',
    helpline: '1800-121-3513',
    documents: ['12th Marksheet', 'Board Percentile Certificate', 'Income Certificate', 'College Admission', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Complete OTR on NSP', 'Fill application form', 'Upload 12th percentile proof', 'College verification', 'Scholarship credited'],
    benefits: [{ label: 'UG Amount', value: '₹12,000/year' }, { label: 'PG Amount', value: '₹20,000/year' }, { label: 'Based on', value: 'Top 20th Percentile' }]
  },
  {
    id: 'inspire-she',
    name: 'INSPIRE (SHE) Scholarship',
    provider: 'DST, Govt of India',
    type: 'government',
    amount: '₹80,000/year',
    eligibility: ['Top 1% in 12th Marks', 'Basic Sciences (B.Sc/M.Sc)', 'Merit Based'],
    deadline: 'Dec 15, 2026',
    deadlineStatus: 'closing-soon',
    educationLevel: ['ug', 'pg'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Innovation in Science Pursuit for Inspired Research (INSPIRE) - Scholarship for Higher Education (SHE). For top 1% students pursuing Basic Sciences.',
    applicationUrl: 'https://online-inspire.gov.in',
    helpline: '011-26590349',
    documents: ['12th Marksheet', 'Top 1% Rank Certificate', 'Science Course Admission', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Verify top 1% eligibility', 'Apply on INSPIRE portal', 'Submit rank proof', 'Verification', 'Scholarship credited'],
    benefits: [{ label: 'Annual Amount', value: '₹80,000' }, { label: 'Summer Project', value: '₹20,000 extra' }, { label: 'For', value: 'B.Sc/M.Sc Students' }]
  },
  {
    id: 'aicte-pragati',
    name: 'AICTE Pragati Scholarship (Girls)',
    provider: 'AICTE, Govt of India',
    type: 'government',
    amount: '₹50,000/year',
    eligibility: ['Female Students', 'Technical Courses (B.E/B.Tech/Diploma)', 'Income < ₹8 Lakh'],
    deadline: 'Dec 31, 2026',
    deadlineStatus: 'closing-soon',
    educationLevel: ['diploma', 'professional'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    incomeLimit: '8',
    gender: 'female',
    state: 'Tamil Nadu',
    description: 'Exclusive scholarship for girl students in Technical courses including B.E., B.Tech, and Diploma programs.',
    applicationUrl: 'https://scholarships.gov.in',
    helpline: '011-29581000',
    documents: ['Income Certificate', 'Admission Letter', '12th Marksheet', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply on NSP', 'Select AICTE Pragati', 'Upload documents', 'Institute verification', 'Scholarship release'],
    benefits: [{ label: 'Annual Amount', value: '₹50,000' }, { label: 'For', value: 'Girls in Tech' }, { label: 'Courses', value: 'B.E/B.Tech/Diploma' }]
  },
  {
    id: 'gate-scholarship',
    name: 'GATE Scholarship',
    provider: 'MHRD, Govt of India',
    type: 'government',
    amount: '₹12,400/month',
    eligibility: ['GATE Exam Qualified', 'M.E/M.Tech Students', 'Admitted to IIT/NIT/Govt Colleges'],
    deadline: 'Based on Admission',
    deadlineStatus: 'open',
    educationLevel: ['pg'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Monthly stipend for PG students (M.E/M.Tech) who have qualified the GATE exam and admitted to recognized institutions.',
    applicationUrl: 'https://scholarships.gov.in',
    helpline: '011-26182813',
    documents: ['GATE Score Card', 'M.E/M.Tech Admission Letter', 'UG Degree Certificate', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Clear GATE exam', 'Get admission to M.E/M.Tech', 'Apply through institute', 'Scholarship credited monthly'],
    benefits: [{ label: 'Monthly Stipend', value: '₹12,400' }, { label: 'Duration', value: '2 Years (M.Tech)' }, { label: 'Contingency', value: '₹20,000/year' }]
  },
  {
    id: 'aicte-saksham',
    name: 'AICTE Saksham Scholarship (Disabled)',
    provider: 'AICTE, Govt of India',
    type: 'government',
    amount: '₹50,000/year',
    eligibility: ['40%+ Disability', 'Technical Courses', 'Income < ₹8 Lakh'],
    deadline: 'Dec 31, 2026',
    deadlineStatus: 'closing-soon',
    educationLevel: ['diploma', 'professional'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    incomeLimit: '8',
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Scholarship for differently abled students in technical education.',
    applicationUrl: 'https://scholarships.gov.in',
    helpline: '011-29581000',
    documents: ['Disability Certificate', 'Income Certificate', 'Admission Letter', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply on NSP', 'Select AICTE Saksham', 'Upload disability proof', 'Institute verification', 'Scholarship release'],
    benefits: [{ label: 'Annual Amount', value: '₹50,000' }, { label: 'For', value: 'Disabled Students' }, { label: 'Courses', value: 'Technical' }]
  },
  {
    id: 'pm-yasasvi',
    name: 'PM YASASVI Scholarship',
    provider: 'Ministry of Social Justice, Govt of India',
    type: 'government',
    amount: '₹75,000 - ₹1,25,000/year',
    eligibility: ['OBC/EBC/DNT', 'Income < ₹2.5 Lakh', 'Class 9-12'],
    deadline: 'Sep 30, 2026',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying'],
    category: ['obc', 'bc-mbc', 'ews'],
    incomeLimit: '2.5',
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'PM Young Achievers Scholarship for OBC/EBC/DNT students.',
    applicationUrl: 'https://yet.nta.ac.in',
    helpline: '011-40759000',
    documents: ['Caste Certificate', 'Income Certificate', 'School Bonafide', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Clear YASASVI entrance test', 'Apply on NTA portal', 'Document verification', 'Scholarship awarded'],
    benefits: [{ label: 'Class 9 Amount', value: '₹75,000/year' }, { label: 'Class 11 Amount', value: '₹1,25,000/year' }]
  },
  {
    id: 'nmms',
    name: 'National Merit Scholarship (NMMS)',
    provider: 'Ministry of Education, Govt of India',
    type: 'government',
    amount: '₹12,000/year',
    eligibility: ['Class 9-12 Students', 'Merit Based', 'Income < ₹3.5 Lakh'],
    deadline: 'Nov 30, 2026',
    deadlineStatus: 'closing-soon',
    educationLevel: ['12th-studying'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    incomeLimit: '3.5',
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'National merit scholarship for meritorious students from economically weaker sections.',
    applicationUrl: 'https://scholarships.gov.in',
    helpline: '1800-121-3513',
    documents: ['Income Certificate', 'Marksheets', 'Aadhaar Card', 'School Bonafide', 'Bank Details'],
    howToApply: ['Clear NMMS selection test', 'Apply through NSP', 'Submit documents', 'State verification', 'Scholarship awarded'],
    benefits: [{ label: 'Annual Amount', value: '₹12,000' }, { label: 'Duration', value: 'Class 9-12' }, { label: 'Selection', value: 'Merit Test' }]
  },
  {
    id: 'nsigse',
    name: 'National Scheme of Incentives for Girls (NSIGSE)',
    provider: 'Ministry of Education, Govt of India',
    type: 'government',
    amount: '₹3,000 (One-time)',
    eligibility: ['SC/ST Girls', 'Class 10 Pass', 'Enrollment in Class 11'],
    deadline: 'Rolling',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying'],
    category: ['sc', 'st'],
    gender: 'female',
    state: 'Tamil Nadu',
    description: 'Incentive for SC/ST girl students to continue education after 10th.',
    applicationUrl: 'https://scholarships.gov.in',
    helpline: '1800-121-3513',
    documents: ['10th Marksheet', 'Class 11 Admission', 'SC/ST Certificate', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply on NSP after Class 10', 'Submit caste certificate', 'Enrollment proof in 11th', 'One-time amount credited'],
    benefits: [{ label: 'One-time Amount', value: '₹3,000' }, { label: 'For', value: 'SC/ST Girls' }, { label: 'Purpose', value: 'Continue Higher Secondary' }]
  },

  // ========================================
  // 3. CORPORATE & CSR SCHOLARSHIPS
  // ========================================
  
  {
    id: 'reliance-foundation-ug',
    name: 'Reliance Foundation Scholarship (UG)',
    provider: 'Reliance Foundation (Vidyasaarathi)',
    type: 'corporate',
    amount: 'Up to ₹2 Lakhs',
    eligibility: ['UG Students', 'Online Aptitude Test', 'Merit + Need Based'],
    deadline: 'Mar 31, 2026',
    deadlineStatus: 'open',
    educationLevel: ['ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Undergraduate scholarship based on online aptitude test performance. Apply through Vidyasaarathi portal.',
    applicationUrl: 'https://www.vidyasaarathi.co.in',
    helpline: '1800-419-8800',
    documents: ['12th Marksheet', 'College Admission Letter', 'Income Certificate', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Register on Vidyasaarathi', 'Apply for Reliance Foundation', 'Clear online aptitude test', 'Document verification', 'Scholarship awarded'],
    benefits: [{ label: 'Maximum Amount', value: 'Up to ₹2 Lakhs' }, { label: 'Selection', value: 'Aptitude Test' }, { label: 'Level', value: 'UG Students' }]
  },
  {
    id: 'reliance-foundation-pg',
    name: 'Reliance Foundation Scholarship (PG)',
    provider: 'Reliance Foundation (Vidyasaarathi)',
    type: 'corporate',
    amount: 'Up to ₹6 Lakhs',
    eligibility: ['PG Students', 'AI/Computer Science/Life Sciences', 'Merit Based'],
    deadline: 'Mar 31, 2026',
    deadlineStatus: 'open',
    educationLevel: ['pg'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Postgraduate scholarship with focus on AI, Computer Science, and Life Sciences. Higher scholarship amount for specialized courses.',
    applicationUrl: 'https://www.vidyasaarathi.co.in',
    helpline: '1800-419-8800',
    documents: ['UG Degree Certificate', 'PG Admission Letter', 'Academic Transcripts', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Register on Vidyasaarathi', 'Apply for PG scholarship', 'Submit specialization proof', 'Selection process', 'Scholarship disbursement'],
    benefits: [{ label: 'Maximum Amount', value: 'Up to ₹6 Lakhs' }, { label: 'Focus Areas', value: 'AI, CS, Life Sciences' }, { label: 'Level', value: 'PG Students' }]
  },
  {
    id: 'hdfc-parivartan-ecss',
    name: 'HDFC Bank Parivartan ECSS',
    provider: 'HDFC Bank (Vidyasaarathi)',
    type: 'corporate',
    amount: 'Up to ₹75,000',
    eligibility: ['12th to PG Students', 'Merit-cum-Means', 'Income < ₹2.5 Lakh'],
    deadline: 'Feb 28, 2026',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying', '12th-passed', 'ug', 'pg'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    incomeLimit: '2.5',
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Educational Crisis Scholarship Support for students from 12th to PG level based on merit and financial need.',
    applicationUrl: 'https://www.vidyasaarathi.co.in',
    helpline: '1800-419-8800',
    documents: ['Income Certificate', 'Academic Records', 'Admission Letter', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Register on Vidyasaarathi', 'Select HDFC Parivartan', 'Submit merit + income proof', 'Verification', 'Scholarship credited'],
    benefits: [{ label: 'Maximum Amount', value: '₹75,000' }, { label: 'Type', value: 'Merit-cum-Means' }, { label: 'Range', value: '12th to PG' }]
  },
  {
    id: 'infosys-stem-stars',
    name: 'Infosys Foundation STEM Stars',
    provider: 'Infosys Foundation',
    type: 'corporate',
    amount: 'Up to ₹1,00,000',
    eligibility: ['Girl Students Only', 'STEM Fields (Science, Tech, Eng, Math)', 'UG Students'],
    deadline: 'Mar 15, 2026',
    deadlineStatus: 'open',
    educationLevel: ['ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'female',
    state: 'Tamil Nadu',
    description: 'Specifically for girl students entering STEM fields - Science, Technology, Engineering, and Mathematics.',
    applicationUrl: 'https://www.infosys.com/infosys-foundation',
    helpline: '080-41581111',
    documents: ['12th Marksheet (Science)', 'STEM Course Admission', 'Income Certificate', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply on Infosys Foundation portal', 'Submit STEM course proof', 'Academic verification', 'Selection', 'Scholarship awarded'],
    benefits: [{ label: 'Maximum Amount', value: '₹1,00,000' }, { label: 'For', value: 'Girls in STEM' }, { label: 'Fields', value: 'Science/Tech/Eng/Math' }]
  },
  {
    id: 'kotak-kanya-scholarship',
    name: 'Kotak Kanya Scholarship',
    provider: 'Kotak Education Foundation',
    type: 'corporate',
    amount: 'Up to ₹1,50,000',
    eligibility: ['Meritorious Girl Students', 'After 12th', 'Low-Income Families'],
    deadline: 'Mar 31, 2026',
    deadlineStatus: 'open',
    educationLevel: ['12th-passed', 'ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'female',
    state: 'Tamil Nadu',
    description: 'Financial aid for meritorious girl students from low-income families after 12th standard.',
    applicationUrl: 'https://www.kotakeducation.org',
    helpline: '022-66056666',
    documents: ['12th Marksheet', 'Income Certificate', 'College Admission', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply on Kotak Education portal', 'Submit merit + income proof', 'Selection process', 'Scholarship disbursement'],
    benefits: [{ label: 'Maximum Amount', value: '₹1,50,000' }, { label: 'For', value: 'Girls after 12th' }, { label: 'Criteria', value: 'Merit + Need' }]
  },
  {
    id: 'tata-trusts-scholarship',
    name: 'Tata Trusts Scholarship',
    provider: 'Tata Trusts',
    type: 'corporate',
    amount: 'Up to ₹50,000',
    eligibility: ['Medical/Engineering Students', 'Need Based', 'Merit Performers'],
    deadline: 'Feb 28, 2026',
    deadlineStatus: 'open',
    educationLevel: ['professional'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Scholarship for meritorious students in Medical and Engineering courses.',
    applicationUrl: 'https://tatatrusts.org',
    helpline: '022-66658282',
    documents: ['Entrance Exam Score', 'Course Admission', 'Income Certificate', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply on Tata Trusts portal', 'Submit documents', 'Selection', 'Scholarship awarded'],
    benefits: [{ label: 'Amount', value: 'Up to ₹50,000' }, { label: 'For', value: 'Medical/Engineering' }]
  },
  {
    id: 'larsen-toubro-scholarship',
    name: 'L&T Build India Scholarship',
    provider: 'Larsen & Toubro',
    type: 'corporate',
    amount: 'Up to ₹50,000',
    eligibility: ['Engineering Students', 'Income < ₹6 Lakh', 'Merit Based'],
    deadline: 'Mar 31, 2026',
    deadlineStatus: 'open',
    educationLevel: ['professional'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    incomeLimit: '6',
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Scholarship for engineering students from economically weaker sections.',
    applicationUrl: 'https://www.lntecc.com',
    helpline: '022-67525656',
    documents: ['JEE Score Card', 'Engineering Admission', 'Income Certificate', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply through L&T portal', 'Submit documents', 'Selection', 'Scholarship awarded'],
    benefits: [{ label: 'Amount', value: 'Up to ₹50,000' }, { label: 'For', value: 'Engineering' }]
  },
  {
    id: 'wipro-scholarship',
    name: 'Wipro Education Scholarship',
    provider: 'Wipro Foundation',
    type: 'corporate',
    amount: 'Up to ₹75,000',
    eligibility: ['Tech/Science Students', 'UG Courses', 'Merit Based'],
    deadline: 'Mar 15, 2026',
    deadlineStatus: 'open',
    educationLevel: ['ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Scholarship for students pursuing technology and science courses.',
    applicationUrl: 'https://www.wipro.com/corporate-responsibility',
    helpline: '080-28440011',
    documents: ['12th Marksheet', 'Course Admission', 'Income Certificate', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply on Wipro portal', 'Submit documents', 'Selection', 'Scholarship awarded'],
    benefits: [{ label: 'Amount', value: 'Up to ₹75,000' }, { label: 'For', value: 'Tech/Science' }]
  },
  {
    id: 'icici-vidyasaarathi',
    name: 'ICICI Foundation Scholarship',
    provider: 'ICICI Foundation',
    type: 'corporate',
    amount: 'Up to ₹50,000',
    eligibility: ['UG/Professional Students', 'Income < ₹3 Lakh', 'Merit Based'],
    deadline: 'Feb 28, 2026',
    deadlineStatus: 'open',
    educationLevel: ['ug', 'professional'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    incomeLimit: '3',
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Scholarship for undergraduate and professional course students.',
    applicationUrl: 'https://www.vidyasaarathi.co.in',
    helpline: '1800-419-8800',
    documents: ['Academic Records', 'Course Admission', 'Income Certificate', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply on Vidyasaarathi', 'Submit documents', 'Selection', 'Scholarship awarded'],
    benefits: [{ label: 'Amount', value: 'Up to ₹50,000' }]
  },

  // ========================================
  // 4. NGO & FOUNDATION SCHOLARSHIPS
  // ========================================
  
  {
    id: 'agaram-vidhai',
    name: 'Agaram Foundation (Vidhai)',
    provider: 'Agaram Foundation',
    type: 'ngo',
    amount: 'Full Education + Hostel Fees',
    eligibility: ['First-Generation Rural Students', 'Economically Weak', 'Higher Education'],
    deadline: 'Rolling (Home Visits)',
    deadlineStatus: 'open',
    educationLevel: ['12th-passed', 'ug', 'professional'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Supports first-generation rural students with full education and hostel fees. Involves personal interviews and home visits to verify need.',
    applicationUrl: 'https://www.agaramfoundation.org',
    helpline: '044-42047474',
    documents: ['Parent Education Declaration', 'Income Certificate', 'Rural Residence Proof', 'Academic Records', 'Aadhaar Card'],
    howToApply: ['Apply on Agaram website', 'Submit background documents', 'Personal interview', 'Home visit verification', 'Full support begins'],
    benefits: [{ label: 'Fee Coverage', value: 'Full Education' }, { label: 'Hostel', value: 'Full Coverage' }, { label: 'For', value: 'First-Gen Rural Students' }]
  },
  {
    id: 'maatram-foundation',
    name: 'Maatram Foundation Scholarship',
    provider: 'Maatram Foundation',
    type: 'ngo',
    amount: 'Tuition + Hostel + Transport',
    eligibility: ['Underprivileged Students', 'Partner College Admission', 'Need Based'],
    deadline: 'Rolling',
    deadlineStatus: 'open',
    educationLevel: ['12th-passed', 'ug', 'professional'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Provides free higher education including Tuition, Hostel, and Transport by partnering with colleges like Sathyabama, SRM, and others.',
    applicationUrl: 'https://www.maatram.org',
    helpline: '044-24621555',
    documents: ['Income Certificate', 'Academic Records', 'College Admission', 'Aadhaar Card', 'Family Background Details'],
    howToApply: ['Apply through Maatram website', 'Document submission', 'Interview process', 'Partner college admission', 'Full support provided'],
    benefits: [{ label: 'Tuition', value: 'Full Coverage' }, { label: 'Hostel', value: 'Covered' }, { label: 'Transport', value: 'Included' }]
  },
  {
    id: 'vidyadhan-sdf',
    name: 'Vidyadhan (Sarojini Damodaran Foundation)',
    provider: 'Sarojini Damodaran Foundation',
    type: 'ngo',
    amount: '₹10,000 - ₹75,000/year',
    eligibility: ['After 10th/12th Students', 'Economically Weak', 'Merit Based'],
    deadline: 'Post 10th/12th Results',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying', '12th-passed', 'ug', 'pg'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Selects students after 10th/12th. Provides ₹10k to ₹75k per year depending on the course pursued.',
    applicationUrl: 'https://www.vidyadhan.org',
    helpline: '080-40952020',
    documents: ['10th/12th Marksheet', 'Income Certificate', 'Course Admission', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply after 10th/12th results', 'Submit documents', 'Selection test', 'Interview', 'Scholarship begins'],
    benefits: [{ label: 'Range', value: '₹10,000 - ₹75,000' }, { label: 'Based on', value: 'Course Type' }, { label: 'Selection', value: 'Post 10th/12th' }]
  },
  {
    id: 'ffe-scholarship',
    name: 'Foundation For Excellence (FFE)',
    provider: 'Foundation For Excellence',
    type: 'ngo',
    amount: 'Up to ₹1,50,000/year',
    eligibility: ['Engineering/Medical/B.Pharm Students', 'High Entrance Rank (JEE/NEET)', 'Low Income Family'],
    deadline: 'Post Counseling',
    deadlineStatus: 'open',
    educationLevel: ['professional'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Supports students in Engineering, Medical, and B.Pharm. Requires high entrance rank (JEE/NEET) and financial need.',
    applicationUrl: 'https://www.ffe.org',
    helpline: '080-67315555',
    documents: ['JEE/NEET Score Card', 'Counseling Allotment', 'Income Certificate', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply after counseling allotment', 'Submit entrance rank proof', 'Income verification', 'Selection', 'Multi-year support'],
    benefits: [{ label: 'Maximum Amount', value: '₹1,50,000/year' }, { label: 'Courses', value: 'Engg/Medical/B.Pharm' }, { label: 'Criteria', value: 'Rank + Need' }]
  },
  {
    id: 'hope-foundation-scholarship',
    name: 'HOPE Foundation Scholarship',
    provider: 'HOPE Foundation',
    type: 'ngo',
    amount: 'Up to ₹50,000',
    eligibility: ['Orphan/Semi-Orphan Students', 'Higher Education', 'TN Domicile'],
    deadline: 'Rolling',
    deadlineStatus: 'open',
    educationLevel: ['12th-passed', 'ug', 'pg'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Special scholarship for orphan and semi-orphan students pursuing higher education.',
    applicationUrl: 'https://www.hopefoundation.org.in',
    helpline: '044-24350707',
    documents: ['Parent Death Certificate (if applicable)', 'Guardian Details', 'Income Proof', 'Academic Records', 'Aadhaar Card'],
    howToApply: ['Apply on HOPE Foundation website', 'Submit documents', 'Verification', 'Scholarship awarded'],
    benefits: [{ label: 'Amount', value: 'Up to ₹50,000' }, { label: 'For', value: 'Orphan/Semi-Orphan' }]
  },
  {
    id: 'giveindia-education',
    name: 'GiveIndia Education Scholarship',
    provider: 'GiveIndia Foundation',
    type: 'ngo',
    amount: 'Up to ₹40,000',
    eligibility: ['Economically Weak', 'UG Studies', 'Need Based'],
    deadline: 'Rolling',
    deadlineStatus: 'open',
    educationLevel: ['ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Scholarship for economically weak students through GiveIndia platform.',
    applicationUrl: 'https://www.giveindia.org',
    helpline: '080-67456000',
    documents: ['Income Certificate', 'Course Admission', 'Academic Records', 'Aadhaar Card'],
    howToApply: ['Apply through GiveIndia NGO partner', 'Submit documents', 'Selection', 'Scholarship awarded'],
    benefits: [{ label: 'Amount', value: 'Up to ₹40,000' }]
  },
  {
    id: 'fair-and-lovely-foundation',
    name: 'Fair & Lovely Foundation Scholarship',
    provider: 'Fair & Lovely Foundation',
    type: 'ngo',
    amount: 'Up to ₹50,000',
    eligibility: ['Female Students', 'Class 12 to PG', 'Economic Need'],
    deadline: 'Feb 28, 2026',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying', '12th-passed', 'ug', 'pg'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'female',
    state: 'Tamil Nadu',
    description: 'Scholarship exclusively for female students from economically weaker backgrounds.',
    applicationUrl: 'https://www.fairandlovelyfoundation.org',
    helpline: '022-39832000',
    documents: ['Income Certificate', 'Academic Records', 'Course Admission', 'Aadhaar Card', 'Bank Details'],
    howToApply: ['Apply on foundation website', 'Submit documents', 'Selection', 'Scholarship awarded'],
    benefits: [{ label: 'Amount', value: 'Up to ₹50,000' }, { label: 'For', value: 'Female Students' }]
  },
  {
    id: 'isha-vidya-scholarship',
    name: 'Isha Vidhya Scholarship',
    provider: 'Isha Foundation',
    type: 'ngo',
    amount: 'Full Education Support',
    eligibility: ['Rural Students', 'School Education', 'TN Villages'],
    deadline: 'Rolling',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Free quality education for rural children in Tamil Nadu villages.',
    applicationUrl: 'https://www.ishavidhya.org',
    helpline: '0422-2515345',
    documents: ['Rural Residence Proof', 'Family Income Details', 'Academic Records', 'Aadhaar Card'],
    howToApply: ['Apply through Isha Vidhya schools', 'Home verification', 'Admission test', 'Free education begins'],
    benefits: [{ label: 'Coverage', value: 'Full Education' }, { label: 'For', value: 'Rural Students' }]
  },
  {
    id: 'akshaya-patra-scholarship',
    name: 'Akshaya Patra Scholarship',
    provider: 'Akshaya Patra Foundation',
    type: 'ngo',
    amount: 'Up to ₹25,000',
    eligibility: ['Government School Students', 'Higher Education', 'Beneficiary Children'],
    deadline: 'Mar 31, 2026',
    deadlineStatus: 'open',
    educationLevel: ['12th-passed', 'ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Scholarship for students who were beneficiaries of Akshaya Patra mid-day meal program.',
    applicationUrl: 'https://www.akshayapatra.org',
    helpline: '1800-425-8622',
    documents: ['Beneficiary Proof', 'School Records', 'College Admission', 'Aadhaar Card'],
    howToApply: ['Apply through Akshaya Patra center', 'Verify beneficiary status', 'Selection', 'Scholarship awarded'],
    benefits: [{ label: 'Amount', value: 'Up to ₹25,000' }]
  },
  {
    id: 'nanhi-kali-scholarship',
    name: 'Nanhi Kali Scholarship',
    provider: 'K.C. Mahindra Education Trust',
    type: 'ngo',
    amount: 'Up to ₹30,000',
    eligibility: ['Girl Students', 'School Education', 'Underprivileged'],
    deadline: 'Rolling',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'female',
    state: 'Tamil Nadu',
    description: 'Education support for underprivileged girl children.',
    applicationUrl: 'https://www.nanhikali.org',
    helpline: '022-24901100',
    documents: ['Income Certificate', 'School Admission', 'Academic Records', 'Aadhaar Card'],
    howToApply: ['Apply through Nanhi Kali partner', 'Verification', 'Selection', 'Support begins'],
    benefits: [{ label: 'Amount', value: 'Up to ₹30,000' }, { label: 'Materials', value: 'Books + Uniform' }]
  },

  // ========================================
  // 5. SPORTS SCHOLARSHIPS
  // ========================================

  // -----------------------------------------
  // 5.1 Tamil Nadu State Government (SDAT)
  // -----------------------------------------
  
  {
    id: 'tn-sdat-champions-development',
    name: 'Champions Development Scheme (CDS)',
    provider: 'Sports Development Authority of Tamil Nadu (SDAT)',
    type: 'sports',
    amount: '₹2.00 Lakh per annum',
    eligibility: ['National-level Gold Medalists', 'Age Under 20 Years', 'TN Domicile'],
    deadline: 'Throughout Year',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying', '12th-passed', 'ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Financial support for national-level gold medalists under 20 years. Covers kits, training, and competition expenses.',
    applicationUrl: 'https://sdat.tn.gov.in',
    helpline: '044-25672222',
    documents: ['National Gold Medal Certificate', 'Age Proof', 'State Sports Association Certificate', 'Form III/II', 'Bank Details'],
    howToApply: ['Apply through SDAT', 'Submit national medal proof', 'Age verification', 'Selection & Approval'],
    benefits: [{ label: 'Annual Amount', value: '₹2.00 Lakh' }, { label: 'For', value: 'Kits, Training, Competition' }, { label: 'Age Limit', value: 'Under 20' }]
  },
  {
    id: 'tn-sdat-elite-sports',
    name: 'Special Scholarship for Elite Sportspersons',
    provider: 'Sports Development Authority of Tamil Nadu (SDAT)',
    type: 'sports',
    amount: 'Up to ₹30.00 Lakh per annum',
    eligibility: ['International/Olympic Level Athletes', 'TN Domicile', 'Elite Performance Record'],
    deadline: 'Throughout Year',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying', '12th-passed', 'ug', 'pg', 'professional'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Premium support for international and Olympic-level athletes from Tamil Nadu. Covers specialized training and world-class equipment.',
    applicationUrl: 'https://sdat.tn.gov.in',
    helpline: '044-25672222',
    documents: ['International/Olympic Medal Certificates', 'Sports Federation Recommendation', 'Form III/II', 'TN Domicile Proof', 'Bank Details'],
    howToApply: ['Nomination by State Association', 'SDAT selection committee', 'Performance review', 'Annual support granted'],
    benefits: [{ label: 'Annual Support', value: 'Up to ₹30 Lakh' }, { label: 'Training', value: 'Specialized' }, { label: 'Equipment', value: 'World-class' }]
  },
  {
    id: 'tn-sdat-mims',
    name: 'Mission International Medals Scheme (MIMS)',
    provider: 'Sports Development Authority of Tamil Nadu (SDAT)',
    type: 'sports',
    amount: '₹12.00 Lakh per annum',
    eligibility: ['Athletes with International Potential', 'TN Domicile', 'State/National Level Performance'],
    deadline: 'Throughout Year',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying', '12th-passed', 'ug', 'pg'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Support for athletes with potential to win international medals. Covers foreign training camps and specialized gear.',
    applicationUrl: 'https://sdat.tn.gov.in',
    helpline: '044-25672222',
    documents: ['State/National Performance Certificates', 'Potential Assessment Report', 'Form III/II', 'TN Domicile', 'Bank Details'],
    howToApply: ['Identification by SDAT scouts', 'Performance evaluation', 'Selection for international training', 'Annual grant begins'],
    benefits: [{ label: 'Annual Amount', value: '₹12 Lakh' }, { label: 'Foreign Training', value: 'Included' }, { label: 'Gear', value: 'Specialized' }]
  },
  {
    id: 'tn-sdat-world-beaters',
    name: 'World Beaters Talent Spotting Scheme',
    provider: 'Sports Development Authority of Tamil Nadu (SDAT)',
    type: 'sports',
    amount: 'Coaching + Dietary Support (Free)',
    eligibility: ['School Students (6th-12th)', 'Physical Aptitude Test Selection', 'TN Government Schools'],
    deadline: 'Academic Year Based',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Early talent identification program for school children through physical aptitude tests. Provides specialized coaching and nutrition at Government sports hostels.',
    applicationUrl: 'https://sdat.tn.gov.in',
    helpline: '044-25672222',
    documents: ['School ID Card', 'Physical Aptitude Test Results', 'Parent Consent', 'Age Proof', 'TN Domicile'],
    howToApply: ['School-level aptitude tests', 'District-level selection', 'Admission to sports hostel', 'Training begins'],
    benefits: [{ label: 'Coaching', value: 'Specialized' }, { label: 'Diet', value: 'High-Protein' }, { label: 'Hostel', value: 'Government' }]
  },

  // -----------------------------------------
  // 5.2 Central Government (National) Schemes
  // -----------------------------------------
  
  {
    id: 'khelo-india-scholarship',
    name: 'Khelo India Scholarship',
    provider: 'Ministry of Youth Affairs & Sports (SAI)',
    type: 'sports',
    amount: '₹5 Lakh/year (8 years)',
    eligibility: ['Selected from Khelo India Games', 'School/College Level Athletes', 'Medal Winners'],
    deadline: 'Post Khelo India Games',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying', '12th-passed', 'ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Comprehensive 8-year scholarship for talented athletes from Khelo India Games. ₹1.2 Lakh direct stipend + ₹3.8 Lakh for training, diet, and medical expenses annually.',
    applicationUrl: 'https://kheloindia.gov.in',
    helpline: '011-24360808',
    documents: ['Khelo India Selection Certificate', 'Age Proof', 'Education Certificate', 'Form III/II', 'Bank Details'],
    howToApply: ['Perform at Khelo India Games', 'Selection by Sports Ministry', 'Documentation', '8-year support begins'],
    benefits: [{ label: 'Annual Total', value: '₹5 Lakh' }, { label: 'Direct Stipend', value: '₹1.2 Lakh' }, { label: 'Duration', value: '8 Years' }]
  },
  {
    id: 'sai-training-centers',
    name: 'SAI Training Centers Scholarship',
    provider: 'Sports Authority of India (SAI)',
    type: 'sports',
    amount: '100% Free - Education, Diet, Coaching & Kits',
    eligibility: ['Residential Trainees at SAI', 'Selected through Trials', 'Age 12-25'],
    deadline: 'Throughout Year',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying', '12th-passed', 'ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Complete residential support for athletes training at SAI centers. Includes 100% free education, high-protein diet, expert coaching, and sports kits.',
    applicationUrl: 'https://sportsauthorityofindia.nic.in',
    helpline: '011-26165655',
    documents: ['Sports Achievement Certificates', 'Trial Selection Proof', 'Age Proof', 'Medical Fitness', 'Bank Details'],
    howToApply: ['Attend SAI trials', 'Selection based on performance', 'Join residential program', 'Full support provided'],
    benefits: [{ label: 'Education', value: '100% Free' }, { label: 'Diet', value: 'High-Protein' }, { label: 'Coaching', value: 'Expert' }]
  },

  // -----------------------------------------
  // 5.3 Public Sector (PSU) & Corporate
  // -----------------------------------------
  
  {
    id: 'iocl-indian-oil-acers',
    name: 'IndianOil Acers Scholarship',
    provider: 'Indian Oil Corporation Limited (IOCL)',
    type: 'sports',
    amount: '₹12,000 - ₹19,000/month',
    eligibility: ['Age 13-19 Years', 'Junior/Sub-Junior Athletes', 'Multiple Sports Disciplines'],
    deadline: 'Rolling Applications',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying', '12th-passed', 'ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Monthly stipend for promising young athletes. 50% seats reserved for female athletes. Includes special "Divyashakti" category for Para-athletes.',
    applicationUrl: 'https://iocl.com/sports',
    helpline: '011-26262000',
    documents: ['Sports Certificates', 'Age Proof', 'State Association Recommendation', 'Form III/II', 'Bank Details'],
    howToApply: ['Apply through sports federation', 'Selection process', 'Trials', 'Monthly stipend begins'],
    benefits: [{ label: 'Monthly Stipend', value: '₹12,000-₹19,000' }, { label: 'Female Quota', value: '50% Reserved' }, { label: 'Para-Athletes', value: 'Divyashakti Category' }]
  },
  {
    id: 'ongc-sports-scholarship',
    name: 'ONGC Sports Scholarship',
    provider: 'Oil and Natural Gas Corporation (ONGC)',
    type: 'sports',
    amount: '₹15,000 - ₹30,000/month',
    eligibility: ['Age 15-20 Years', 'National/International Rankings', 'Family Income < ₹5 Lakh'],
    deadline: 'Rolling Applications',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying', '12th-passed', 'ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    incomeLimit: '5',
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Strictly merit-based scholarship looking at National/International singles rankings (Badminton, Tennis) or Best Single Performance (Athletics, Football).',
    applicationUrl: 'https://www.ongcindia.com',
    helpline: '011-26756000',
    documents: ['National/International Ranking Proof', 'Income Certificate (< ₹5L)', 'Form III/II', 'Age Proof', 'Bank Details'],
    howToApply: ['Apply with ranking proof', 'Merit-based selection', 'No double benefit rule', 'Monthly support begins'],
    benefits: [{ label: 'Monthly Stipend', value: '₹15,000-₹30,000' }, { label: 'Selection', value: 'Merit-Based' }, { label: 'Income Limit', value: '< ₹5 Lakh' }]
  },
  {
    id: 'aai-sports-scholarship',
    name: 'Airports Authority Sports Scholarship',
    provider: 'Airports Authority of India (AAI)',
    type: 'sports',
    amount: '₹15,000 - ₹20,000/month',
    eligibility: ['Age 14-24 Years', 'State/National Level Athletes', 'Multiple Disciplines'],
    deadline: 'Rolling Applications',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying', '12th-passed', 'ug', 'pg'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Monthly scholarship for talented athletes aged 14-24. No double benefit allowed - cannot receive money from any other sports scholarship simultaneously.',
    applicationUrl: 'https://www.aai.aero',
    helpline: '011-24632950',
    documents: ['Sports Achievement Certificates', 'State/National Selection Proof', 'Form III/II', 'Age Proof', 'No Other Scholarship Declaration'],
    howToApply: ['Apply through AAI sports wing', 'Submit achievements', 'Verification of no double benefit', 'Monthly support begins'],
    benefits: [{ label: 'Monthly Stipend', value: '₹15,000-₹20,000' }, { label: 'Age Range', value: '14-24 Years' }, { label: 'Condition', value: 'No Double Benefit' }]
  },
  {
    id: 'reliance-foundation-sports',
    name: 'Reliance Foundation Sports Scholarship',
    provider: 'Reliance Foundation',
    type: 'sports',
    amount: 'Full Funding - Training & Travel',
    eligibility: ['Junior/Senior Level Athletes', 'High Potential', 'Multiple Sports'],
    deadline: 'Rolling Applications',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying', '12th-passed', 'ug', 'pg'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Comprehensive funding for junior and senior athletes covering training expenses, domestic/international travel, equipment, and competition costs.',
    applicationUrl: 'https://www.reliancefoundation.org',
    helpline: '022-35553000',
    documents: ['Sports Achievements', 'Potential Assessment', 'Federation Recommendation', 'Bank Details'],
    howToApply: ['Apply through Reliance Foundation', 'Performance evaluation', 'Selection', 'Full funding support'],
    benefits: [{ label: 'Training', value: 'Full Funding' }, { label: 'Travel', value: 'Domestic + International' }, { label: 'Equipment', value: 'Covered' }]
  },

  // -----------------------------------------
  // 5.4 Private University & College Sports Quota
  // -----------------------------------------
  
  {
    id: 'college-sports-quota-national',
    name: 'College Sports Quota - 100% Fee Waiver',
    provider: 'Private Universities (PSG, KCT, SKCET, KPRIET, etc.)',
    type: 'sports',
    amount: '100% Fee Waiver + Free Hostel & Food',
    eligibility: ['International/National Medalists', 'Trials Selection', 'UG/PG Admission'],
    deadline: 'Admission Season',
    deadlineStatus: 'open',
    educationLevel: ['ug', 'pg'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Top colleges in Coimbatore, Namakkal, Erode belt offer 100% fee waiver for international/national medalists. Includes free hostel and food for college team members.',
    applicationUrl: 'https://www.psgtech.edu',
    helpline: '0422-2572177',
    documents: ['International/National Medal Certificates', 'Form III & Form II from State/National Association', 'Admission Documents', 'Bank Details'],
    howToApply: ['Attend college sports trials', 'Submit Form III & Form II certificates', 'Skill assessment', 'Fee waiver granted'],
    benefits: [{ label: 'Fee Waiver', value: '100%' }, { label: 'Hostel', value: 'Free' }, { label: 'Food', value: 'Free' }]
  },
  {
    id: 'college-sports-quota-state',
    name: 'College Sports Quota - 50% Fee Waiver',
    provider: 'Private Universities (Paavai, KSR, Vivekanandha, Mahendra)',
    type: 'sports',
    amount: '50% Fee Waiver',
    eligibility: ['State-level/Zonal Medalists', 'Trials Selection', 'UG/PG Admission'],
    deadline: 'Admission Season',
    deadlineStatus: 'open',
    educationLevel: ['ug', 'pg'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: '50% fee waiver for state-level and zonal medalists at autonomous colleges. Vivekanandha offers special quota for women athletes.',
    applicationUrl: 'https://pmu.edu',
    helpline: '04286-225000',
    documents: ['State/Zonal Medal Certificates', 'Form III & Form II from State Association', 'Admission Documents', 'Bank Details'],
    howToApply: ['Apply with sports certificates', 'College sports trial', 'Form III & II verification', '50% fee waiver applied'],
    benefits: [{ label: 'Fee Waiver', value: '50%' }, { label: 'Team Membership', value: 'College Team' }, { label: 'Special', value: 'Women Athletes (Vivekanandha)' }]
  },

  // ══════════════════════════════════════════════════════════════
  // 6. TAMIL NADU SPORTS SCHOLARSHIPS (New — TN-specific)
  // ══════════════════════════════════════════════════════════════

  {
    id: 'tn-sdat-higher-secondary',
    name: 'SDAT Sports Scholarship (Higher Secondary)',
    provider: 'Sports Development Authority of Tamil Nadu (SDAT)',
    type: 'sports',
    amount: 'Up to ₹13,000/month',
    eligibility: ['Higher Secondary School students in Tamil Nadu', 'Medal winners at National School Games (SGFI)', 'Medal at National/Inter-State Championships by National Federations', 'Top 3 in Khelo India / National Games individual events', '1st/2nd in team games'],
    deadline: 'Jun–Oct 2026',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'SDAT scholarship targeting medal-winning Higher Secondary School students domiciled in Tamil Nadu. National level medal winners in SGFI, Khelo India, or National Games are eligible for up to ₹13,000 per month.',
    applicationUrl: 'https://sdat.tn.gov.in',
    helpline: '044-25672222',
    documents: ['Sports Achievement Certificate (National/State)', 'School Bonafide Certificate', 'Aadhaar-Linked Bank Account', 'Community Certificate', 'TN Domicile Proof'],
    howToApply: ['Apply through SDAT portal or school nomination', 'Submit medal/participation certificates', 'SDAT verification committee review', 'Monthly stipend via DBT'],
    benefits: [{ label: 'Monthly Stipend', value: 'Up to ₹13,000' }, { label: 'Level', value: 'National Medalists' }, { label: 'Duration', value: 'Academic Year' }]
  },
  {
    id: 'tn-cm-sports-award',
    name: "Chief Minister's State Sports Award",
    provider: 'Government of Tamil Nadu',
    type: 'sports',
    amount: '₹1,00,000 (One-Time)',
    eligibility: ['Outstanding sports persons from Tamil Nadu', 'Coaches with exceptional track record', 'Physical Education Teachers with notable contributions', 'TN domicile required'],
    deadline: 'Dec 2026',
    deadlineStatus: 'open',
    educationLevel: ['12th-studying', '12th-passed', 'ug', 'pg', 'diploma', 'professional'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Annual award by the Government of Tamil Nadu recognizing outstanding sports persons, coaches, and Physical Education Teachers. Consists of a citation, a replica, and a cash award of ₹1 Lakh.',
    applicationUrl: 'https://sdat.tn.gov.in',
    helpline: '044-25672222',
    documents: ['Sports Achievement Certificates', 'Identity Proof', 'Nomination/Recommendation Letter', 'TN Domicile Proof'],
    howToApply: ['Nomination by Sports Association or State body', 'SDAT selection committee evaluation', 'Award ceremony announcement', 'Cash prize + citation awarded'],
    benefits: [{ label: 'Cash Award', value: '₹1,00,000' }, { label: 'Citation', value: 'Yes' }, { label: 'Replica', value: 'Yes' }]
  },
  {
    id: 'tn-sports-welfare-fund',
    name: 'Tamil Nadu Sports Persons Welfare Fund',
    provider: 'Government of Tamil Nadu',
    type: 'sports',
    amount: 'Financial Assistance (Varies)',
    eligibility: ['Sports persons injured during National/State competitions', 'Athletes who suffered losses during participation', 'TN domicile required'],
    deadline: 'Throughout Year',
    deadlineStatus: 'always-open',
    educationLevel: ['12th-studying', '12th-passed', 'ug', 'pg', 'diploma', 'professional'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'A welfare fund providing financial help to sports persons who are injured or suffer losses during participation in National and State level competitions.',
    applicationUrl: 'https://sdat.tn.gov.in',
    helpline: '044-25672222',
    documents: ['Medical Report / Injury Certificate', 'Sports Participation Proof', 'FIR/Accident Report (if applicable)', 'Bank Details', 'TN Domicile Proof'],
    howToApply: ['Apply through SDAT with injury/loss documentation', 'Medical assessment if needed', 'Committee review', 'Financial assistance disbursed'],
    benefits: [{ label: 'Support', value: 'Medical + Financial' }, { label: 'For', value: 'Injured Athletes' }, { label: 'Availability', value: 'Year-round' }]
  },
  {
    id: 'tn-tnea-sports-quota',
    name: 'TNEA Sports Quota Seats (Engineering)',
    provider: 'Department of Technical Education (DoTE), Tamil Nadu',
    type: 'sports',
    amount: '2% Seat Reservation (~4,801 seats)',
    eligibility: ['Completed Class 12 with Physics, Chemistry, Mathematics', 'Min 45% marks (General) / 40% (SC/ST/MBC/DNC/SCA)', 'District/State/National level sports achievers', 'Valid TNEA application'],
    deadline: 'Jul 2026',
    deadlineStatus: 'open',
    educationLevel: ['12th-passed'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Government increased reservation for sports achievers to 2% of all engineering seats from 2025–26, covering ~4,801 seats across 433 engineering colleges in TN. Sports Quota counselling is conducted separately before general counselling.',
    applicationUrl: 'https://tneaonline.org',
    helpline: '044-22353101',
    documents: ['Sports Achievement Certificate (District/State/National)', 'Class 12 Mark Sheet', 'TNEA Application', 'Community Certificate', 'Form II/III from State Association'],
    howToApply: ['Register on TNEA portal', 'Upload sports certificates', 'Attend separate Sports Quota counselling', 'Seat allotment before general rounds'],
    benefits: [{ label: 'Seats', value: '~4,801 across TN' }, { label: 'Colleges', value: '433 Engineering' }, { label: 'Counselling', value: 'Separate & Early' }]
  },
  {
    id: 'tn-tnpesu-sports',
    name: 'TNPESU Sports Scholarship',
    provider: 'Tamil Nadu Physical Education & Sports University (TNPESU)',
    type: 'sports',
    amount: 'Tuition + Hostel Support',
    eligibility: ['Students enrolled in TNPESU programs', 'Sports achievers at State/National level', 'SC/ST and BC/MBC students also eligible for Post Matric component'],
    deadline: 'Aug 2026',
    deadlineStatus: 'open',
    educationLevel: ['12th-passed', 'ug', 'pg'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'TNPESU offers dedicated Sports Scholarships for students in the university. SC/ST and BC/MBC students can also access Post Matric Scholarship components alongside the sports scholarship.',
    applicationUrl: 'https://tnpesu.org',
    helpline: '044-24501608',
    documents: ['TNPESU Admission Proof', 'Sports Achievement Certificates', 'Community Certificate (for SC/ST/BC/MBC)', 'Income Certificate', 'Bank Details'],
    howToApply: ['Enroll in TNPESU program', 'Apply for sports scholarship at university', 'Submit sports certificates', 'Scholarship credited to fees'],
    benefits: [{ label: 'Tuition', value: 'Covered' }, { label: 'Hostel', value: 'Supported' }, { label: 'Post Matric', value: 'SC/ST/BC eligible' }]
  },
  {
    id: 'tn-srm-sports',
    name: 'SRM Sports Scholarship (100% Waiver)',
    provider: 'SRM Institute of Science and Technology (SRMIST), Chennai',
    type: 'sports',
    amount: '100% Tuition + Hostel Fee Waiver',
    eligibility: ['State/National/International level sports achievers', 'Must clear SRM sports selection trials', 'Available for Engineering, Management, Science, Hotel Mgmt, Law', 'Sports: Cricket, Basketball, Volleyball, Football, Hockey, Badminton, Tennis, Table Tennis, Chess'],
    deadline: 'Apr–Jul 2026',
    deadlineStatus: 'open',
    educationLevel: ['12th-passed', 'ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'SRMIST provides 100% scholarships for selected athletes through sports quota selection trials. 104 candidates selected annually through fair trials. Founder\'s Scholarship for National/International level athletes covers full tuition and hostel throughout the program.',
    applicationUrl: 'https://srmist.edu.in',
    helpline: '044-27417000',
    documents: ['State/National/International Participation Certificates', 'Class 12 Mark Sheet', 'Form II/III from Sports Association', 'Admission Documents', 'Bank Details'],
    howToApply: ['Apply on SRMIST portal with sports certificates', 'Attend sports selection trials at campus', 'Evaluated by internal expert panel', 'Scholarship awarded on selection'],
    benefits: [{ label: 'Fee Waiver', value: '100%' }, { label: 'Hostel', value: 'Full Waiver' }, { label: 'Seats', value: '104/year' }]
  },
  {
    id: 'tn-vit-sports',
    name: 'VIT Sports Scholarship',
    provider: 'Vellore Institute of Technology (VIT), Vellore',
    type: 'sports',
    amount: 'Tuition Fee Waiver (Varies)',
    eligibility: ['Students excelling in sports and games', 'Based on sports achievement level', 'Rural TN students with top district ranks in VITEEE get special consideration'],
    deadline: 'Apr–Jun 2026',
    deadlineStatus: 'open',
    educationLevel: ['12th-passed', 'ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'VIT awards scholarships each year to students who excel in sports and games, in the form of tuition waivers. Special consideration for students from rural Tamil Nadu who secure top district-level ranks in VITEEE.',
    applicationUrl: 'https://vit.ac.in',
    helpline: '0416-2243091',
    documents: ['Sports Achievement Certificates', 'VITEEE Score Card', 'Class 12 Mark Sheet', 'Rural Area Certificate (if applicable)', 'Bank Details'],
    howToApply: ['Apply through VIT admissions portal', 'Submit sports achievement proof', 'Performance assessment', 'Tuition waiver applied on admission'],
    benefits: [{ label: 'Tuition', value: 'Waiver' }, { label: 'Special', value: 'Rural TN Priority' }, { label: 'Renewal', value: 'Annual Review' }]
  },
  {
    id: 'tn-shivnadar-sports',
    name: 'Shiv Nadar University Sports Scholarship',
    provider: 'Shiv Nadar University, Chennai (Kalavakkam)',
    type: 'sports',
    amount: '100% Tuition Fee Waiver',
    eligibility: ['Represented State in National Championship organized by MYAS/IOA/SAI/SDAT/National Federation', 'For 1st year: sports participation in 11th & 12th considered', 'Renewal based on sports performance'],
    deadline: 'May 2026',
    deadlineStatus: 'open',
    educationLevel: ['12th-passed', 'ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Full tuition fee waiver for students who have represented their State in national championships. First-year students are evaluated on their 11th and 12th standard sports participation. Continued based on sports performance in the preceding year.',
    applicationUrl: 'https://snuchennai.edu.in',
    helpline: '9444139220',
    documents: ['State Representation Certificate', 'National Championship Participation Proof', 'Class 12 Mark Sheet', 'Admission Documents'],
    howToApply: ['Apply to Shiv Nadar University', 'Submit state-level representation proof', 'Physical Director review', 'Full tuition waiver for 1 year (renewable)'],
    benefits: [{ label: 'Tuition', value: '100% Waiver' }, { label: 'Duration', value: '1 Year (Renewable)' }, { label: 'Contact', value: 'Dr. P. Balaji' }]
  },
  {
    id: 'tn-kcg-sports',
    name: 'KCG College Sports Scholarship',
    provider: 'KCG College of Technology, Chennai',
    type: 'sports',
    amount: 'Sports Quota Admission + Scholarship',
    eligibility: ['Sports achievers at District/State/National level', 'Seeking Engineering admission', '200+ students admitted via sports quota since inception'],
    deadline: 'Apr–Jul 2026',
    deadlineStatus: 'open',
    educationLevel: ['12th-passed', 'ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'KCG College offers sports quota admissions and scholarships. Over 200 students have obtained admission through sports scholarships since inception. Students are trained by international players and experts across various sports fields.',
    applicationUrl: 'https://kcgcollege.ac.in',
    helpline: '044-22297894',
    documents: ['Sports Achievement Certificates', 'Class 12 Mark Sheet', 'Admission Application', 'Community Certificate'],
    howToApply: ['Apply to KCG College with sports certificates', 'Attend sports selection trials', 'Merit evaluation', 'Scholarship applied to fees'],
    benefits: [{ label: 'Admission', value: 'Sports Quota' }, { label: 'Training', value: 'International Coaches' }, { label: 'Alumni', value: '200+ Sports Scholars' }]
  },
  {
    id: 'tn-hits-sports',
    name: 'HITS Sports Scholarship',
    provider: 'Hindustan Institute of Technology & Science (HITS), Chennai',
    type: 'sports',
    amount: 'Scholarship Based on Performance',
    eligibility: ['Exceptional skill and sports performance', 'District/State/National level achievers', 'Seeking UG admission at HITS'],
    deadline: 'Apr–Jul 2026',
    deadlineStatus: 'open',
    educationLevel: ['12th-passed', 'ug'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'HITS grants sports scholarships to eligible candidates who demonstrate exceptional skill and performance, empowering them to pursue academic and athletic aspirations simultaneously.',
    applicationUrl: 'https://hindustanuniv.ac.in',
    helpline: '044-27474262',
    documents: ['Sports Achievement Certificates', 'Class 12 Mark Sheet', 'Admission Application', 'Identity Proof'],
    howToApply: ['Apply through HITS admissions', 'Submit sports achievement proof', 'Performance assessment by sports committee', 'Scholarship awarded on merit'],
    benefits: [{ label: 'Support', value: 'Academic + Athletic' }, { label: 'Basis', value: 'Performance-Based' }, { label: 'Level', value: 'District/State/National' }]
  },
  {
    id: 'tn-anna-univ-sports-quota',
    name: 'Anna University / TNEA Sports Quota',
    provider: 'Anna University & TNEA-Affiliated Colleges',
    type: 'sports',
    amount: 'Reserved Seat Admission',
    eligibility: ['Sports achievers at State/National level', '500 students admitted under sports quota annually', 'Must meet TNEA eligibility (PCM in Class 12)', 'Form II/III from recognized Sports Association'],
    deadline: 'Jul 2026',
    deadlineStatus: 'open',
    educationLevel: ['12th-passed'],
    category: ['general', 'sc', 'st', 'obc', 'bc-mbc', 'ews', 'minority'],
    gender: 'all',
    state: 'Tamil Nadu',
    description: 'Anna University and TNEA-affiliated institutions reserve seats for sports achievers, with approximately 500 students getting admission under sports quota across affiliated colleges annually.',
    applicationUrl: 'https://annauniv.edu',
    helpline: '044-22358561',
    documents: ['Sports Achievement Certificate', 'Class 12 Mark Sheet (PCM)', 'TNEA Application', 'Form II/III from State Sports Association', 'Community Certificate'],
    howToApply: ['Register on TNEA portal', 'Apply under sports quota category', 'Submit Form II/III sports certificates', 'Attend sports quota counselling'],
    benefits: [{ label: 'Seats', value: '~500 Annually' }, { label: 'Network', value: 'Anna Univ Affiliated' }, { label: 'Counselling', value: 'Separate Process' }]
  }
];

export const getScholarshipsByType = (type: string) => {
  return scholarships.filter(s => s.type === type);
};

// Removed getJKKNScholarships - no longer used

export const getGovernmentScholarships = () => {
  return scholarships.filter(s => s.type === 'government');
};

export const getCorporateScholarships = () => {
  return scholarships.filter(s => s.type === 'corporate');
};

export const getNGOScholarships = () => {
  return scholarships.filter(s => s.type === 'ngo');
};

export const getSportsScholarships = () => {
  return scholarships.filter(s => s.type === 'sports');
};
