export interface TNEASportsCollege { code: string; name: string; type: 'Govt' | 'Govt-Aided' | 'Private' | 'Central Govt' | 'Govt Deemed'; }
export interface DistrictColleges { district: string; districtTamil: string; colleges: TNEASportsCollege[]; }

export const tneaSportsQuotaColleges: DistrictColleges[] = [
  { district: 'Ariyalur', districtTamil: 'அரியலூர்', colleges: [
    { code: '3016', name: 'University College of Engineering, Ariyalur', type: 'Govt' },
    { code: '3466', name: 'Nelliandavar Institute of Technology', type: 'Private' },
    { code: '3462', name: 'Ariyalur Engineering College', type: 'Private' },
  ]},
  { district: 'Chennai', districtTamil: 'சென்னை', colleges: [
    { code: '0001', name: 'Anna University – CEG Campus', type: 'Govt' },
    { code: '0002', name: 'Anna University – ACT Campus', type: 'Govt' },
    { code: '1101', name: 'Aalim Muhammed Salegh College of Engineering', type: 'Private' },
    { code: '1106', name: 'Jaya Engineering College', type: 'Private' },
    { code: '1114', name: 'S A Engineering College', type: 'Private' },
    { code: '1118', name: 'Vel Tech Multi Tech Engineering College', type: 'Private' },
    { code: '1120', name: 'Velammal Engineering College', type: 'Private' },
    { code: '1122', name: 'Vel Tech High Tech Engineering College', type: 'Private' },
    { code: '1123', name: 'Gojan School of Business and Technology', type: 'Private' },
    { code: '1125', name: 'P M R Engineering College', type: 'Private' },
    { code: '1127', name: 'St. Peters College of Engineering and Technology', type: 'Private' },
    { code: '1131', name: 'Vel Tech', type: 'Private' },
    { code: '1133', name: 'Annai Veilankannis College of Engineering', type: 'Private' },
    { code: '1149', name: 'St. Josephs Institute of Technology', type: 'Private' },
    { code: '1202', name: 'D M I College of Engineering', type: 'Private' },
    { code: '1210', name: 'Panimalar Engineering College', type: 'Private' },
    { code: '1213', name: 'S K R Engineering College', type: 'Private' },
    { code: '1217', name: 'Sree Sastha Institute of Engineering and Technology', type: 'Private' },
    { code: '1218', name: 'Sri Muthukumaran Institute of Technology', type: 'Private' },
    { code: '1221', name: 'Jaya College of Engineering and Technology', type: 'Private' },
    { code: '1225', name: 'Loyola Institute of Technology', type: 'Private' },
    { code: '1228', name: 'Alpha College of Engineering', type: 'Private' },
    { code: '1231', name: 'Panimalar Institute of Technology', type: 'Private' },
    { code: '1243', name: 'Madha Institute of Engineering and Technology', type: 'Private' },
    { code: '1304', name: 'Easwari Engineering College', type: 'Private' },
    { code: '1306', name: 'Jeppiar Engineering College', type: 'Private' },
    { code: '1309', name: 'Meenakshi Sundararajan Engineering College', type: 'Private' },
    { code: '1310', name: 'MNM Jain Engineering College', type: 'Private' },
    { code: '1311', name: 'K C G College of Technology', type: 'Private' },
    { code: '1313', name: 'SMK Fomra Institute of Technology', type: 'Private' },
    { code: '1317', name: 'St. Josephs College of Engineering', type: 'Private' },
    { code: '1319', name: 'Thangavelu Engineering College', type: 'Private' },
    { code: '1321', name: 'CIPET, Guindy', type: 'Central Govt' },
    { code: '1322', name: 'Dhanalakshmi Srinivasan College of Engg. & Tech.', type: 'Private' },
    { code: '1324', name: 'Sri Sai Ram Institute of Technology', type: 'Private' },
    { code: '1399', name: 'Chennai Institute of Technology', type: 'Private' },
    { code: '1405', name: 'Dhanalakshmi College of Engineering', type: 'Private' },
    { code: '1407', name: 'G K M College of Engineering and Technology', type: 'Private' },
    { code: '1411', name: 'Madha Engineering College', type: 'Private' },
    { code: '1414', name: 'Prince Shri Venkateshwara Padmavathy Engg. College', type: 'Private' },
    { code: '1416', name: 'Jaya Sakthi Engineering College', type: 'Private' },
    { code: '1419', name: 'Sri Sairam Engineering College', type: 'Private' },
    { code: '1420', name: 'Tagore Engineering College', type: 'Private' },
    { code: '1422', name: 'SRM Valliammai Engineering College', type: 'Private' },
    { code: '1424', name: 'Dhaanish Ahmed College of Engineering', type: 'Private' },
    { code: '1426', name: 'Sri Ramanujar Engineering College', type: 'Private' },
    { code: '1427', name: 'Sri Krishna Engineering College', type: 'Private' },
    { code: '1431', name: 'New Prince Shri Bhavani College of Engg. & Tech.', type: 'Private' },
    { code: '1437', name: 'Rrase College of Engineering', type: 'Private' },
    { code: '1442', name: 'Prince Dr. K Vasudevan College of Engg. & Tech.', type: 'Private' },
    { code: '1447', name: 'Jawahar Engineering College', type: 'Private' },
    { code: '1450', name: 'Loyola-ICAM College of Engineering and Technology', type: 'Private' },
    { code: '1452', name: 'PERI Institute of Technology', type: 'Private' },
    { code: '1509', name: 'Meenakshi College of Engineering', type: 'Private' },
  ]},
  { district: 'Coimbatore', districtTamil: 'கோயம்புத்தூர்', colleges: [
    { code: '2005', name: 'Government College of Technology', type: 'Govt' },
    { code: '2006', name: 'PSG College of Technology', type: 'Govt-Aided' },
    { code: '2007', name: 'Coimbatore Institute of Technology (CIT)', type: 'Govt-Aided' },
    { code: '2025', name: 'Anna University Regional Campus – Coimbatore', type: 'Govt' },
    { code: '2329', name: 'Rathinam Technical Campus', type: 'Private' },
    { code: '2338', name: 'Asian College of Engineering and Technology', type: 'Private' },
    { code: '2342', name: 'Sri Ranganathar Institute of Engg. and Technology', type: 'Private' },
    { code: '2349', name: 'Dhaanish Ahmed Institute of Technology', type: 'Private' },
    { code: '2354', name: 'Pollachi Institute of Engg. and Technology', type: 'Private' },
    { code: '2360', name: 'Suguna College of Engineering', type: 'Private' },
    { code: '2367', name: 'Arjun College of Technology', type: 'Private' },
    { code: '2377', name: 'PSG Institute of Technology and Applied Research', type: 'Private' },
    { code: '2650', name: 'Christ the King Engineering College', type: 'Private' },
    { code: '2704', name: 'Coimbatore Institute of Engg. and Technology', type: 'Private' },
    { code: '2706', name: 'Dr. Mahalingam College of Engg. and Technology', type: 'Private' },
    { code: '2708', name: 'Hindusthan College of Engg. and Technology', type: 'Private' },
    { code: '2710', name: 'Karpagam College of Engineering', type: 'Private' },
    { code: '2712', name: 'Kumaraguru College of Technology', type: 'Private' },
    { code: '2716', name: 'Park College of Engg. and Technology', type: 'Private' },
    { code: '2718', name: 'Sri Krishna College of Engg. and Technology', type: 'Private' },
    { code: '2719', name: 'Sri Ramakrishna Engineering College', type: 'Private' },
    { code: '2721', name: 'Tamilnadu College of Engineering', type: 'Private' },
    { code: '2722', name: 'Sri Krishna College of Technology', type: 'Private' },
    { code: '2725', name: 'Sri Ramakrishna Institute of Technology', type: 'Private' },
    { code: '2726', name: 'SNS College of Technology', type: 'Private' },
    { code: '2727', name: 'Sri Shakthi Institute of Engg. and Technology', type: 'Private' },
    { code: '2729', name: 'Nehru Institute of Engg. and Technology', type: 'Private' },
    { code: '2731', name: 'R V S College of Engg. and Technology', type: 'Private' },
    { code: '2732', name: 'INFO Institute of Engineering', type: 'Private' },
    { code: '2734', name: 'SNS College of Engineering', type: 'Private' },
    { code: '2735', name: 'Karpagam Institute of Technology', type: 'Private' },
    { code: '2736', name: 'Dr. N G P Institute of Technology', type: 'Private' },
    { code: '2739', name: 'Sri Eshwar College of Engineering', type: 'Private' },
    { code: '2740', name: 'Hindustan Institute of Technology', type: 'Private' },
    { code: '2741', name: 'P A College of Engg. and Technology', type: 'Private' },
    { code: '2743', name: 'Dhanalakshmi Srinivasan College of Engineering', type: 'Private' },
    { code: '2744', name: 'Adithya Institute of Technology', type: 'Private' },
    { code: '2745', name: 'Kathir College of Engineering', type: 'Private' },
    { code: '2749', name: 'EASA College of Engg. and Technology', type: 'Private' },
    { code: '2750', name: 'KIT – Kalaignar Karunanidhi Institute of Technology', type: 'Private' },
    { code: '2751', name: 'KGISL Institute of Technology', type: 'Private' },
    { code: '2753', name: 'P P G Institute of Technology', type: 'Private' },
    { code: '2755', name: 'Nehru Institute of Technology', type: 'Private' },
    { code: '2761', name: 'United Institute of Technology', type: 'Private' },
    { code: '2762', name: 'Jansons Institute of Technology', type: 'Private' },
    { code: '2763', name: 'Akshaya College of Engg. and Technology', type: 'Private' },
    { code: '2764', name: 'K P R Institute of Engg. and Technology', type: 'Private' },
    { code: '2765', name: 'Sriguru Institute of Technology', type: 'Private' },
    { code: '2768', name: 'Park College of Technology', type: 'Private' },
    { code: '2769', name: 'J C T College of Engg. and Technology', type: 'Private' },
    { code: '2772', name: 'C M S College of Engg. and Technology', type: 'Private' },
    { code: '2776', name: 'R V S Technical Campus – Coimbatore', type: 'Private' },
  ]},
  { district: 'Cuddalore', districtTamil: 'கடலூர்', colleges: [
    { code: '0005', name: 'Annamalai University Faculty of Engineering', type: 'Govt Deemed' },
    { code: '3019', name: 'University College of Engineering, Panruti', type: 'Govt' },
    { code: '3410', name: 'Krishnaswamy College of Engg. and Technology', type: 'Private' },
    { code: '3425', name: 'C K College of Engg. and Technology', type: 'Private' },
    { code: '3822', name: 'Dr. Navalar Nedunchezhian College of Engineering', type: 'Private' },
    { code: '3843', name: 'M R K Institute of Technology', type: 'Private' },
    { code: '3860', name: 'St. Annes College of Engg. and Technology', type: 'Private' },
  ]},
  { district: 'Dharmapuri', districtTamil: 'தர்மபுரி', colleges: [
    { code: '2369', name: 'Government College of Engineering, Dharmapuri', type: 'Govt' },
    { code: '2606', name: 'Jayam College of Engg. and Technology', type: 'Private' },
    { code: '2640', name: 'Jayalakshmi Institute of Technology', type: 'Private' },
    { code: '2641', name: 'Varuvan Vadivelan Institute of Technology', type: 'Private' },
    { code: '2683', name: 'Shreenivasa Engineering College', type: 'Private' },
  ]},
  { district: 'Dindigul', districtTamil: 'திண்டுக்கல்', colleges: [
    { code: '5022', name: 'University College of Engineering, Dindigul', type: 'Govt' },
    { code: '5530', name: 'SSM Institute of Engg. and Technology', type: 'Private' },
    { code: '5703', name: 'Christian College of Engg. and Technology', type: 'Private' },
    { code: '5720', name: 'Sri Subramanya College of Engg. and Technology', type: 'Private' },
    { code: '5832', name: 'N P R College of Engg. and Technology', type: 'Private' },
    { code: '5851', name: 'Veerammal Engineering College', type: 'Private' },
    { code: '5862', name: 'R V S Educational Trust Group of Institutions', type: 'Private' },
    { code: '5910', name: 'P S N A College of Engg. and Technology', type: 'Private' },
    { code: '5913', name: 'Ratnavel Subramaniam College of Engg. & Tech.', type: 'Private' },
    { code: '5930', name: 'SBM College of Engg. and Technology', type: 'Private' },
  ]},
  { district: 'Erode', districtTamil: 'ஈரோடு', colleges: [
    { code: '2332', name: 'Aishwarya College of Engg. and Technology', type: 'Private' },
    { code: '2652', name: 'Al-Ameen Engineering College', type: 'Private' },
    { code: '2702', name: 'Bannari Amman Institute of Technology', type: 'Private' },
    { code: '2707', name: 'Erode Sengunthar Engineering College', type: 'Private' },
    { code: '2709', name: 'Institute of Road and Transport Technology', type: 'Govt' },
    { code: '2711', name: 'Kongu Engineering College', type: 'Private' },
    { code: '2713', name: 'M P Nachimuthu M Jagannathan Engg. College', type: 'Private' },
    { code: '2715', name: 'Nandha Engineering College', type: 'Private' },
    { code: '2723', name: 'Velalar College of Engg. and Technology', type: 'Private' },
    { code: '2747', name: 'Shree Venkateshwara Hi-Tech Engg. College', type: 'Private' },
    { code: '2748', name: 'Surya Engineering College', type: 'Private' },
    { code: '2752', name: 'Nandha College of Technology', type: 'Private' },
    { code: '2758', name: 'J K K Muniraja College of Technology', type: 'Private' },
  ]},
  { district: 'Kanchipuram', districtTamil: 'காஞ்சிபுரம்', colleges: [
    { code: '0004', name: 'Anna University – MIT Campus', type: 'Govt' },
    { code: '1026', name: 'University College of Engineering, Kanchipuram', type: 'Govt' },
    { code: '1140', name: 'Jeppiaar Institute of Technology', type: 'Private' },
    { code: '1201', name: 'Arignar Anna Institute of Science and Technology', type: 'Private' },
    { code: '1206', name: 'Jeppiaar Maamallan Engineering College', type: 'Private' },
    { code: '1207', name: 'Kings Engineering College', type: 'Private' },
    { code: '1209', name: 'Pallavan College of Engineering', type: 'Private' },
    { code: '1211', name: 'Rajalakshmi Engineering College', type: 'Private' },
    { code: '1212', name: 'Rajiv Gandhi College of Engineering', type: 'Private' },
    { code: '1216', name: 'Saveetha Engineering College', type: 'Private' },
    { code: '1219', name: 'Sri Venkateswara College of Engineering', type: 'Private' },
    { code: '1222', name: 'P B College of Engineering', type: 'Private' },
    { code: '1226', name: 'P T Lee Chengalvaraya Naicker College of Engg. & Tech.', type: 'Private' },
    { code: '1230', name: 'Apollo Engineering College', type: 'Private' },
    { code: '1232', name: 'A R M College of Engg. and Technology', type: 'Private' },
    { code: '1233', name: 'Adhi College of Engg. and Technology', type: 'Private' },
    { code: '1234', name: 'Indira Gandhi College of Engg. & Tech. for Women', type: 'Private' },
    { code: '1301', name: 'Mohamed Sathak A J College of Engineering', type: 'Private' },
    { code: '1303', name: 'Anand Institute of Higher Technology', type: 'Private' },
    { code: '1315', name: 'Sri Sivasubramaniya Nadar College of Engineering (SSN)', type: 'Private' },
    { code: '1316', name: 'Agni College of Technology', type: 'Private' },
    { code: '1320', name: 'Jeppiaar SRR Engineering College', type: 'Private' },
    { code: '1325', name: 'St. Joseph College of Engineering', type: 'Private' },
    { code: '1333', name: 'Vi Institute of Technology', type: 'Private' },
    { code: '1334', name: 'ARS College of Engineering', type: 'Private' },
    { code: '1401', name: 'Adhiparasakthi Engineering College, Melmaruvathur', type: 'Private' },
    { code: '1409', name: 'Karpagavinayaga College of Engg. and Technology', type: 'Private' },
    { code: '1413', name: 'Sri Venkateswaraa College of Technology', type: 'Private' },
    { code: '1417', name: 'Shri Andal Alagar College of Engineering', type: 'Private' },
    { code: '1432', name: 'Rajalakshmi Institute of Technology', type: 'Private' },
    { code: '1435', name: 'Balaji Institute of Engg. and Technology', type: 'Private' },
    { code: '1444', name: 'Chendu College of Engg. & Technology', type: 'Private' },
    { code: '1517', name: 'Thirumalai Engineering College', type: 'Private' },
  ]},
  { district: 'Kanniyakumari', districtTamil: 'கன்னியாகுமரி', colleges: [
    { code: '4023', name: 'University College of Engineering, Nagercoil', type: 'Govt' },
    { code: '4670', name: 'Rohini College of Engg. & Technology', type: 'Private' },
    { code: '4672', name: 'Stella Marys College of Engineering', type: 'Private' },
    { code: '4677', name: 'Lourdes Mount College of Engg. and Technology', type: 'Private' },
    { code: '4686', name: 'Good Shepherd College of Engg. and Technology', type: 'Private' },
    { code: '4927', name: 'Maria College of Engg. and Technology', type: 'Private' },
    { code: '4928', name: 'MAR Ephraem College of Engg. & Technology', type: 'Private' },
    { code: '4929', name: 'M E T Engineering College', type: 'Private' },
    { code: '4938', name: 'Sivaji College of Engg. and Technology', type: 'Private' },
    { code: '4943', name: 'Satyam College of Engg. & Technology', type: 'Private' },
    { code: '4944', name: 'Arunachala College of Engineering for Women', type: 'Private' },
    { code: '4945', name: 'Vins Christian Womens College of Engineering', type: 'Private' },
    { code: '4946', name: 'D M I Engineering College', type: 'Private' },
    { code: '4948', name: 'Rajas International Institute of Technology for Women', type: 'Private' },
    { code: '4952', name: 'C S I Institute of Technology', type: 'Private' },
    { code: '4971', name: 'St. Xavier Catholic College of Engineering', type: 'Private' },
    { code: '4972', name: 'Amrita College of Engg. and Technology', type: 'Private' },
    { code: '4977', name: 'Narayanaguru College of Engineering', type: 'Private' },
    { code: '4978', name: 'Udaya School of Engineering', type: 'Private' },
    { code: '4981', name: 'Ponjesly College of Engineering', type: 'Private' },
    { code: '4982', name: 'Vins Christian College of Engineering', type: 'Private' },
    { code: '4983', name: 'Lord Jegannath College of Engg. and Technology', type: 'Private' },
    { code: '4984', name: 'Marthandam College of Engg. & Technology', type: 'Private' },
    { code: '4992', name: 'Bethlahem Institute of Engineering', type: 'Private' },
    { code: '4993', name: 'Loyola Institute of Technology and Science', type: 'Private' },
    { code: '4999', name: 'Annai Vailankanni College of Engineering', type: 'Private' },
  ]},
  { district: 'Karur', districtTamil: 'கரூர்', colleges: [
    { code: '2355', name: 'Cheran College of Engineering', type: 'Private' },
    { code: '2356', name: 'Arulmurugan College of Engineering', type: 'Private' },
    { code: '2608', name: 'M Kumarasamy College of Engineering', type: 'Private' },
    { code: '2622', name: 'V S B Engineering College', type: 'Private' },
    { code: '2649', name: 'Karur College of Engineering', type: 'Private' },
  ]},
  { district: 'Krishnagiri', districtTamil: 'கிருஷ்ணகிரி', colleges: [
    { code: '2601', name: 'Adhiyamaan College of Engineering', type: 'Private' },
    { code: '2603', name: 'Government College of Engineering, Bargur', type: 'Govt' },
    { code: '2621', name: 'Er. Perumal Manimekalai College of Engineering', type: 'Private' },
    { code: '2642', name: 'P S V College of Engg. and Technology', type: 'Private' },
  ]},
  { district: 'Madurai', districtTamil: 'மதுரை', colleges: [
    { code: '5008', name: 'Thiagarajar College of Engineering (TCE)', type: 'Govt-Aided' },
    { code: '5010', name: 'Anna University Regional Campus – Madurai', type: 'Govt' },
    { code: '5532', name: 'Vaigai College of Engineering', type: 'Private' },
    { code: '5536', name: 'Mangayarkarasi College of Engineering', type: 'Private' },
    { code: '5911', name: 'P T R College of Engg. and Technology', type: 'Private' },
    { code: '5914', name: 'Solaimalai College of Engineering', type: 'Private' },
    { code: '5915', name: 'SACS-MAVMM Engineering College', type: 'Private' },
    { code: '5942', name: 'Ultra College of Engg. & Technology', type: 'Private' },
    { code: '5986', name: 'Velammal College of Engg. and Technology', type: 'Private' },
    { code: '5990', name: 'Latha Mathavan Engineering College', type: 'Private' },
  ]},
  { district: 'Nagapattinam', districtTamil: 'நாகப்பட்டினம்', colleges: [
    { code: '3018', name: 'University College of Engineering, Thirukkuvalai', type: 'Govt' },
    { code: '3461', name: 'Arifa Institute of Technology', type: 'Private' },
    { code: '3760', name: 'Sir Issac Newton College of Engg. and Technology', type: 'Private' },
    { code: '3801', name: 'A V C College of Engineering', type: 'Private' },
    { code: '3806', name: 'E G S Pillay Engineering College', type: 'Private' },
    { code: '3859', name: 'Sembodai Rukmani Varatharajan Engg. College', type: 'Private' },
  ]},
  { district: 'Namakkal', districtTamil: 'நாமக்கல்', colleges: [
    { code: '2314', name: 'Muthayammal College of Engineering', type: 'Private' },
    { code: '2328', name: 'K S R Institute for Engg. and Technology', type: 'Private' },
    { code: '2602', name: 'Annai Mathammal Sheela Engineering College', type: 'Private' },
    { code: '2607', name: 'K S Rangasamy College of Technology', type: 'Private' },
    { code: '2609', name: 'Mahendra Engineering College', type: 'Private' },
    { code: '2610', name: 'Muthayammal Engineering College', type: 'Private' },
    { code: '2611', name: 'Paavai Engineering College', type: 'Private' },
    { code: '2612', name: 'P G P College of Engg. and Technology', type: 'Private' },
    { code: '2613', name: 'K S R College of Engineering', type: 'Private' },
    { code: '2614', name: 'S S M College of Engineering', type: 'Private' },
    { code: '2617', name: 'Sengunthar Engineering College', type: 'Private' },
    { code: '2620', name: 'Vivekanandha College of Engg. for Women', type: 'Private' },
    { code: '2624', name: 'Gnanamani College of Technology', type: 'Private' },
    { code: '2627', name: 'Selvam College of Technology', type: 'Private' },
    { code: '2628', name: 'Paavai College of Engineering', type: 'Private' },
    { code: '2629', name: 'Sengunthar College of Engineering', type: 'Private' },
    { code: '2632', name: 'Mahendra Institute of Technology', type: 'Private' },
    { code: '2633', name: 'Vidyaa Vikas College of Engg. and Technology', type: 'Private' },
    { code: '2634', name: 'Excel Engineering College', type: 'Private' },
    { code: '2638', name: 'Mahendra Engineering College for Women', type: 'Private' },
    { code: '2647', name: 'J K K Nataraja College of Engg. and Technology', type: 'Private' },
    { code: '2657', name: 'Paavai College of Technology', type: 'Private' },
    { code: '2660', name: 'Gnanamani College of Engineering', type: 'Private' },
    { code: '2661', name: 'Vivekanandha College of Technology for Women', type: 'Private' },
    { code: '2664', name: 'Excel College of Engg. and Technology', type: 'Private' },
    { code: '2665', name: 'Mahendra Institute of Engg. and Technology', type: 'Private' },
    { code: '2767', name: 'SRG Engineering College', type: 'Private' },
  ]},
  { district: 'Perambalur', districtTamil: 'பெரம்பலூர்', colleges: [
    { code: '3454', name: 'Sri Ramakrishna College of Engineering', type: 'Private' },
    { code: '3457', name: 'Dhanalakshmi Srinivasan College of Engineering', type: 'Private' },
    { code: '3805', name: 'Dhanalakshmi Srinivasan Engineering College', type: 'Private' },
    { code: '3817', name: 'Roever Engineering College', type: 'Private' },
    { code: '3823', name: 'Srinivasan Engineering College', type: 'Private' },
    { code: '3847', name: 'Roever College of Engg. and Technology', type: 'Private' },
  ]},
  { district: 'Pudukkottai', districtTamil: 'புதுக்கோட்டை', colleges: [
    { code: '3812', name: 'Mookambigai College of Engineering', type: 'Private' },
    { code: '3846', name: 'Mother Terasa College of Engg. and Technology', type: 'Private' },
    { code: '3852', name: 'Sri Bharathi Engineering College for Women', type: 'Private' },
    { code: '3854', name: 'Mahath Amma Institute of Engg. and Technology', type: 'Private' },
    { code: '3905', name: 'Kings College of Engineering', type: 'Private' },
    { code: '3908', name: 'Mount Zion College of Engg. and Technology', type: 'Private' },
    { code: '3918', name: 'Shanmuganathan Engineering College', type: 'Private' },
    { code: '3920', name: 'Sudharsan Engineering College', type: 'Private' },
    { code: '3923', name: 'M N S K College of Engineering', type: 'Private' },
    { code: '3925', name: 'M A R College of Engg. and Technology', type: 'Private' },
  ]},
  { district: 'Ramanathapuram', districtTamil: 'ராமநாதபுரம்', colleges: [
    { code: '5017', name: 'University College of Engineering, Ramanathapuram', type: 'Govt' },
    { code: '5907', name: 'Mohamed Sathak Engineering College', type: 'Private' },
    { code: '5921', name: 'Syed Ammal Engineering College', type: 'Private' },
    { code: '5924', name: 'Ganapathy Chettiar College of Engg. and Technology', type: 'Private' },
  ]},
];

export const getTotalColleges = () => tneaSportsQuotaColleges.reduce((s, d) => s + d.colleges.length, 0);
export const getDistrictCount = () => tneaSportsQuotaColleges.length;
export const getGovtCount = () => tneaSportsQuotaColleges.reduce((s, d) => s + d.colleges.filter(c => c.type !== 'Private').length, 0);
