export interface TNEASportsCollege { code: string; name: string; type: 'Govt' | 'Govt-Aided' | 'Private' | 'Central Govt' | 'Govt Deemed'; }
export interface DistrictColleges { district: string; districtTamil: string; colleges: TNEASportsCollege[]; }

export const tneaSportsQuotaColleges: DistrictColleges[] = [
  { district: 'Ariyalur', districtTamil: 'அரியலூர்', colleges: [
    { code: '3016', name: 'University College of Engineering, Ariyalur', type: 'Govt' },
    { code: '3466', name: 'Nelliandavar Institute of Technology', type: 'Private' },
    { code: '3462', name: 'Ariyalur Engineering College', type: 'Private' },
  ]},
  { district: 'Chennai', districtTamil: 'சென்னை', colleges: [
    { code: '0001', name: 'Anna University – CEG Campus', type: 'Govt' },
    { code: '0002', name: 'Anna University – ACT Campus', type: 'Govt' },
    { code: '1101', name: 'Aalim Muhammed Salegh College of Engineering', type: 'Private' },
    { code: '1106', name: 'Jaya Engineering College', type: 'Private' },
    { code: '1114', name: 'S A Engineering College', type: 'Private' },
    { code: '1118', name: 'Vel Tech Multi Tech Engineering College', type: 'Private' },
    { code: '1120', name: 'Velammal Engineering College', type: 'Private' },
    { code: '1122', name: 'Vel Tech High Tech Engineering College', type: 'Private' },
    { code: '1123', name: 'Gojan School of Business and Technology', type: 'Private' },
    { code: '1125', name: 'P M R Engineering College', type: 'Private' },
    { code: '1127', name: 'St. Peters College of Engineering and Technology', type: 'Private' },
    { code: '1131', name: 'Vel Tech', type: 'Private' },
    { code: '1133', name: 'Annai Veilankannis College of Engineering', type: 'Private' },
    { code: '1149', name: 'St. Josephs Institute of Technology', type: 'Private' },
    { code: '1202', name: 'D M I College of Engineering', type: 'Private' },
    { code: '1210', name: 'Panimalar Engineering College', type: 'Private' },
    { code: '1213', name: 'S K R Engineering College', type: 'Private' },
    { code: '1217', name: 'Sree Sastha Institute of Engineering and Technology', type: 'Private' },
    { code: '1218', name: 'Sri Muthukumaran Institute of Technology', type: 'Private' },
    { code: '1221', name: 'Jaya College of Engineering and Technology', type: 'Private' },
    { code: '1225', name: 'Loyola Institute of Technology', type: 'Private' },
    { code: '1228', name: 'Alpha College of Engineering', type: 'Private' },
    { code: '1231', name: 'Panimalar Institute of Technology', type: 'Private' },
    { code: '1243', name: 'Madha Institute of Engineering and Technology', type: 'Private' },
    { code: '1304', name: 'Easwari Engineering College', type: 'Private' },
    { code: '1306', name: 'Jeppiar Engineering College', type: 'Private' },
    { code: '1309', name: 'Meenakshi Sundararajan Engineering College', type: 'Private' },
    { code: '1310', name: 'MNM Jain Engineering College', type: 'Private' },
    { code: '1311', name: 'K C G College of Technology', type: 'Private' },
    { code: '1313', name: 'SMK Fomra Institute of Technology', type: 'Private' },
    { code: '1317', name: 'St. Josephs College of Engineering', type: 'Private' },
    { code: '1319', name: 'Thangavelu Engineering College', type: 'Private' },
    { code: '1321', name: 'CIPET, Guindy', type: 'Central Govt' },
    { code: '1322', name: 'Dhanalakshmi Srinivasan College of Engg. & Tech.', type: 'Private' },
    { code: '1324', name: 'Sri Sai Ram Institute of Technology', type: 'Private' },
    { code: '1399', name: 'Chennai Institute of Technology', type: 'Private' },
    { code: '1405', name: 'Dhanalakshmi College of Engineering', type: 'Private' },
    { code: '1407', name: 'G K M College of Engineering and Technology', type: 'Private' },
    { code: '1411', name: 'Madha Engineering College', type: 'Private' },
    { code: '1414', name: 'Prince Shri Venkateshwara Padmavathy Engg. College', type: 'Private' },
    { code: '1416', name: 'Jaya Sakthi Engineering College', type: 'Private' },
    { code: '1419', name: 'Sri Sairam Engineering College', type: 'Private' },
    { code: '1420', name: 'Tagore Engineering College', type: 'Private' },
    { code: '1422', name: 'SRM Valliammai Engineering College', type: 'Private' },
    { code: '1424', name: 'Dhaanish Ahmed College of Engineering', type: 'Private' },
    { code: '1426', name: 'Sri Ramanujar Engineering College', type: 'Private' },
    { code: '1427', name: 'Sri Krishna Engineering College', type: 'Private' },
    { code: '1431', name: 'New Prince Shri Bhavani College of Engg. & Tech.', type: 'Private' },
    { code: '1437', name: 'Rrase College of Engineering', type: 'Private' },
    { code: '1442', name: 'Prince Dr. K Vasudevan College of Engg. & Tech.', type: 'Private' },
    { code: '1447', name: 'Jawahar Engineering College', type: 'Private' },
    { code: '1450', name: 'Loyola-ICAM College of Engineering and Technology', type: 'Private' },
    { code: '1452', name: 'PERI Institute of Technology', type: 'Private' },
    { code: '1509', name: 'Meenakshi College of Engineering', type: 'Private' },
  ]},
  { district: 'Coimbatore', districtTamil: 'கோயம்புத்தூர்', colleges: [
    { code: '2005', name: 'Government College of Technology', type: 'Govt' },
    { code: '2006', name: 'PSG College of Technology', type: 'Govt-Aided' },
    { code: '2007', name: 'Coimbatore Institute of Technology (CIT)', type: 'Govt-Aided' },
    { code: '2025', name: 'Anna University Regional Campus – Coimbatore', type: 'Govt' },
    { code: '2329', name: 'Rathinam Technical Campus', type: 'Private' },
    { code: '2338', name: 'Asian College of Engineering and Technology', type: 'Private' },
    { code: '2342', name: 'Sri Ranganathar Institute of Engg. and Technology', type: 'Private' },
    { code: '2349', name: 'Dhaanish Ahmed Institute of Technology', type: 'Private' },
    { code: '2354', name: 'Pollachi Institute of Engg. and Technology', type: 'Private' },
    { code: '2360', name: 'Suguna College of Engineering', type: 'Private' },
    { code: '2367', name: 'Arjun College of Technology', type: 'Private' },
    { code: '2377', name: 'PSG Institute of Technology and Applied Research', type: 'Private' },
    { code: '2650', name: 'Christ the King Engineering College', type: 'Private' },
    { code: '2704', name: 'Coimbatore Institute of Engg. and Technology', type: 'Private' },
    { code: '2706', name: 'Dr. Mahalingam College of Engg. and Technology', type: 'Private' },
    { code: '2708', name: 'Hindusthan College of Engg. and Technology', type: 'Private' },
    { code: '2710', name: 'Karpagam College of Engineering', type: 'Private' },
    { code: '2712', name: 'Kumaraguru College of Technology', type: 'Private' },
    { code: '2716', name: 'Park College of Engg. and Technology', type: 'Private' },
    { code: '2718', name: 'Sri Krishna College of Engg. and Technology', type: 'Private' },
    { code: '2719', name: 'Sri Ramakrishna Engineering College', type: 'Private' },
    { code: '2721', name: 'Tamilnadu College of Engineering', type: 'Private' },
    { code: '2722', name: 'Sri Krishna College of Technology', type: 'Private' },
    { code: '2725', name: 'Sri Ramakrishna Institute of Technology', type: 'Private' },
    { code: '2726', name: 'SNS College of Technology', type: 'Private' },
    { code: '2727', name: 'Sri Shakthi Institute of Engg. and Technology', type: 'Private' },
    { code: '2729', name: 'Nehru Institute of Engg. and Technology', type: 'Private' },
    { code: '2731', name: 'R V S College of Engg. and Technology', type: 'Private' },
    { code: '2732', name: 'INFO Institute of Engineering', type: 'Private' },
    { code: '2734', name: 'SNS College of Engineering', type: 'Private' },
    { code: '2735', name: 'Karpagam Institute of Technology', type: 'Private' },
    { code: '2736', name: 'Dr. N G P Institute of Technology', type: 'Private' },
    { code: '2739', name: 'Sri Eshwar College of Engineering', type: 'Private' },
    { code: '2740', name: 'Hindustan Institute of Technology', type: 'Private' },
    { code: '2741', name: 'P A College of Engg. and Technology', type: 'Private' },
    { code: '2743', name: 'Dhanalakshmi Srinivasan College of Engineering', type: 'Private' },
    { code: '2744', name: 'Adithya Institute of Technology', type: 'Private' },
    { code: '2745', name: 'Kathir College of Engineering', type: 'Private' },
    { code: '2749', name: 'EASA College of Engg. and Technology', type: 'Private' },
    { code: '2750', name: 'KIT – Kalaignar Karunanidhi Institute of Technology', type: 'Private' },
    { code: '2751', name: 'KGISL Institute of Technology', type: 'Private' },
    { code: '2753', name: 'P P G Institute of Technology', type: 'Private' },
    { code: '2755', name: 'Nehru Institute of Technology', type: 'Private' },
    { code: '2761', name: 'United Institute of Technology', type: 'Private' },
    { code: '2762', name: 'Jansons Institute of Technology', type: 'Private' },
    { code: '2763', name: 'Akshaya College of Engg. and Technology', type: 'Private' },
    { code: '2764', name: 'K P R Institute of Engg. and Technology', type: 'Private' },
    { code: '2765', name: 'Sriguru Institute of Technology', type: 'Private' },
    { code: '2768', name: 'Park College of Technology', type: 'Private' },
    { code: '2769', name: 'J C T College of Engg. and Technology', type: 'Private' },
    { code: '2772', name: 'C M S College of Engg. and Technology', type: 'Private' },
    { code: '2776', name: 'R V S Technical Campus – Coimbatore', type: 'Private' },
  ]},
  { district: 'Cuddalore', districtTamil: 'கடலூர்', colleges: [
    { code: '0005', name: 'Annamalai University Faculty of Engineering', type: 'Govt Deemed' },
    { code: '3019', name: 'University College of Engineering, Panruti', type: 'Govt' },
    { code: '3410', name: 'Krishnaswamy College of Engg. and Technology', type: 'Private' },
    { code: '3425', name: 'C K College of Engg. and Technology', type: 'Private' },
    { code: '3822', name: 'Dr. Navalar Nedunchezhian College of Engineering', type: 'Private' },
    { code: '3843', name: 'M R K Institute of Technology', type: 'Private' },
    { code: '3860', name: 'St. Annes College of Engg. and Technology', type: 'Private' },
  ]},
  { district: 'Dharmapuri', districtTamil: 'தர்மபுரி', colleges: [
    { code: '2369', name: 'Government College of Engineering, Dharmapuri', type: 'Govt' },
    { code: '2606', name: 'Jayam College of Engg. and Technology', type: 'Private' },
    { code: '2640', name: 'Jayalakshmi Institute of Technology', type: 'Private' },
    { code: '2641', name: 'Varuvan Vadivelan Institute of Technology', type: 'Private' },
    { code: '2683', name: 'Shreenivasa Engineering College', type: 'Private' },
  ]},
  { district: 'Dindigul', districtTamil: 'திண்டுக்கல்', colleges: [
    { code: '5022', name: 'University College of Engineering, Dindigul', type: 'Govt' },
    { code: '5530', name: 'SSM Institute of Engg. and Technology', type: 'Private' },
    { code: '5703', name: 'Christian College of Engg. and Technology', type: 'Private' },
    { code: '5720', name: 'Sri Subramanya College of Engg. and Technology', type: 'Private' },
    { code: '5832', name: 'N P R College of Engg. and Technology', type: 'Private' },
    { code: '5851', name: 'Veerammal Engineering College', type: 'Private' },
    { code: '5862', name: 'R V S Educational Trust Group of Institutions', type: 'Private' },
    { code: '5910', name: 'P S N A College of Engg. and Technology', type: 'Private' },
    { code: '5913', name: 'Ratnavel Subramaniam College of Engg. & Tech.', type: 'Private' },
    { code: '5930', name: 'SBM College of Engg. and Technology', type: 'Private' },
  ]},
  { district: 'Erode', districtTamil: 'ஈரோடு', colleges: [
    { code: '2332', name: 'Aishwarya College of Engg. and Technology', type: 'Private' },
    { code: '2652', name: 'Al-Ameen Engineering College', type: 'Private' },
    { code: '2702', name: 'Bannari Amman Institute of Technology', type: 'Private' },
    { code: '2707', name: 'Erode Sengunthar Engineering College', type: 'Private' },
    { code: '2709', name: 'Institute of Road and Transport Technology', type: 'Govt' },
    { code: '2711', name: 'Kongu Engineering College', type: 'Private' },
    { code: '2713', name: 'M P Nachimuthu M Jagannathan Engg. College', type: 'Private' },
    { code: '2715', name: 'Nandha Engineering College', type: 'Private' },
    { code: '2723', name: 'Velalar College of Engg. and Technology', type: 'Private' },
    { code: '2747', name: 'Shree Venkateshwara Hi-Tech Engg. College', type: 'Private' },
    { code: '2748', name: 'Surya Engineering College', type: 'Private' },
    { code: '2752', name: 'Nandha College of Technology', type: 'Private' },
    { code: '2758', name: 'J K K Muniraja College of Technology', type: 'Private' },
  ]},
];

export const getTotalColleges = () => tneaSportsQuotaColleges.reduce((s, d) => s + d.colleges.length, 0);
export const getDistrictCount = () => tneaSportsQuotaColleges.length;
export const getGovtCount = () => tneaSportsQuotaColleges.reduce((s, d) => s + d.colleges.filter(c => c.type !== 'Private').length, 0);
