export interface College {
  id: string;
  name: string;
  type: 'government' | 'government-aided' | 'private' | 'autonomous';
  category: CollegeCategory;
  naacGrade?: string;
  establishedYear?: number;
  courses: string;
  contact?: string;
  website?: string;
  feeRange?: string;
  address?: string;
  accreditation?: string;
  isJKKN?: boolean;
  placementStats?: string;
  facilities?: string[];
}

export type CollegeCategory = 
  | 'arts_science'
  | 'medical'
  | 'dental'
  | 'allied_health'
  | 'pharmacy'
  | 'nursing'
  | 'engineering'
  | 'agricultural'
  | 'education'
  | 'law'
  | 'hotel_management'
  | 'management'
  | 'fine_arts'
  | 'physical_education'
  | 'polytechnic';

export interface CategoryInfo {
  id: CollegeCategory;
  name: string;
  icon: string;
  order: number;
}

export const COLLEGE_CATEGORIES: CategoryInfo[] = [
  { id: 'arts_science', name: 'Arts and Science Colleges', icon: '🏛️', order: 1 },
  { id: 'medical', name: 'Medical Colleges (MBBS)', icon: '⚕️', order: 2 },
  { id: 'dental', name: 'Dental Colleges', icon: '🦷', order: 3 },
  { id: 'allied_health', name: 'Allied Health Sciences (AHS)', icon: '🏥', order: 4 },
  { id: 'pharmacy', name: 'Pharmacy Colleges', icon: '💊', order: 5 },
  { id: 'nursing', name: 'Nursing Colleges', icon: '👩‍⚕️', order: 6 },
  { id: 'engineering', name: 'Engineering Colleges', icon: '⚙️', order: 7 },
  { id: 'agricultural', name: 'Agricultural Colleges', icon: '🌾', order: 8 },
  { id: 'education', name: 'Education Colleges (B.Ed)', icon: '📚', order: 9 },
  { id: 'law', name: 'Law Colleges', icon: '⚖️', order: 10 },
  { id: 'hotel_management', name: 'Hotel Management Colleges', icon: '🏨', order: 11 },
  { id: 'management', name: 'Management/Business Colleges', icon: '💼', order: 12 },
  { id: 'fine_arts', name: 'Fine Arts Colleges', icon: '🎨', order: 13 },
  { id: 'physical_education', name: 'Physical Education Colleges', icon: '🏋️', order: 14 },
  { id: 'polytechnic', name: 'Polytechnic Colleges', icon: '🔬', order: 15 },
];

export const TAMIL_NADU_DISTRICTS = [
  'Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli', 'Salem', 
  'Tirunelveli', 'Erode', 'Vellore', 'Thoothukudi', 'Dindigul',
  'Thanjavur', 'Ranipet', 'Sivaganga', 'Karur', 'Tirupur',
  'Nagapattinam', 'Cuddalore', 'Kanchipuram', 'Tiruvallur', 'Virudhunagar',
  'Namakkal', 'Krishnagiri', 'Theni', 'Perambalur', 'Ariyalur',
  'Nilgiris', 'Ramanathapuram', 'Villupuram', 'Tiruvannamalai', 'Pudukkottai',
  'Dharmapuri', 'Kanyakumari', 'Kallakurichi', 'Chengalpattu', 'Tenkasi',
  'Tirupattur', 'Mayiladuthurai', 'Thiruvarur'
].sort();

export const COLLEGE_TYPE_INFO = {
  government: { label: 'Government', color: 'bg-green-500', badge: '🟢' },
  'government-aided': { label: 'Government-Aided', color: 'bg-blue-500', badge: '🔵' },
  private: { label: 'Private', color: 'bg-orange-500', badge: '🟠' },
  autonomous: { label: 'Autonomous', color: 'bg-purple-500', badge: '🟣' },
};

// Namakkal District Colleges - Complete List
export const NAMAKKAL_FEATURED_COLLEGES: College[] = [
  // ============================================
  // 1. GOVERNMENT COLLEGES
  // ============================================
  {
    id: 'arignar_anna_govt_arts',
    name: 'Arignar Anna Government Arts College, Namakkal',
    type: 'government',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, M.A, M.Sc, M.Com',
    address: 'Sanniyasikaradu, Namakkal',
    feeRange: '₹1,000 - ₹5,000 per year',
  },
  {
    id: 'nkr_govt_arts_women',
    name: 'NKR Government Arts College for Women, Namakkal',
    type: 'government',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc',
    address: 'Trichy Road, Namakkal',
    feeRange: '₹1,000 - ₹5,000 per year',
  },
  {
    id: 'thiruvalluvar_govt_arts',
    name: 'Thiruvalluvar Government Arts College, Rasipuram',
    type: 'government',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, M.A, M.Sc',
    address: 'Andagalur Gate, Rasipuram',
    feeRange: '₹1,000 - ₹5,000 per year',
  },
  {
    id: 'govt_arts_science_komarapalayam',
    name: 'Government Arts and Science College, Komarapalayam',
    type: 'government',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, M.A, M.Sc',
    address: 'Komarapalayam',
    feeRange: '₹1,000 - ₹5,000 per year',
  },
  {
    id: 'govt_arts_science_senthamangalam',
    name: 'Government Arts and Science College, Senthamangalam',
    type: 'government',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com',
    address: 'Senthamangalam',
    feeRange: '₹1,000 - ₹5,000 per year',
  },
  {
    id: 'govt_medical_college_namakkal',
    name: 'Government Medical College, Namakkal',
    type: 'government',
    category: 'medical',
    courses: 'MBBS',
    address: 'Siluvampatti, Namakkal',
    feeRange: '₹15,000 - ₹25,000 per year',
    accreditation: 'NMC Approved',
  },
  {
    id: 'govt_law_college_namakkal',
    name: 'Government Law College, Namakkal',
    type: 'government',
    category: 'law',
    courses: 'B.A. LL.B (5 Year), LL.B (3 Year)',
    address: 'Namakkal',
    feeRange: '₹2,000 - ₹10,000 per year',
    accreditation: 'Bar Council of India Approved',
  },
  {
    id: 'vcri_namakkal',
    name: 'Veterinary College and Research Institute (VCRI), Namakkal',
    type: 'government',
    category: 'agricultural',
    courses: 'B.V.Sc & A.H, M.V.Sc, Ph.D',
    address: 'TANUVAS constituent',
    feeRange: '₹5,000 - ₹15,000 per year',
    accreditation: 'VCI Approved, TANUVAS Affiliated',
  },
  {
    id: 'govt_college_education_komarapalayam',
    name: 'Government College of Education, Komarapalayam',
    type: 'government',
    category: 'education',
    courses: 'B.Ed, M.Ed',
    address: 'Komarapalayam',
    feeRange: '₹2,000 - ₹8,000 per year',
    accreditation: 'NCTE Approved',
  },
  {
    id: 'govt_polytechnic_mohanur',
    name: 'Government Polytechnic College, Mohanur',
    type: 'government',
    category: 'polytechnic',
    courses: 'Diploma in Mechanical, Civil, ECE, EEE',
    address: 'Mohanur',
    feeRange: '₹2,000 - ₹5,000 per year',
    accreditation: 'AICTE Approved',
  },

  // ============================================
  // 2. AIDED COLLEGES
  // ============================================
  {
    id: 'kandaswami_kandars_college',
    name: "Kandaswami Kandar's College, Velur",
    type: 'government-aided',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc, M.Com',
    address: 'Paramathi Velur',
    feeRange: '₹5,000 - ₹25,000 per year',
  },
  {
    id: 'jkkn_aided_arts_science',
    name: 'J.K.K. Nataraja (JKKN) College of Arts & Science, Komarapalayam',
    type: 'government-aided',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com',
    address: 'Komarapalayam (Operates both Aided and Self-Financing streams)',
    feeRange: '₹5,000 - ₹25,000 per year',
    website: 'https://artsci.jkkn.ac.in',
    isJKKN: true,
  },

  // ============================================
  // 3. AUTONOMOUS COLLEGES - Arts & Science
  // ============================================
  {
    id: 'jkkn_autonomous_arts_science',
    name: 'J.K.K. Nataraja (JKKN) College of Arts & Science',
    type: 'autonomous',
    category: 'arts_science',
    courses: 'B.Sc, B.Com, BCA, BBA, M.Sc, M.Com, MBA',
    address: 'Komarapalayam',
    feeRange: '₹25,000 - ₹75,000 per year',
    website: 'https://artsci.jkkn.ac.in',
    isJKKN: true,
  },
  {
    id: 'ksr_arts_science',
    name: 'K.S.R. College of Arts & Science, Tiruchengode',
    type: 'autonomous',
    category: 'arts_science',
    courses: 'B.Sc, B.Com, BCA, BBA, M.Sc, M.Com, MBA',
    address: 'Tiruchengode',
    feeRange: '₹30,000 - ₹80,000 per year',
    website: 'https://www.ksrcas.edu',
  },
  {
    id: 'selvamm_arts_science',
    name: 'Selvamm Arts and Science College, Namakkal',
    type: 'autonomous',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc',
    address: 'Namakkal',
    feeRange: '₹20,000 - ₹50,000 per year',
    accreditation: 'NAAC A+ Accredited',
  },
  {
    id: 'vivekanandha_arts_science',
    name: 'Vivekanandha College (VICAS), Elayampalayam',
    type: 'autonomous',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com',
    address: 'Elayampalayam',
    feeRange: '₹25,000 - ₹70,000 per year',
  },
  {
    id: 'mahendra_arts_science',
    name: 'Mahendra Arts and Science College, Kalipatti',
    type: 'autonomous',
    category: 'arts_science',
    courses: 'B.Sc, B.Com, BCA, BBA, M.Sc, M.Com',
    address: 'Kalipatti',
    feeRange: '₹20,000 - ₹50,000 per year',
  },
  {
    id: 'vivekanandha_arts_science_women',
    name: 'Vivekanandha College of Arts and Sciences for Women, Tiruchengode',
    type: 'autonomous',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com',
    address: 'Tiruchengode',
    feeRange: '₹20,000 - ₹60,000 per year',
  },
  {
    id: 'sengunthar_arts_science',
    name: 'Sengunthar Arts and Science College, Tiruchengode',
    type: 'autonomous',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc',
    address: 'Tiruchengode',
    feeRange: '₹20,000 - ₹50,000 per year',
  },
  {
    id: 'muthayammal_arts_science',
    name: 'Muthayammal College of Arts & Science',
    type: 'autonomous',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc',
    address: 'Rasipuram',
    feeRange: '₹20,000 - ₹50,000 per year',
  },

  // ============================================
  // 3. AUTONOMOUS COLLEGES - Engineering & Technology
  // ============================================
  {
    id: 'excel_engineering',
    name: 'Excel Engineering College (Autonomous), Komarapalayam',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Komarapalayam | TNEA Code: 2634',
    feeRange: '₹50,000 - ₹1,20,000 per year',
    accreditation: 'AICTE Approved, Autonomous',
  },
  {
    id: 'paavai_engineering',
    name: 'Paavai Engineering College (Autonomous), Pachal',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Pachal | TNEA Code: 2611',
    feeRange: '₹55,000 - ₹1,20,000 per year',
    accreditation: 'AICTE Approved, NBA Accredited',
  },
  {
    id: 'ksrct',
    name: 'K.S. Rangasamy College of Technology (Autonomous), Tiruchengode',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil, AI&ML), M.E/M.Tech, MBA',
    address: 'Tiruchengode | TNEA Code: 2607',
    feeRange: '₹70,000 - ₹1,50,000 per year',
    accreditation: 'NBA Accredited, AICTE Approved',
    website: 'https://www.ksrct.ac.in',
  },
  {
    id: 'ksr_engineering',
    name: 'K.S.R. College of Engineering (Autonomous), Tiruchengode',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Tiruchengode | TNEA Code: 2613',
    feeRange: '₹60,000 - ₹1,20,000 per year',
    accreditation: 'AICTE Approved, Autonomous',
    website: 'https://ksrce.ac.in',
  },
  {
    id: 'mahendra_engineering',
    name: 'Mahendra Engineering College (Autonomous), Mallasamudram',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Mallasamudram | TNEA Code: 2609',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'AICTE Approved, Autonomous',
  },
  {
    id: 'muthayammal_engineering',
    name: 'Muthayammal Engineering College (Autonomous), Rasipuram',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Rasipuram | TNEA Code: 2610',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'AICTE Approved, Autonomous',
  },
  {
    id: 'sengunthar_engineering',
    name: 'Sengunthar Engineering College (Autonomous), Tiruchengode',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech), M.E/M.Tech',
    address: 'Tiruchengode | TNEA Code: 2617',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'AICTE Approved, Autonomous',
  },
  {
    id: 'vivekanandha_engineering_women',
    name: 'Vivekanandha College of Engineering for Women (Autonomous), Tiruchengode',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE), M.E/M.Tech',
    address: 'Elayampalayam | TNEA Code: 2620',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'AICTE Approved, Autonomous',
  },
  {
    id: 'mahendra_institute_tech',
    name: 'Mahendra Institute of Technology (Autonomous), Mallasamudram',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Mallasamudram | TNEA Code: 2632',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'AICTE Approved, Autonomous',
  },

  // ============================================
  // 4. PRIVATE (SELF-FINANCING) COLLEGES - Arts & Science
  // ============================================
  {
    id: 'pgp_arts_science',
    name: 'PGP College of Arts & Science, Namakkal',
    type: 'private',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc',
    address: 'Namakkal',
    feeRange: '₹20,000 - ₹50,000 per year',
  },
  {
    id: 'trinity_college_women',
    name: 'Trinity College for Women, Namakkal',
    type: 'private',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA',
    address: 'Namakkal',
    feeRange: '₹20,000 - ₹45,000 per year',
  },
  {
    id: 'kavithas_arts_science',
    name: "Kavitha's College of Arts & Science, Tiruchengode",
    type: 'private',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA',
    address: 'Tiruchengode',
    feeRange: '₹18,000 - ₹40,000 per year',
  },
  {
    id: 'ssm_arts_science',
    name: 'SSM College of Arts & Science, Komarapalayam',
    type: 'private',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA',
    address: 'Komarapalayam',
    feeRange: '₹20,000 - ₹45,000 per year',
  },
  {
    id: 'loyola_college_mettala',
    name: 'Loyola College, Mettala',
    type: 'private',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com',
    address: 'Mettala',
    feeRange: '₹15,000 - ₹35,000 per year',
  },

  // ============================================
  // 4. PRIVATE (SELF-FINANCING) COLLEGES - Engineering
  // ============================================
  {
    id: 'jkkn_engineering',
    name: 'J.K.K. Nattraja College of Engineering and Technology, Komarapalayam',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Komarapalayam | TNEA Code: 2647',
    feeRange: '₹60,000 - ₹1,50,000 per year',
    accreditation: 'NBA Accredited, AICTE Approved',
    website: 'https://engg.jkkn.ac.in',
    isJKKN: true,
  },
  {
    id: 'annai_mathammal_sheela',
    name: 'Annai Mathammal Sheela Engineering College, Erumappatti',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil)',
    address: 'Erumappatti | TNEA Code: 2602',
    feeRange: '₹45,000 - ₹1,00,000 per year',
    accreditation: 'AICTE Approved, Anna University Affiliated',
  },
  {
    id: 'gnanamani_tech',
    name: 'Gnanamani College of Technology, Pachal',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Pachal | TNEA Code: 2608',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'pgp_engineering',
    name: 'P.G.P. College of Engineering and Technology, Namakkal',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil)',
    address: 'Namakkal | TNEA Code: 2612',
    feeRange: '₹45,000 - ₹1,00,000 per year',
    accreditation: 'AICTE Approved, Anna University Affiliated',
  },
  {
    id: 'ssm_engineering',
    name: 'S.S.M. College of Engineering, Komarapalayam',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Komarapalayam | TNEA Code: 2614',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'muthayammal_college_engineering',
    name: 'Muthayammal College of Engineering, Rasipuram',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil)',
    address: 'Rasipuram | TNEA Code: 2615',
    feeRange: '₹45,000 - ₹1,00,000 per year',
    accreditation: 'AICTE Approved, Anna University Affiliated',
  },
  {
    id: 'vidyaa_vikas_engineering',
    name: 'Vidyaa Vikas College of Engineering and Technology, Tiruchengode',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil)',
    address: 'Tiruchengode | TNEA Code: 2618',
    feeRange: '₹45,000 - ₹1,00,000 per year',
    accreditation: 'AICTE Approved, Anna University Affiliated',
  },
  {
    id: 'gnanamani_engineering',
    name: 'Gnanamani College of Engineering, Pachal',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil)',
    address: 'Pachal | TNEA Code: 2624',
    feeRange: '₹45,000 - ₹1,00,000 per year',
    accreditation: 'AICTE Approved, Anna University Affiliated',
  },
  {
    id: 'vivekanandha_iet_women',
    name: 'Vivekanandha Institute of Engineering & Technology for Women, Tiruchengode',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech)',
    address: 'Tiruchengode | TNEA Code: 2626',
    feeRange: '₹45,000 - ₹1,00,000 per year',
    accreditation: 'AICTE Approved, Anna University Affiliated',
  },
  {
    id: 'selvam_tech',
    name: 'Selvam College of Technology, Namakkal',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, Mech, Civil)',
    address: 'Namakkal | TNEA Code: 2627',
    feeRange: '₹45,000 - ₹90,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'paavai_college_engineering',
    name: 'Paavai College of Engineering, Pachal',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil)',
    address: 'Pachal | TNEA Code: 2628',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'AICTE Approved, Anna University Affiliated',
  },
  {
    id: 'cms_engineering',
    name: 'CMS College of Engineering, Eranapuram',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil)',
    address: 'Eranapuram | TNEA Code: 2635',
    feeRange: '₹45,000 - ₹90,000 per year',
    accreditation: 'AICTE Approved, Anna University Affiliated',
  },
  {
    id: 'mahendra_engineering_women',
    name: 'Mahendra Engineering College for Women, Tiruchengode',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE)',
    address: 'Tiruchengode | TNEA Code: 2638',
    feeRange: '₹45,000 - ₹90,000 per year',
    accreditation: 'AICTE Approved, Anna University Affiliated',
  },
  {
    id: 'vivekanandha_tech_women',
    name: 'Vivekanandha College of Technology for Women, Tiruchengode',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE)',
    address: 'Tiruchengode | TNEA Code: 2661',
    feeRange: '₹45,000 - ₹90,000 per year',
    accreditation: 'AICTE Approved, Anna University Affiliated',
  },
  {
    id: 'excel_college_engineering',
    name: 'Excel College of Engineering and Technology, Komarapalayam',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil)',
    address: 'Komarapalayam | TNEA Code: 2664',
    feeRange: '₹45,000 - ₹90,000 per year',
    accreditation: 'AICTE Approved, Anna University Affiliated',
  },
  {
    id: 'pavai_college_tech',
    name: 'Pavai College of Technology, Pachal',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil)',
    address: 'Pachal | TNEA Code: 2681',
    feeRange: '₹45,000 - ₹90,000 per year',
    accreditation: 'AICTE Approved, Anna University Affiliated',
  },
  {
    id: 'srg_engineering',
    name: 'SRG Engineering College, Aniyapuram',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil)',
    address: 'Aniyapuram | TNEA Code: 2767',
    feeRange: '₹45,000 - ₹90,000 per year',
    accreditation: 'AICTE Approved, Anna University Affiliated',
  },
  {
    id: 'king_tech',
    name: 'King College of Technology, Nallur',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech)',
    address: 'Nallur',
    feeRange: '₹45,000 - ₹90,000 per year',
    accreditation: 'AICTE Approved',
  },

  // ============================================
  // 4. PRIVATE - Medical & Health Sciences
  // ============================================
  {
    id: 'jkkn_dental',
    name: 'JKKN Dental College, Komarapalayam',
    type: 'private',
    category: 'dental',
    courses: 'BDS, MDS',
    address: 'Komarapalayam',
    feeRange: '₹3,00,000 - ₹8,00,000 per year',
    accreditation: 'DCI Approved',
    website: 'https://dental.jkkn.ac.in',
    isJKKN: true,
  },
  {
    id: 'jkkn_pharmacy',
    name: 'JKK Nattraja College of Pharmacy, Komarapalayam',
    type: 'private',
    category: 'pharmacy',
    courses: 'B.Pharm, D.Pharm, M.Pharm, Pharm.D',
    address: 'Komarapalayam',
    feeRange: '₹50,000 - ₹1,50,000 per year',
    accreditation: 'PCI Approved',
    website: 'https://pharmacy.jkkn.ac.in/admission-process',
    isJKKN: true,
  },
  {
    id: 'jkkn_nursing',
    name: 'JKKN College of Nursing, Komarapalayam',
    type: 'private',
    category: 'nursing',
    courses: 'B.Sc Nursing, M.Sc Nursing, GNM, ANM',
    address: 'Komarapalayam',
    feeRange: '₹40,000 - ₹1,20,000 per year',
    accreditation: 'INC Approved',
    website: 'https://nursing.sresakthimayeil.jkkn.ac.in',
    isJKKN: true,
  },
  {
    id: 'ksr_dental',
    name: 'K.S.R. Institute of Dental Science & Research, Tiruchengode',
    type: 'private',
    category: 'dental',
    courses: 'BDS, MDS',
    address: 'Tiruchengode',
    feeRange: '₹3,50,000 - ₹9,00,000 per year',
    accreditation: 'DCI Approved',
    website: 'https://www.ksridsr.edu.in',
  },
  {
    id: 'vivekanandha_dental',
    name: 'Vivekanandha Dental College, Tiruchengode',
    type: 'private',
    category: 'dental',
    courses: 'BDS, MDS',
    address: 'Tiruchengode',
    feeRange: '₹3,00,000 - ₹8,00,000 per year',
    accreditation: 'DCI Approved',
  },
  {
    id: 'vivekanandha_nursing',
    name: 'Vivekanandha College of Nursing, Tiruchengode',
    type: 'private',
    category: 'nursing',
    courses: 'B.Sc Nursing, M.Sc Nursing, GNM',
    address: 'Tiruchengode',
    feeRange: '₹40,000 - ₹1,00,000 per year',
    accreditation: 'INC Approved',
  },
  {
    id: 'vivekanandha_pharmacy',
    name: 'Swamy Vivekanandha College of Pharmacy, Tiruchengode',
    type: 'private',
    category: 'pharmacy',
    courses: 'B.Pharm, D.Pharm, M.Pharm',
    address: 'Tiruchengode',
    feeRange: '₹50,000 - ₹1,20,000 per year',
    accreditation: 'PCI Approved',
  },
  {
    id: 'excel_siddha',
    name: 'Excel Medical & Paramedical Institutions (Siddha)',
    type: 'private',
    category: 'medical',
    courses: 'BSMS (Siddha Medicine)',
    address: 'Pallakkapalayam',
    feeRange: '₹1,00,000 - ₹2,50,000 per year',
  },
  {
    id: 'excel_homeopathy',
    name: 'Excel Medical & Paramedical Institutions (Homeopathy)',
    type: 'private',
    category: 'medical',
    courses: 'BHMS (Homeopathy)',
    address: 'Pallakkapalayam',
    feeRange: '₹1,00,000 - ₹2,50,000 per year',
  },
  {
    id: 'excel_bpt',
    name: 'Excel Medical & Paramedical Institutions (Physiotherapy)',
    type: 'private',
    category: 'allied_health',
    courses: 'BPT (Physiotherapy)',
    address: 'Pallakkapalayam',
    feeRange: '₹80,000 - ₹1,50,000 per year',
  },

  // ============================================
  // 4A. PRIVATE - Allied Health Sciences Colleges
  // ============================================
  {
    id: 'jkkn_allied_health',
    name: 'JKKN College of Allied Health Sciences, Komarapalayam',
    type: 'private',
    category: 'allied_health',
    courses: 'B.Sc Allied Health Sciences, B.Sc MLT, B.Sc Radiology, B.Sc Cardiac Technology, B.Sc Optometry',
    address: 'Komarapalayam',
    feeRange: '₹50,000 - ₹1,20,000 per year',
    accreditation: 'TN Dr. M.G.R. Medical University Affiliated',
    website: 'https://ahs.jkkn.ac.in',
    isJKKN: true,
  },
  {
    id: 'vivekanandha_allied_health',
    name: 'Vivekanandha College of Allied Health Sciences, Tiruchengode',
    type: 'private',
    category: 'allied_health',
    courses: 'B.Sc Allied Health Sciences, B.Sc MLT, B.Sc Radiology, B.Sc Cardiac Technology',
    address: 'Tiruchengode',
    feeRange: '₹50,000 - ₹1,20,000 per year',
    accreditation: 'TN Dr. M.G.R. Medical University Affiliated',
  },
  {
    id: 'excel_health_sciences',
    name: 'Excel Institute of Health Sciences, Komarapalayam',
    type: 'private',
    category: 'allied_health',
    courses: 'B.Sc Allied Health Sciences, B.Sc MLT, BPT, Paramedical Courses',
    address: 'Komarapalayam',
    feeRange: '₹50,000 - ₹1,20,000 per year',
  },
  {
    id: 'dhanvantri_allied_health',
    name: 'Dhanvantri College of Allied Health Sciences, Tiruchengode',
    type: 'private',
    category: 'allied_health',
    courses: 'B.Sc Allied Health Sciences, B.Sc MLT, Paramedical Courses',
    address: 'Tiruchengode',
    feeRange: '₹50,000 - ₹1,00,000 per year',
  },

  // ============================================
  // 4C. PRIVATE - Pharmacy Colleges (Complete List)
  // ============================================
  {
    id: 'excel_pharmacy',
    name: 'Excel College of Pharmacy, Komarapalayam',
    type: 'private',
    category: 'pharmacy',
    courses: 'B.Pharm, D.Pharm',
    address: 'Komarapalayam',
    feeRange: '₹50,000 - ₹1,20,000 per year',
    accreditation: 'PCI Approved',
  },
  {
    id: 'sengunthar_pharmacy',
    name: 'Sengunthar College of Pharmacy, Tiruchengode',
    type: 'private',
    category: 'pharmacy',
    courses: 'B.Pharm, D.Pharm',
    address: 'Tiruchengode',
    feeRange: '₹50,000 - ₹1,20,000 per year',
    accreditation: 'PCI Approved',
  },

  // ============================================
  // 4B. PRIVATE - Nursing Colleges (Complete List)
  // ============================================
  {
    id: 'anbu_nursing',
    name: 'Anbu College of Nursing, Namakkal',
    type: 'private',
    category: 'nursing',
    courses: 'B.Sc Nursing, GNM, ANM',
    address: 'Namakkal',
    feeRange: '₹40,000 - ₹1,00,000 per year',
    accreditation: 'INC Approved',
  },
  {
    id: 'annai_jkk_sampoorani_nursing',
    name: 'Annai JKK Sampoorani Ammal College of Nursing, Komarapalayam',
    type: 'private',
    category: 'nursing',
    courses: 'B.Sc Nursing, M.Sc Nursing, GNM, ANM',
    address: 'Komarapalayam',
    feeRange: '₹40,000 - ₹1,20,000 per year',
    accreditation: 'INC Approved',
    website: 'https://nursing.sresakthimayeil.jkkn.ac.in',
    isJKKN: true,
  },
  {
    id: 'arvinth_nursing',
    name: 'Arvinth College of Nursing, Namakkal',
    type: 'private',
    category: 'nursing',
    courses: 'B.Sc Nursing, GNM',
    address: 'Namakkal',
    feeRange: '₹40,000 - ₹1,00,000 per year',
    accreditation: 'INC Approved',
  },
  {
    id: 'dhanvantri_nursing',
    name: 'Dhanvantri College of Nursing, Namakkal',
    type: 'private',
    category: 'nursing',
    courses: 'B.Sc Nursing, GNM',
    address: 'Namakkal',
    feeRange: '₹40,000 - ₹1,00,000 per year',
    accreditation: 'INC Approved',
  },
  {
    id: 'deepthi_nursing',
    name: 'Deepthi College of Nursing, Namakkal',
    type: 'private',
    category: 'nursing',
    courses: 'B.Sc Nursing, GNM',
    address: 'Namakkal',
    feeRange: '₹40,000 - ₹1,00,000 per year',
    accreditation: 'INC Approved',
  },
  {
    id: 'pgp_nursing',
    name: 'PGP College of Nursing and Research, Namakkal',
    type: 'private',
    category: 'nursing',
    courses: 'B.Sc Nursing, M.Sc Nursing, GNM',
    address: 'Namakkal',
    feeRange: '₹40,000 - ₹1,20,000 per year',
    accreditation: 'INC Approved, TN Dr. M.G.R. Medical University Affiliated',
  },
  {
    id: 'paavai_nursing',
    name: 'Paavai College of Nursing and Research, Pachal',
    type: 'private',
    category: 'nursing',
    courses: 'B.Sc Nursing, M.Sc Nursing, GNM',
    address: 'Pachal',
    feeRange: '₹40,000 - ₹1,20,000 per year',
    accreditation: 'INC Approved',
  },
  {
    id: 'hahnemann_nursing',
    name: 'Dr Hahnemann Homoeopathy Medical College & Research Centre (Nursing), Namakkal',
    type: 'private',
    category: 'nursing',
    courses: 'B.Sc Nursing',
    address: 'Namakkal',
    feeRange: '₹40,000 - ₹1,00,000 per year',
  },
  {
    id: 'sresakthimayeil_nursing',
    name: 'Sresakthimayeil Institute of Nursing and Research, Komarapalayam',
    type: 'private',
    category: 'nursing',
    courses: 'B.Sc Nursing, GNM',
    address: 'Komarapalayam',
    feeRange: '₹40,000 - ₹1,00,000 per year',
    accreditation: 'INC Approved',
    website: 'https://nursing.sresakthimayeil.jkkn.ac.in',
    isJKKN: true,
  },
  {
    id: 'ksr_nursing',
    name: 'KS Rangasamy College of Nursing, Tiruchengode',
    type: 'private',
    category: 'nursing',
    courses: 'B.Sc Nursing, M.Sc Nursing, GNM',
    address: 'Tiruchengode',
    feeRange: '₹40,000 - ₹1,20,000 per year',
    accreditation: 'INC Approved',
    website: 'https://www.ksrei.org',
  },
  {
    id: 'sengunthar_nursing',
    name: 'Sengunthar College of Nursing, Namakkal',
    type: 'private',
    category: 'nursing',
    courses: 'B.Sc Nursing, GNM',
    address: 'Namakkal',
    feeRange: '₹40,000 - ₹1,00,000 per year',
    accreditation: 'INC Approved',
  },
  {
    id: 'excel_nursing',
    name: 'Excel College of Nursing, Pallakkapalayam',
    type: 'private',
    category: 'nursing',
    courses: 'B.Sc Nursing, GNM',
    address: 'Pallakkapalayam',
    feeRange: '₹40,000 - ₹1,00,000 per year',
    accreditation: 'INC Approved',
  },

  // ============================================
  // 5. AGRICULTURE & SPECIALIZED COLLEGES
  // ============================================
  {
    id: 'pgp_agricultural',
    name: 'PGP College of Agricultural Sciences, Vettambadi',
    type: 'private',
    category: 'agricultural',
    courses: 'B.Sc Agriculture, B.Sc Horticulture',
    address: 'Vettambadi (Affiliated with TNAU)',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'TNAU Affiliated',
  },
  {
    id: 'paavai_agricultural',
    name: 'Paavai Institutions (Agriculture Engineering), Pachal',
    type: 'private',
    category: 'agricultural',
    courses: 'B.Tech Agricultural Engineering',
    address: 'Pachal',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'TNAU Affiliated',
  },
  {
    id: 'vcri_laddivadi',
    name: 'Veterinary College and Research Institute (VCRI), Laddivadi',
    type: 'government',
    category: 'agricultural',
    courses: 'B.V.Sc & A.H, M.V.Sc',
    address: 'Laddivadi, Namakkal',
    feeRange: '₹5,000 - ₹15,000 per year',
    accreditation: 'VCI Approved, TANUVAS Affiliated',
  },
];

// Erode District Colleges - Complete List
export const ERODE_FEATURED_COLLEGES: College[] = [
  // ============================================
  // 1. GOVERNMENT & UNIVERSITY CONSTITUENT COLLEGES
  // ============================================
  {
    id: 'gce_erode',
    name: 'Government College of Engineering (GCE), Erode',
    type: 'government',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Chithode, Erode (Formerly IRTT)',
    feeRange: '₹10,000 - ₹30,000 per year',
    accreditation: 'AICTE Approved, Anna University Affiliated',
  },
  {
    id: 'govt_erode_medical',
    name: 'Government Erode Medical College & Hospital, Perundurai',
    type: 'government',
    category: 'medical',
    courses: 'MBBS',
    address: 'Perundurai, Erode',
    feeRange: '₹15,000 - ₹25,000 per year',
    accreditation: 'NMC Approved',
  },
  {
    id: 'cnc_erode',
    name: 'Chikkaiah Naicker College (CNC), Erode',
    type: 'government',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc, M.Com',
    address: 'Erode',
    feeRange: '₹1,000 - ₹5,000 per year',
  },
  {
    id: 'govt_arts_sathyamangalam',
    name: 'Government Arts and Science College, Sathyamangalam',
    type: 'government',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, M.A, M.Sc',
    address: 'Sathyamangalam, Erode',
    feeRange: '₹1,000 - ₹5,000 per year',
  },
  {
    id: 'govt_arts_thittamalai',
    name: 'Government Arts and Science College, Thittamalai',
    type: 'government',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com',
    address: 'Thittamalai, Erode',
    feeRange: '₹1,000 - ₹5,000 per year',
  },
  {
    id: 'govt_arts_modakkurichi',
    name: 'Government Arts and Science College, Modakkurichi',
    type: 'government',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com',
    address: 'Modakkurichi, Erode',
    feeRange: '₹1,000 - ₹5,000 per year',
  },
  {
    id: 'bharathiar_pg_erode',
    name: 'Bharathiar University PG Extension and Research Centre, Erode',
    type: 'government',
    category: 'arts_science',
    courses: 'M.A, M.Sc, M.Com, M.Phil, Ph.D',
    address: 'Erode',
    feeRange: '₹5,000 - ₹15,000 per year',
    accreditation: 'Bharathiar University Constituent',
  },
  {
    id: 'govt_arts_nambiyur',
    name: 'Government Arts and Science College, Nambiyur',
    type: 'government',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com',
    address: 'Nambiyur, Erode',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'Bharathiar University Affiliated',
  },

  // ============================================
  // 2. AUTONOMOUS COLLEGES - Engineering
  // ============================================
  {
    id: 'bit_sathyamangalam',
    name: 'Bannari Amman Institute of Technology (BIT), Sathyamangalam',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil, AI&ML), M.E/M.Tech, MBA',
    address: 'Sathyamangalam, Erode',
    feeRange: '₹80,000 - ₹1,50,000 per year',
    accreditation: 'NBA Accredited, NAAC A++',
  },
  {
    id: 'kec_perundurai',
    name: 'Kongu Engineering College (KEC), Perundurai',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil, AI&DS), M.E/M.Tech, MBA',
    address: 'Perundurai, Erode',
    feeRange: '₹75,000 - ₹1,40,000 per year',
    accreditation: 'NBA Accredited, NAAC A+',
  },
  {
    id: 'vcet_thindal',
    name: 'Velalar College of Engineering and Technology (VCET), Thindal',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Thindal, Erode',
    feeRange: '₹60,000 - ₹1,20,000 per year',
    accreditation: 'NBA Accredited, AICTE Approved',
  },
  {
    id: 'nandha_engineering',
    name: 'Nandha Engineering College, Vaikkalmedu',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Vaikkalmedu, Erode',
    feeRange: '₹60,000 - ₹1,20,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'esec_thudupathi',
    name: 'Erode Sengunthar Engineering College, Thudupathi',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Thudupathi, Erode',
    feeRange: '₹55,000 - ₹1,10,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'alameen_engineering',
    name: 'Al-Ameen Engineering College, Erode',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Erode',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'AICTE Approved',
  },

  // ============================================
  // 2. AUTONOMOUS COLLEGES - Arts & Science
  // ============================================
  {
    id: 'kongu_arts_science',
    name: 'Kongu Arts and Science College, Nanjanapuram',
    type: 'autonomous',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com, MBA',
    address: 'Nanjanapuram, Erode',
    feeRange: '₹25,000 - ₹70,000 per year',
  },
  {
    id: 'easc_erode',
    name: 'Erode Arts and Science College (EASC), Rangampalayam',
    type: 'autonomous',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com',
    address: 'Rangampalayam, Erode',
    feeRange: '₹20,000 - ₹60,000 per year',
  },
  {
    id: 'vellalar_women',
    name: 'Vellalar College for Women, Thindal',
    type: 'autonomous',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com',
    address: 'Thindal, Erode',
    feeRange: '₹20,000 - ₹60,000 per year',
  },
  {
    id: 'gobi_arts_science',
    name: 'Gobi Arts & Science College, Gobichettipalayam',
    type: 'autonomous',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com',
    address: 'Gobichettipalayam, Erode',
    feeRange: '₹20,000 - ₹55,000 per year',
  },
  {
    id: 'nandha_arts_science',
    name: 'Nandha Arts and Science College, Erode',
    type: 'autonomous',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com',
    address: 'Erode',
    feeRange: '₹20,000 - ₹55,000 per year',
  },

  // ============================================
  // 3. PRIVATE (SELF-FINANCING) - Engineering
  // ============================================
  {
    id: 'nandha_tech',
    name: 'Nandha College of Technology, Erode',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Erode',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'surya_engineering',
    name: 'Surya Engineering College, Kathirampatti',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech)',
    address: 'Kathirampatti, Erode',
    feeRange: '₹45,000 - ₹90,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'svhec_gobi',
    name: 'Shree Venkateshwara Hi-Tech Engineering College, Gobi',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil)',
    address: 'Gobichettipalayam, Erode',
    feeRange: '₹45,000 - ₹90,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'mpnmj_engineering',
    name: 'MP Nachimuthu M Jaganathan Engineering College, Chennimalai',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil)',
    address: 'Chennimalai, Erode',
    feeRange: '₹45,000 - ₹90,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'jkkm_tech',
    name: 'J.K.K. Munirajah College of Technology, TN Palayam',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech)',
    address: 'TN Palayam, Erode',
    feeRange: '₹45,000 - ₹90,000 per year',
    accreditation: 'AICTE Approved',
  },

  // ============================================
  // 3. PRIVATE (SELF-FINANCING) - Arts & Science
  // ============================================
  {
    id: 'bharathidasan_ellispettai',
    name: 'Bharathidasan College of Arts and Science, Ellispettai',
    type: 'private',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA',
    address: 'Ellispettai, Erode',
    feeRange: '₹18,000 - ₹45,000 per year',
  },
  {
    id: 'navarasam_women',
    name: 'Navarasam Arts and Science College for Women, Arachalur',
    type: 'private',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA',
    address: 'Arachalur, Erode',
    feeRange: '₹18,000 - ₹45,000 per year',
  },
  {
    id: 'kaamadhenu_arts',
    name: 'Kaamadhenu Arts and Science College, Sathyamangalam',
    type: 'private',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA',
    address: 'Sathyamangalam, Erode',
    feeRange: '₹18,000 - ₹45,000 per year',
  },
  {
    id: 'sri_vasavi_sf',
    name: 'Sri Vasavi College (Self-Finance Wing), Chithode',
    type: 'private',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA',
    address: 'Chithode, Erode',
    feeRange: '₹18,000 - ₹45,000 per year',
  },
  {
    id: 'adharsh_women',
    name: 'Adharsh Vidhyalaya Arts and Science College for Women, Bhavani',
    type: 'private',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA',
    address: 'Bhavani, Erode',
    feeRange: '₹18,000 - ₹45,000 per year',
  },

  // ============================================
  // 4. AGRICULTURE & SPECIALIZED COLLEGES
  // ============================================
  {
    id: 'kia_sakthinagar',
    name: 'Kumaraguru Institute of Agriculture (KIA), Sakthi Nagar',
    type: 'private',
    category: 'agricultural',
    courses: 'B.Sc Agriculture, B.Sc Horticulture',
    address: 'Sakthi Nagar, Erode',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'TNAU Affiliated',
  },
  {
    id: 'jkkm_agricultural',
    name: 'J.K.K. Munirajah College of Agricultural Science, TN Palayam',
    type: 'private',
    category: 'agricultural',
    courses: 'B.Sc Agriculture',
    address: 'TN Palayam, Erode',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'TNAU Affiliated',
  },
  {
    id: 'nandha_medical',
    name: 'Nandha Medical College & Hospital, Erode',
    type: 'private',
    category: 'medical',
    courses: 'MBBS, MD, MS',
    address: 'Erode',
    feeRange: '₹10,00,000 - ₹20,00,000 per year',
    accreditation: 'NMC Approved',
  },
  {
    id: 'nandha_pharmacy',
    name: 'Nandha College of Pharmacy, Erode',
    type: 'private',
    category: 'pharmacy',
    courses: 'B.Pharm, D.Pharm, M.Pharm, Pharm.D',
    address: 'Erode',
    feeRange: '₹50,000 - ₹1,50,000 per year',
    accreditation: 'PCI Approved',
  },
  {
    id: 'nandha_nursing',
    name: 'Nandha College of Nursing, Erode',
    type: 'private',
    category: 'nursing',
    courses: 'B.Sc Nursing, M.Sc Nursing, GNM',
    address: 'Erode',
    feeRange: '₹40,000 - ₹1,20,000 per year',
    accreditation: 'INC Approved',
  },
  {
    id: 'nandha_physio',
    name: 'Nandha College of Physiotherapy, Erode',
    type: 'private',
    category: 'allied_health',
    courses: 'BPT, MPT',
    address: 'Erode',
    feeRange: '₹80,000 - ₹1,50,000 per year',
  },
  {
    id: 'erode_law',
    name: 'Erode College of Law, Erode',
    type: 'private',
    category: 'law',
    courses: 'B.A. LL.B (5 Year), LL.B (3 Year), LL.M',
    address: 'Erode',
    feeRange: '₹30,000 - ₹80,000 per year',
    accreditation: 'Bar Council of India Approved',
  },

  // ============================================
  // 5. POLYTECHNIC COLLEGES
  // ============================================
  {
    id: 'sakthi_polytechnic',
    name: 'Sakthi Polytechnic College, Sakthi Nagar',
    type: 'private',
    category: 'polytechnic',
    courses: 'Diploma in Mechanical, Civil, ECE, EEE, Computer',
    address: 'Sakthi Nagar, Erode',
    feeRange: '₹15,000 - ₹40,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'nandha_polytechnic',
    name: 'Nandha Polytechnic College, Erode',
    type: 'private',
    category: 'polytechnic',
    courses: 'Diploma in Mechanical, Civil, ECE, EEE, Computer',
    address: 'Erode',
    feeRange: '₹15,000 - ₹40,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'kongu_polytechnic',
    name: 'Kongu Polytechnic College, Perundurai',
    type: 'private',
    category: 'polytechnic',
    courses: 'Diploma in Mechanical, Civil, ECE, EEE, Computer',
    address: 'Perundurai, Erode',
    feeRange: '₹15,000 - ₹40,000 per year',
    accreditation: 'AICTE Approved',
  },

  // ============================================
  // 6. ADDITIONAL ENGINEERING COLLEGES
  // ============================================
  {
    id: 'aishwarya_engineering',
    name: 'Aishwarya College of Engineering & Technology, Bhavani',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil)',
    address: 'Bhavani, Erode',
    feeRange: '₹45,000 - ₹90,000 per year',
    accreditation: 'AICTE Approved',
  },

  // ============================================
  // 7. ADDITIONAL ARTS & SCIENCE COLLEGES
  // ============================================
  {
    id: 'vetias_erode',
    name: 'VET Institute of Arts and Science (VETIAS), Erode',
    type: 'private',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA',
    address: 'Erode',
    feeRange: '₹18,000 - ₹45,000 per year',
  },
  {
    id: 'sri_amman_arts_science',
    name: 'Sri Amman Arts and Science College, Chittode',
    type: 'private',
    category: 'arts_science',
    courses: 'B.A (English), B.Sc (Computer Science, Maths, Physics), B.Com (CA, PA, General), BBA, M.Com, M.Sc Computer Science',
    address: 'Chittode (Vaikkalmedu), Erode',
    feeRange: '₹18,000 - ₹50,000 per year',
    accreditation: 'Bharathiar University Affiliated',
  },
  {
    id: 'shree_venkateshwara_arts_science',
    name: 'Shree Venkateshwara Arts and Science College, Gobichettipalayam',
    type: 'private',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA',
    address: 'Othakuthirai, Gobichettipalayam, Erode',
    feeRange: '₹18,000 - ₹45,000 per year',
  },

  // ============================================
  // 8. ADDITIONAL MEDICAL, DENTAL & HEALTH COLLEGES
  // ============================================
  {
    id: 'nandha_dental',
    name: 'Nandha Dental College and Hospital, Erode',
    type: 'private',
    category: 'dental',
    courses: 'BDS, MDS',
    address: 'Vaikkalmedu, Erode',
    feeRange: '₹3,00,000 - ₹8,00,000 per year',
    accreditation: 'DCI Approved',
  },
  {
    id: 'erode_pharmacy',
    name: 'Erode College of Pharmacy, Erode',
    type: 'private',
    category: 'pharmacy',
    courses: 'B.Pharm, D.Pharm, M.Pharm',
    address: 'Erode',
    feeRange: '₹50,000 - ₹1,20,000 per year',
    accreditation: 'PCI Approved',
  },
  {
    id: 'govt_nursing_erode',
    name: 'Government College of Nursing, Erode',
    type: 'government',
    category: 'nursing',
    courses: 'B.Sc Nursing, GNM',
    address: 'Erode',
    feeRange: '₹5,000 - ₹15,000 per year',
    accreditation: 'INC Approved',
  },
  {
    id: 'vellalar_nursing',
    name: 'Vellalar College of Nursing, Erode',
    type: 'private',
    category: 'nursing',
    courses: 'B.Sc Nursing, M.Sc Nursing, GNM',
    address: 'Thindal, Erode',
    feeRange: '₹40,000 - ₹1,00,000 per year',
    accreditation: 'INC Approved',
  },
  {
    id: 'nandha_allied_health',
    name: 'Nandha College of Allied Health Sciences, Erode',
    type: 'private',
    category: 'allied_health',
    courses: 'B.Sc Allied Health Sciences, DMLT, B.Sc MLT, B.Sc Radiology',
    address: 'Erode',
    feeRange: '₹50,000 - ₹1,20,000 per year',
  },

  // ============================================
  // 9. EDUCATION COLLEGES (B.Ed)
  // ============================================
  {
    id: 'vellalar_education',
    name: 'Vellalar College of Education, Erode',
    type: 'private',
    category: 'education',
    courses: 'B.Ed, M.Ed',
    address: 'Thindal, Erode',
    feeRange: '₹30,000 - ₹60,000 per year',
    accreditation: 'NCTE Approved',
  },
  {
    id: 'nandha_education',
    name: 'Nandha College of Education, Erode',
    type: 'private',
    category: 'education',
    courses: 'B.Ed, M.Ed',
    address: 'Erode',
    feeRange: '₹30,000 - ₹60,000 per year',
    accreditation: 'NCTE Approved',
  },
  {
    id: 'gandhi_education',
    name: 'Gandhi College of Education, Erode',
    type: 'private',
    category: 'education',
    courses: 'B.Ed',
    address: 'Erode',
    feeRange: '₹25,000 - ₹50,000 per year',
    accreditation: 'NCTE Approved',
  },
];

// Salem District Colleges - Complete List
export const SALEM_FEATURED_COLLEGES: College[] = [
  // ============================================
  // 1. GOVERNMENT & AIDED COLLEGES
  // ============================================
  {
    id: 'govt_arts_salem',
    name: 'Government Arts College (Autonomous), Salem',
    type: 'government',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc, M.Com, M.Phil, Ph.D',
    address: 'Salem',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'NAAC Accredited, Autonomous',
  },
  {
    id: 'gce_salem',
    name: 'Government College of Engineering (GCE), Salem',
    type: 'government',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil, IT), M.E/M.Tech',
    address: 'Salem',
    feeRange: '₹10,000 - ₹30,000 per year',
    accreditation: 'Autonomous, Anna University Affiliated, NBA Accredited',
  },
  {
    id: 'gmkmc_salem',
    name: 'Government Mohan Kumaramangalam Medical College (GMKMC), Salem',
    type: 'government',
    category: 'medical',
    courses: 'MBBS, MD, MS',
    address: 'Salem',
    feeRange: '₹15,000 - ₹25,000 per year',
    accreditation: 'NMC Approved',
  },
  {
    id: 'govt_law_salem',
    name: 'Government Law College, Salem',
    type: 'government',
    category: 'law',
    courses: 'B.A. LL.B (5 Year), LL.B (3 Year)',
    address: 'Salem',
    feeRange: '₹2,000 - ₹10,000 per year',
    accreditation: 'Bar Council of India Approved',
  },
  {
    id: 'govt_arts_women_salem',
    name: 'Government Arts College for Women, Salem-8',
    type: 'government',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc',
    address: 'Salem-8',
    feeRange: '₹1,000 - ₹5,000 per year',
  },
  {
    id: 'aagac_attur',
    name: 'Arignar Anna Government Arts College, Attur',
    type: 'government',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, M.A, M.Sc',
    address: 'Attur, Salem',
    feeRange: '₹1,000 - ₹5,000 per year',
  },
  {
    id: 'sri_sarada_women',
    name: 'Sri Sarada College for Women (Autonomous), Salem',
    type: 'government-aided',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com, M.Phil',
    address: 'Salem',
    feeRange: '₹5,000 - ₹25,000 per year',
    accreditation: 'NAAC A Grade, Autonomous',
  },
  {
    id: 'salem_sowdeswari',
    name: 'Salem Sowdeswari College, Salem',
    type: 'government-aided',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc, M.Com',
    address: 'Salem',
    feeRange: '₹5,000 - ₹25,000 per year',
  },
  {
    id: 'govt_polytechnic_salem',
    name: 'Government Polytechnic College, Salem',
    type: 'government',
    category: 'polytechnic',
    courses: 'Diploma in Mechanical, Civil, ECE, EEE, Computer',
    address: 'Salem',
    feeRange: '₹2,000 - ₹5,000 per year',
    accreditation: 'AICTE Approved',
  },

  // ============================================
  // 2. AUTONOMOUS COLLEGES - Engineering
  // ============================================
  {
    id: 'sona_tech',
    name: 'Sona College of Technology, Salem',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil, AI&ML), M.E/M.Tech, MBA',
    address: 'Salem',
    feeRange: '₹80,000 - ₹1,50,000 per year',
    accreditation: 'NBA Accredited, NAAC A+',
  },
  {
    id: 'kiot_salem',
    name: 'Knowledge Institute of Technology (KIOT), Kakapalayam',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil, AI&DS), M.E/M.Tech',
    address: 'Kakapalayam, Salem',
    feeRange: '₹70,000 - ₹1,40,000 per year',
    accreditation: 'NBA Accredited, AICTE Approved',
  },
  {
    id: 'annapoorana_engineering',
    name: 'Annapoorana Engineering College, Salem',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Salem',
    feeRange: '₹60,000 - ₹1,20,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'dgct_salem',
    name: 'Dhirajlal Gandhi College of Technology (DGCT), Salem',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Salem',
    feeRange: '₹60,000 - ₹1,20,000 per year',
    accreditation: 'AICTE Approved',
  },

  // ============================================
  // 3. PRIVATE (SELF-FINANCING) - Engineering
  // ============================================
  {
    id: 'avs_engineering',
    name: 'AVS Engineering College, Salem',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Salem',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'mahendra_engineering_salem',
    name: 'Mahendra College of Engineering, Minnampalli',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Minnampalli, Salem',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'vmkvec_salem',
    name: "Vinayaka Mission's Kirupananda Variyar Engineering College, Salem",
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Salem',
    feeRange: '₹60,000 - ₹1,20,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'bharathiyar_women_engg',
    name: 'Bharathiyar Institute of Engineering for Women, Salem',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE)',
    address: 'Salem',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'AICTE Approved',
  },

  // ============================================
  // 3. PRIVATE (SELF-FINANCING) - Arts & Science
  // ============================================
  {
    id: 'avs_arts_science',
    name: 'AVS College of Arts & Science, Salem',
    type: 'private',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com',
    address: 'Salem',
    feeRange: '₹20,000 - ₹50,000 per year',
  },
  {
    id: 'vysya_college',
    name: 'Vysya College, Salem',
    type: 'private',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA',
    address: 'Salem',
    feeRange: '₹18,000 - ₹45,000 per year',
  },
  {
    id: 'jairam_arts_science',
    name: 'Jairam Arts & Science College, Salem',
    type: 'private',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA',
    address: 'Salem',
    feeRange: '₹18,000 - ₹45,000 per year',
  },
  {
    id: 'shri_sakthikailassh_women',
    name: 'Shri Sakthikailassh Women\'s College, Salem',
    type: 'private',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA',
    address: 'Salem',
    feeRange: '₹18,000 - ₹45,000 per year',
  },
  {
    id: 'sona_arts_science',
    name: 'Sona College of Arts & Science, Salem',
    type: 'private',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com',
    address: 'Salem',
    feeRange: '₹25,000 - ₹60,000 per year',
  },

  // ============================================
  // 4. AGRICULTURE & SPECIALIZED COLLEGES
  // ============================================
  {
    id: 'vcri_thalaivasal',
    name: 'Veterinary College and Research Institute (VCRI), Thalaivasal',
    type: 'government',
    category: 'agricultural',
    courses: 'B.V.Sc & A.H, M.V.Sc, Ph.D',
    address: 'Thalaivasal, Salem',
    feeRange: '₹5,000 - ₹15,000 per year',
    accreditation: 'VCI Approved, TANUVAS Affiliated',
  },
  {
    id: 'iiht_salem',
    name: 'Indian Institute of Handloom Technology (IIHT), Salem',
    type: 'government',
    category: 'fine_arts',
    courses: 'Diploma in Handloom & Textile Technology',
    address: 'Salem',
    feeRange: '₹5,000 - ₹15,000 per year',
    accreditation: 'Central Government Institute',
  },
  {
    id: 'vmrf_deemed',
    name: "Vinayaka Mission's Research Foundation (Deemed University), Salem",
    type: 'private',
    category: 'medical',
    courses: 'MBBS, BDS, B.Sc Agriculture, B.Pharm, Nursing',
    address: 'Salem',
    feeRange: '₹2,00,000 - ₹15,00,000 per year',
    accreditation: 'UGC Approved Deemed University',
  },

  // ============================================
  // 5. MEDICAL & DENTAL (PRIVATE)
  // ============================================
  {
    id: 'annapoorana_medical',
    name: 'Annapoorana Medical College and Hospital, Salem',
    type: 'private',
    category: 'medical',
    courses: 'MBBS, MD, MS',
    address: 'Salem',
    feeRange: '₹10,00,000 - ₹20,00,000 per year',
    accreditation: 'NMC Approved',
  },
  {
    id: 'vmkv_medical',
    name: "Vinayaka Mission's Kirupananda Variyar Medical College, Salem",
    type: 'private',
    category: 'medical',
    courses: 'MBBS, MD, MS',
    address: 'Salem',
    feeRange: '₹10,00,000 - ₹20,00,000 per year',
    accreditation: 'NMC Approved',
  },
  {
    id: 'vms_dental',
    name: "Vinayaka Mission's Sankarachariyar Dental College, Salem",
    type: 'private',
    category: 'dental',
    courses: 'BDS, MDS',
    address: 'Salem',
    feeRange: '₹3,00,000 - ₹8,00,000 per year',
    accreditation: 'DCI Approved',
  },
];

// Coimbatore District Colleges - Complete List
export const COIMBATORE_FEATURED_COLLEGES: College[] = [
  // ============================================
  // 1. GOVERNMENT & AIDED - Engineering
  // ============================================
  {
    id: 'gct_coimbatore',
    name: 'Government College of Technology (GCT), Coimbatore',
    type: 'government',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil, IT, Production), M.E/M.Tech',
    address: 'Thadagam Road, Coimbatore',
    feeRange: '₹10,000 - ₹30,000 per year',
    accreditation: 'Autonomous, NBA Accredited, NAAC A+',
  },
  {
    id: 'psg_tech',
    name: 'PSG College of Technology, Coimbatore',
    type: 'government-aided',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil, Robotics, AI&DS), M.E/M.Tech, MBA, MCA',
    address: 'Peelamedu, Coimbatore',
    feeRange: '₹50,000 - ₹1,50,000 per year',
    accreditation: 'Autonomous, NBA Accredited, NAAC A++',
  },
  {
    id: 'cit_coimbatore',
    name: 'Coimbatore Institute of Technology (CIT), Coimbatore',
    type: 'government-aided',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil), M.E/M.Tech, MBA',
    address: 'Peelamedu, Coimbatore',
    feeRange: '₹50,000 - ₹1,40,000 per year',
    accreditation: 'Autonomous, NBA Accredited, NAAC A+',
  },

  // ============================================
  // 1. GOVERNMENT & AIDED - Arts & Science
  // ============================================
  {
    id: 'govt_arts_coimbatore',
    name: 'Government Arts College (Autonomous), Coimbatore',
    type: 'government',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc, M.Com, M.Phil, Ph.D',
    address: 'Arts College Road, Coimbatore',
    feeRange: '₹1,000 - ₹5,000 per year',
    accreditation: 'Autonomous, NAAC Accredited',
  },
  {
    id: 'govt_arts_women_puliakulam',
    name: 'Government Arts and Science College for Women, Puliakulam',
    type: 'government',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc',
    address: 'Puliakulam, Coimbatore',
    feeRange: '₹1,000 - ₹5,000 per year',
  },
  {
    id: 'govt_arts_mettupalayam',
    name: 'Government Arts and Science College, Mettupalayam',
    type: 'government',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com',
    address: 'Mettupalayam, Coimbatore',
    feeRange: '₹1,000 - ₹5,000 per year',
  },
  {
    id: 'govt_arts_thondamuthur',
    name: 'Government Arts and Science College, Thondamuthur',
    type: 'government',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com',
    address: 'Thondamuthur, Coimbatore',
    feeRange: '₹1,000 - ₹5,000 per year',
  },
  {
    id: 'govt_arts_pollachi',
    name: 'Government Arts and Science College, Pollachi',
    type: 'government',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com',
    address: 'Pollachi, Coimbatore',
    feeRange: '₹1,000 - ₹5,000 per year',
  },
  {
    id: 'govt_arts_valparai',
    name: 'Government Arts and Science College, Valparai',
    type: 'government',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com',
    address: 'Valparai, Coimbatore',
    feeRange: '₹1,000 - ₹5,000 per year',
  },
  {
    id: 'psg_arts_science',
    name: 'PSG College of Arts & Science, Coimbatore',
    type: 'government-aided',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com, MBA, MCA',
    address: 'Peelamedu, Coimbatore',
    feeRange: '₹30,000 - ₹80,000 per year',
    accreditation: 'Autonomous, NAAC A++',
  },
  {
    id: 'psgr_krishnammal',
    name: 'PSGR Krishnammal College for Women, Coimbatore',
    type: 'government-aided',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com, MBA',
    address: 'Peelamedu, Coimbatore',
    feeRange: '₹25,000 - ₹70,000 per year',
    accreditation: 'Autonomous, NAAC A++',
  },
  {
    id: 'nirmala_women',
    name: 'Nirmala College for Women, Coimbatore',
    type: 'government-aided',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com',
    address: 'Redfields, Coimbatore',
    feeRange: '₹20,000 - ₹60,000 per year',
    accreditation: 'Autonomous, NAAC A+',
  },
  {
    id: 'srmv_college',
    name: 'Sri Ramakrishna Mission Vidyalaya College of Arts and Science (SRMV), Coimbatore',
    type: 'government-aided',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc, M.Com',
    address: 'Periyanaickenpalayam, Coimbatore',
    feeRange: '₹15,000 - ₹50,000 per year',
  },

  // ============================================
  // 1. GOVERNMENT & AIDED - Medical & Specialized
  // ============================================
  {
    id: 'cmc_coimbatore',
    name: 'Coimbatore Medical College (CMC), Coimbatore',
    type: 'government',
    category: 'medical',
    courses: 'MBBS, MD, MS, DM, MCh',
    address: 'Peelamedu, Coimbatore',
    feeRange: '₹15,000 - ₹30,000 per year',
    accreditation: 'NMC Approved',
  },
  {
    id: 'govt_medical_esic',
    name: 'Government Medical College & ESIC Hospital, Coimbatore',
    type: 'government',
    category: 'medical',
    courses: 'MBBS',
    address: 'Singanallur, Coimbatore',
    feeRange: '₹15,000 - ₹25,000 per year',
    accreditation: 'NMC Approved',
  },
  {
    id: 'govt_law_coimbatore',
    name: 'Government Law College, Coimbatore',
    type: 'government',
    category: 'law',
    courses: 'B.A. LL.B (5 Year), LL.B (3 Year), LL.M',
    address: 'Maruthamalai Road, Coimbatore',
    feeRange: '₹2,000 - ₹10,000 per year',
    accreditation: 'Bar Council of India Approved',
  },
  {
    id: 'tnau_coimbatore',
    name: 'Tamil Nadu Agricultural University (TNAU), Coimbatore',
    type: 'government',
    category: 'agricultural',
    courses: 'B.Sc Agriculture, B.Tech Agricultural Engineering, M.Sc, Ph.D',
    address: 'Lawley Road, Coimbatore',
    feeRange: '₹10,000 - ₹30,000 per year',
    accreditation: 'ICAR Accredited, State University',
  },
  {
    id: 'fcri_mettupalayam',
    name: 'Forest College and Research Institute, Mettupalayam',
    type: 'government',
    category: 'agricultural',
    courses: 'B.Sc Forestry, M.Sc Forestry, Ph.D',
    address: 'Mettupalayam, Coimbatore',
    feeRange: '₹10,000 - ₹25,000 per year',
    accreditation: 'TNAU Affiliated',
  },

  // ============================================
  // 2. AUTONOMOUS ENGINEERING COLLEGES (Private)
  // ============================================
  {
    id: 'kct_coimbatore',
    name: 'Kumaraguru College of Technology (KCT), Coimbatore',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil, AI&DS), M.E/M.Tech, MBA',
    address: 'Saravanampatti, Coimbatore',
    feeRange: '₹1,00,000 - ₹1,80,000 per year',
    accreditation: 'NBA Accredited, NAAC A++',
  },
  {
    id: 'skcet_coimbatore',
    name: 'Sri Krishna College of Engineering and Technology (SKCET), Coimbatore',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil, AI&ML), M.E/M.Tech',
    address: 'Kuniamuthur, Coimbatore',
    feeRange: '₹90,000 - ₹1,60,000 per year',
    accreditation: 'NBA Accredited, NAAC A+',
  },
  {
    id: 'kpriet_coimbatore',
    name: 'KPR Institute of Engineering and Technology (KPRIET), Coimbatore',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Arasur, Coimbatore',
    feeRange: '₹80,000 - ₹1,50,000 per year',
    accreditation: 'NBA Accredited, NAAC A+',
  },
  {
    id: 'srec_coimbatore',
    name: 'Sri Ramakrishna Engineering College (SREC), Coimbatore',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil), M.E/M.Tech, MBA',
    address: 'Vattamalaipalayam, Coimbatore',
    feeRange: '₹80,000 - ₹1,50,000 per year',
    accreditation: 'NBA Accredited, NAAC A+',
  },
  {
    id: 'hicet_coimbatore',
    name: 'Hindusthan College of Engineering and Technology (HiCET), Coimbatore',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Othakkalmandapam, Coimbatore',
    feeRange: '₹70,000 - ₹1,40,000 per year',
    accreditation: 'NAAC A, AICTE Approved',
  },
  {
    id: 'karpagam_engineering',
    name: 'Karpagam College of Engineering, Coimbatore',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Eachanari, Coimbatore',
    feeRange: '₹70,000 - ₹1,40,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'sri_eshwar_engineering',
    name: 'Sri Eshwar College of Engineering, Coimbatore',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil, AI&ML), M.E/M.Tech',
    address: 'Kinathukadavu, Coimbatore',
    feeRange: '₹80,000 - ₹1,50,000 per year',
    accreditation: 'NBA Accredited, NAAC A+',
  },
  {
    id: 'sns_tech',
    name: 'SNS College of Technology, Coimbatore',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Saravanampatti, Coimbatore',
    feeRange: '₹70,000 - ₹1,40,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'ngp_tech',
    name: 'Dr. N.G.P. Institute of Technology, Coimbatore',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil, AI&DS), M.E/M.Tech',
    address: 'Kalapatti, Coimbatore',
    feeRange: '₹80,000 - ₹1,50,000 per year',
    accreditation: 'NBA Accredited, NAAC A+',
  },
  {
    id: 'mcet_pollachi',
    name: 'Dr. Mahalingam College of Engineering and Technology (MCET), Pollachi',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, IT, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Pollachi, Coimbatore',
    feeRange: '₹70,000 - ₹1,40,000 per year',
    accreditation: 'NBA Accredited, NAAC A',
  },
  {
    id: 'akshaya_engineering',
    name: 'Akshaya College of Engineering and Technology, Coimbatore',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil)',
    address: 'Kinathukadavu, Coimbatore',
    feeRange: '₹60,000 - ₹1,20,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'rathinam_tech',
    name: 'Rathinam Technical Campus, Coimbatore',
    type: 'autonomous',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Eachanari, Coimbatore',
    feeRange: '₹60,000 - ₹1,20,000 per year',
    accreditation: 'AICTE Approved',
  },

  // ============================================
  // 3. AUTONOMOUS ARTS & SCIENCE COLLEGES (Private)
  // ============================================
  {
    id: 'skasc_coimbatore',
    name: 'Sri Krishna Arts and Science College (SKASC), Coimbatore',
    type: 'autonomous',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com, MBA, MCA',
    address: 'Kuniamuthur, Coimbatore',
    feeRange: '₹40,000 - ₹1,00,000 per year',
    accreditation: 'NAAC A++',
  },
  {
    id: 'kongunadu_arts_science',
    name: 'Kongunadu Arts and Science College, Coimbatore',
    type: 'autonomous',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com, MBA',
    address: 'G.N. Mills, Coimbatore',
    feeRange: '₹30,000 - ₹80,000 per year',
    accreditation: 'NAAC A+',
  },
  {
    id: 'ngp_arts_science',
    name: 'Dr. N.G.P. Arts and Science College, Coimbatore',
    type: 'autonomous',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com',
    address: 'Kalapatti, Coimbatore',
    feeRange: '₹35,000 - ₹90,000 per year',
    accreditation: 'NAAC A+',
  },
  {
    id: 'srcas_coimbatore',
    name: 'Sri Ramakrishna College of Arts and Science (SRCAS), Coimbatore',
    type: 'autonomous',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com, MBA',
    address: 'Nava India, Coimbatore',
    feeRange: '₹30,000 - ₹80,000 per year',
    accreditation: 'NAAC A+',
  },
  {
    id: 'hindusthan_arts_science',
    name: 'Hindusthan College of Arts & Science, Coimbatore',
    type: 'autonomous',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com',
    address: 'Nava India, Coimbatore',
    feeRange: '₹25,000 - ₹70,000 per year',
    accreditation: 'NAAC A',
  },
  {
    id: 'sns_rajalakshmi',
    name: 'Dr. SNS Rajalakshmi College of Arts and Science, Coimbatore',
    type: 'autonomous',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com',
    address: 'Chinnavedampatti, Coimbatore',
    feeRange: '₹25,000 - ₹70,000 per year',
  },
  {
    id: 'rathinam_arts_science',
    name: 'Rathinam College of Arts and Science, Coimbatore',
    type: 'autonomous',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com',
    address: 'Eachanari, Coimbatore',
    feeRange: '₹25,000 - ₹70,000 per year',
  },
  {
    id: 'rvs_arts_science',
    name: 'RVS College of Arts and Science, Coimbatore',
    type: 'autonomous',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com',
    address: 'Sulur, Coimbatore',
    feeRange: '₹25,000 - ₹70,000 per year',
  },
  {
    id: 'cms_college',
    name: 'CMS College of Science and Commerce, Coimbatore',
    type: 'autonomous',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com',
    address: 'Chinnavedampatti, Coimbatore',
    feeRange: '₹25,000 - ₹70,000 per year',
  },
  {
    id: 'nehru_arts_science',
    name: 'Nehru Arts and Science College, Coimbatore',
    type: 'autonomous',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com',
    address: 'Thirumalayampalayam, Coimbatore',
    feeRange: '₹25,000 - ₹70,000 per year',
  },

  // ============================================
  // 4. DEEMED UNIVERSITIES
  // ============================================
  {
    id: 'amrita_coimbatore',
    name: 'Amrita Vishwa Vidyapeetham, Coimbatore',
    type: 'private',
    category: 'engineering',
    courses: 'B.Tech, M.Tech, MBA, MCA, B.Sc, M.Sc, Ph.D (Engineering, Arts, Science, Management)',
    address: 'Ettimadai, Coimbatore',
    feeRange: '₹1,50,000 - ₹3,00,000 per year',
    accreditation: 'NAAC A++, Deemed University',
  },
  {
    id: 'karunya_coimbatore',
    name: 'Karunya Institute of Technology and Sciences, Coimbatore',
    type: 'private',
    category: 'engineering',
    courses: 'B.Tech, M.Tech, MBA, MCA, B.Sc, M.Sc, Ph.D',
    address: 'Karunya Nagar, Coimbatore',
    feeRange: '₹1,20,000 - ₹2,50,000 per year',
    accreditation: 'NAAC A+, Deemed University',
  },
  {
    id: 'avinashilingam_coimbatore',
    name: 'Avinashilingam Institute for Home Science and Higher Education for Women, Coimbatore',
    type: 'private',
    category: 'arts_science',
    courses: 'B.Sc, M.Sc, B.A, M.A, B.Ed, M.Ed, Ph.D (Home Science, Arts, Education)',
    address: 'Saibaba Colony, Coimbatore',
    feeRange: '₹40,000 - ₹1,00,000 per year',
    accreditation: 'NAAC A+, Deemed University (Women)',
  },
  {
    id: 'karpagam_academy',
    name: 'Karpagam Academy of Higher Education, Coimbatore',
    type: 'private',
    category: 'engineering',
    courses: 'B.Tech, M.Tech, MBA, MCA, B.Sc, M.Sc, Ph.D',
    address: 'Eachanari, Coimbatore',
    feeRange: '₹80,000 - ₹1,80,000 per year',
    accreditation: 'NAAC A, Deemed University',
  },

  // ============================================
  // 5. MANAGEMENT & MBA SPECIALISTS
  // ============================================
  {
    id: 'psgim_coimbatore',
    name: 'PSG Institute of Management (PSGIM), Coimbatore',
    type: 'government-aided',
    category: 'management',
    courses: 'MBA, PGDM, Executive MBA',
    address: 'Peelamedu, Coimbatore',
    feeRange: '₹2,00,000 - ₹4,00,000 per year',
    accreditation: 'AICTE Approved, AACSB Accredited',
  },
  {
    id: 'amrita_business',
    name: 'Amrita School of Business (ASB), Coimbatore',
    type: 'private',
    category: 'management',
    courses: 'MBA, PGDM, Ph.D',
    address: 'Ettimadai, Coimbatore',
    feeRange: '₹3,00,000 - ₹5,00,000 per year',
    accreditation: 'AICTE Approved, AACSB Accredited',
  },
  {
    id: 'jsb_coimbatore',
    name: 'Jansons School of Business (JSB), Coimbatore',
    type: 'private',
    category: 'management',
    courses: 'PGDM, MBA',
    address: 'Karumathampatti, Coimbatore',
    feeRange: '₹2,50,000 - ₹4,50,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'kct_business',
    name: 'KCT Business School, Coimbatore',
    type: 'private',
    category: 'management',
    courses: 'MBA',
    address: 'Saravanampatti, Coimbatore',
    feeRange: '₹1,50,000 - ₹3,00,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'grgsms_coimbatore',
    name: 'GRG School of Management Studies (GRGSMS), Coimbatore',
    type: 'private',
    category: 'management',
    courses: 'PGDM, MBA, Ph.D',
    address: 'Peelamedu, Coimbatore',
    feeRange: '₹2,00,000 - ₹4,00,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'firebird_coimbatore',
    name: 'Firebird Institute of Research in Management, Coimbatore',
    type: 'private',
    category: 'management',
    courses: 'PGDM',
    address: 'Chettipalayam, Coimbatore',
    feeRange: '₹2,00,000 - ₹3,50,000 per year',
    accreditation: 'AICTE Approved',
  },

  // ============================================
  // 6. MEDICAL, DENTAL & ALLIED HEALTH
  // ============================================
  {
    id: 'psg_imsr',
    name: 'PSG Institute of Medical Sciences and Research (PSG IMSR), Coimbatore',
    type: 'private',
    category: 'medical',
    courses: 'MBBS, MD, MS, DM, MCh',
    address: 'Peelamedu, Coimbatore',
    feeRange: '₹10,00,000 - ₹25,00,000 per year',
    accreditation: 'NMC Approved, NAAC A',
  },
  {
    id: 'kmch_coimbatore',
    name: 'KMCH Institute of Health Sciences and Research, Coimbatore',
    type: 'private',
    category: 'medical',
    courses: 'MBBS, MD, MS, B.Sc Nursing, Allied Health Sciences',
    address: 'Avanashi Road, Coimbatore',
    feeRange: '₹10,00,000 - ₹25,00,000 per year',
    accreditation: 'NMC Approved',
  },
  {
    id: 'karpagam_medical',
    name: 'Karpagam Faculty of Medical Sciences and Research, Coimbatore',
    type: 'private',
    category: 'medical',
    courses: 'MBBS, MD, MS',
    address: 'Othakkalmandapam, Coimbatore',
    feeRange: '₹10,00,000 - ₹20,00,000 per year',
    accreditation: 'NMC Approved',
  },
  {
    id: 'sri_ramakrishna_dental',
    name: 'Sri Ramakrishna Dental College and Hospital, Coimbatore',
    type: 'private',
    category: 'dental',
    courses: 'BDS, MDS',
    address: 'Nava India, Coimbatore',
    feeRange: '₹3,00,000 - ₹8,00,000 per year',
    accreditation: 'DCI Approved',
  },
  {
    id: 'rvs_dental',
    name: 'RVS Dental College and Hospital, Coimbatore',
    type: 'private',
    category: 'dental',
    courses: 'BDS, MDS',
    address: 'Kannampalayam, Coimbatore',
    feeRange: '₹3,00,000 - ₹8,00,000 per year',
    accreditation: 'DCI Approved',
  },
  {
    id: 'royal_nursing',
    name: 'Royal College of Nursing, Coimbatore',
    type: 'private',
    category: 'nursing',
    courses: 'B.Sc Nursing, M.Sc Nursing, GNM',
    address: 'Marappalam, Coimbatore',
    feeRange: '₹50,000 - ₹1,50,000 per year',
    accreditation: 'INC Approved',
  },

  // ============================================
  // 7. AGRICULTURE & VETERINARY
  // ============================================
  {
    id: 'acri_tnau',
    name: 'Agricultural College and Research Institute (AC&RI), TNAU Campus',
    type: 'government',
    category: 'agricultural',
    courses: 'B.Sc Agriculture, M.Sc Agriculture, Ph.D',
    address: 'TNAU Campus, Coimbatore',
    feeRange: '₹10,000 - ₹25,000 per year',
    accreditation: 'TNAU Constituent, ICAR Accredited',
  },
  {
    id: 'hcri_coimbatore',
    name: 'Horticultural College and Research Institute, Coimbatore',
    type: 'government',
    category: 'agricultural',
    courses: 'B.Sc Horticulture, M.Sc Horticulture, Ph.D',
    address: 'TNAU Campus, Coimbatore',
    feeRange: '₹10,000 - ₹25,000 per year',
    accreditation: 'TNAU Constituent',
  },
  {
    id: 'aecri_coimbatore',
    name: 'Agricultural Engineering College and Research Institute (AEC&RI), Coimbatore',
    type: 'government',
    category: 'agricultural',
    courses: 'B.Tech Agricultural Engineering, M.Tech, Ph.D',
    address: 'TNAU Campus, Coimbatore',
    feeRange: '₹10,000 - ₹25,000 per year',
    accreditation: 'TNAU Constituent',
  },
  {
    id: 'vanavarayar_agriculture',
    name: 'Vanavarayar Institute of Agriculture, Pollachi',
    type: 'private',
    category: 'agricultural',
    courses: 'B.Sc Agriculture',
    address: 'Pollachi, Coimbatore',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'TNAU Affiliated',
  },

  // ============================================
  // 8. PRIVATE ENGINEERING COLLEGES (Affiliated)
  // ============================================
  {
    id: 'psg_itech',
    name: 'PSG Institute of Technology and Applied Research (PSG iTech), Coimbatore',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Neelambur, Coimbatore',
    feeRange: '₹70,000 - ₹1,40,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'skct_coimbatore',
    name: 'Sri Krishna College of Technology (SKCT), Coimbatore',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Kovaipudur, Coimbatore',
    feeRange: '₹70,000 - ₹1,40,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'kit_coimbatore',
    name: 'Kalaignar Karunanidhi Institute of Technology (KIT), Coimbatore',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil)',
    address: 'Kannampalayam, Coimbatore',
    feeRange: '₹60,000 - ₹1,20,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'niet_coimbatore',
    name: 'Nehru Institute of Engineering and Technology (NIET), Coimbatore',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Thirumalayampalayam, Coimbatore',
    feeRange: '₹60,000 - ₹1,20,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'uit_coimbatore',
    name: 'United Institute of Technology (UIT), Coimbatore',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil)',
    address: 'Periyanaickenpalayam, Coimbatore',
    feeRange: '₹55,000 - ₹1,10,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'jct_engineering',
    name: 'JCT College of Engineering and Technology, Coimbatore',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil)',
    address: 'Pichanur, Coimbatore',
    feeRange: '₹55,000 - ₹1,10,000 per year',
    accreditation: 'AICTE Approved',
  },
];

// Tirupur District Colleges - Complete List
export const TIRUPUR_FEATURED_COLLEGES: College[] = [
  // ============================================
  // 1. GOVERNMENT COLLEGES
  // ============================================
  {
    id: 'chikkanna_govt_arts',
    name: 'Chikkanna Government Arts College, Tirupur North',
    type: 'government',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc, M.Com',
    address: 'Tirupur North, Tirupur',
    feeRange: '₹1,000 - ₹5,000 per year',
  },
  {
    id: 'lrg_govt_arts_women',
    name: 'L.R.G. Government Arts College for Women, Tirupur',
    type: 'government',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, M.A, M.Sc',
    address: 'Tirupur',
    feeRange: '₹1,000 - ₹5,000 per year',
  },
  {
    id: 'govt_medical_tirupur',
    name: 'Government Medical College, Tirupur',
    type: 'government',
    category: 'medical',
    courses: 'MBBS',
    address: 'Velliangadu, Tirupur',
    feeRange: '₹15,000 - ₹25,000 per year',
    accreditation: 'NMC Approved',
  },
  {
    id: 'govt_arts_kangayam',
    name: 'Government Arts and Science College, Kangayam',
    type: 'government',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com',
    address: 'Kangayam, Tirupur',
    feeRange: '₹1,000 - ₹5,000 per year',
  },
  {
    id: 'govt_arts_udumalpet',
    name: 'Government Arts and Science College, Udumalpet',
    type: 'government',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com',
    address: 'Udumalpet, Tirupur',
    feeRange: '₹1,000 - ₹5,000 per year',
  },
  {
    id: 'govt_polytechnic_dharapuram',
    name: 'Government Polytechnic College, Dharapuram',
    type: 'government',
    category: 'polytechnic',
    courses: 'Diploma in Mechanical, Civil, ECE, EEE, Computer',
    address: 'Dharapuram, Tirupur',
    feeRange: '₹2,000 - ₹5,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'govt_iti_tirupur',
    name: 'Government ITI, Tirupur & Dharapuram',
    type: 'government',
    category: 'polytechnic',
    courses: 'ITI Trades - Fitter, Turner, Electrician, Mechanic',
    address: 'Tirupur & Dharapuram',
    feeRange: '₹1,000 - ₹3,000 per year',
  },

  // ============================================
  // 2. ENGINEERING COLLEGES (Private)
  // ============================================
  {
    id: 'angel_engineering',
    name: 'Angel College of Engineering and Technology, Tirupur',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Tirupur',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'jai_shriram_engineering',
    name: 'Jai Shriram Engineering College, Avinashipalayam',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil)',
    address: 'Avinashipalayam, Tirupur',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'sasurie_engineering',
    name: 'Sasurie College of Engineering, Vijayamangalam',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil), M.E/M.Tech',
    address: 'Vijayamangalam, Tirupur',
    feeRange: '₹50,000 - ₹1,00,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'cheran_tech',
    name: 'Cheran College of Technology, Kangayam',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil)',
    address: 'Kangayam, Tirupur',
    feeRange: '₹45,000 - ₹90,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'jairupaa_engineering',
    name: 'Jairupaa College of Engineering, Tirupur',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech)',
    address: 'Tirupur',
    feeRange: '₹45,000 - ₹90,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'nallini_engineering',
    name: 'Dr. Nallini Institute of Engineering and Technology, Tirupur',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech, Civil)',
    address: 'Dharapuram Road, Tirupur',
    feeRange: '₹45,000 - ₹90,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'scad_tech',
    name: 'SCAD Institute of Technology, Palladam',
    type: 'private',
    category: 'engineering',
    courses: 'B.E/B.Tech (CSE, ECE, EEE, Mech)',
    address: 'Palladam, Tirupur',
    feeRange: '₹45,000 - ₹90,000 per year',
    accreditation: 'AICTE Approved',
  },

  // ============================================
  // 3. ARTS & SCIENCE COLLEGES (Private)
  // ============================================
  {
    id: 'nifttea_tirupur',
    name: 'NIFT-TEA College of Knitwear Fashion, Tirupur',
    type: 'private',
    category: 'arts_science',
    courses: 'B.Sc Fashion Design, Textile Design, Knitwear Technology',
    address: 'Mudalipalayam, Tirupur',
    feeRange: '₹50,000 - ₹1,50,000 per year',
    accreditation: 'Pioneer in Textile Education',
  },
  {
    id: 'parks_college',
    name: 'Parks College (Autonomous), Tirupur',
    type: 'autonomous',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA, M.A, M.Sc, M.Com, MBA',
    address: 'Tirupur',
    feeRange: '₹25,000 - ₹70,000 per year',
    accreditation: 'Autonomous',
  },
  {
    id: 'avp_arts_science',
    name: 'AVP College of Arts and Science, Chettipalayam',
    type: 'private',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA',
    address: 'Chettipalayam, Tirupur',
    feeRange: '₹20,000 - ₹50,000 per year',
  },
  {
    id: 'tirupur_kumaran_women',
    name: 'Tirupur Kumaran College for Women, Tirupur',
    type: 'private',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA',
    address: 'Tirupur',
    feeRange: '₹20,000 - ₹50,000 per year',
  },
  {
    id: 'st_josephs_women_tirupur',
    name: "St. Joseph's College for Women, Tirupur",
    type: 'private',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA',
    address: 'Tirupur',
    feeRange: '₹18,000 - ₹45,000 per year',
  },
  {
    id: 'cheran_arts_science',
    name: 'Cheran College of Arts and Science, Kangayam',
    type: 'private',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA, BBA',
    address: 'Kangayam, Tirupur',
    feeRange: '₹18,000 - ₹45,000 per year',
  },
  {
    id: 'maharani_arts_dharapuram',
    name: 'Maharani Arts and Science College, Dharapuram',
    type: 'private',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA',
    address: 'Dharapuram, Tirupur',
    feeRange: '₹18,000 - ₹45,000 per year',
  },
  {
    id: 'vidyasagar_arts_udumalpet',
    name: 'Vidyasagar College of Arts and Science, Udumalpet',
    type: 'private',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA',
    address: 'Udumalpet, Tirupur',
    feeRange: '₹18,000 - ₹45,000 per year',
  },
  {
    id: 'bishop_arulzadah_dharapuram',
    name: 'Bishop Arulzadah Arts and Science College, Dharapuram',
    type: 'private',
    category: 'arts_science',
    courses: 'B.A, B.Sc, B.Com, BCA',
    address: 'Dharapuram, Tirupur',
    feeRange: '₹18,000 - ₹45,000 per year',
  },

  // ============================================
  // 4. MEDICAL & HEALTH SCIENCES
  // ============================================
  {
    id: 'revathi_nursing',
    name: 'Revathi College of Nursing, Tirupur',
    type: 'private',
    category: 'nursing',
    courses: 'B.Sc Nursing, GNM, ANM',
    address: 'Tirupur',
    feeRange: '₹40,000 - ₹1,00,000 per year',
    accreditation: 'INC Approved',
  },
  {
    id: 'sara_nursing',
    name: 'Sara Nursing College, Dharapuram',
    type: 'private',
    category: 'nursing',
    courses: 'B.Sc Nursing, GNM',
    address: 'Dharapuram, Tirupur',
    feeRange: '₹40,000 - ₹1,00,000 per year',
    accreditation: 'INC Approved',
  },
  {
    id: 'revathi_physio',
    name: 'Revathi Institute of Physiotherapy, Tirupur',
    type: 'private',
    category: 'allied_health',
    courses: 'BPT, MPT',
    address: 'Tirupur',
    feeRange: '₹80,000 - ₹1,50,000 per year',
  },
  {
    id: 'priya_paramedical',
    name: 'Priya Institute of Paramedical, Udumalpet',
    type: 'private',
    category: 'allied_health',
    courses: 'DMLT, B.Sc MLT, Allied Health Courses',
    address: 'Udumalpet, Tirupur',
    feeRange: '₹30,000 - ₹80,000 per year',
  },

  // ============================================
  // 5. SPECIALIZED & POLYTECHNIC COLLEGES
  // ============================================
  {
    id: 'senthur_polytechnic',
    name: 'Senthur Polytechnic College, Tirupur',
    type: 'private',
    category: 'polytechnic',
    courses: 'Diploma in Mechanical, Civil, ECE, EEE, Computer',
    address: 'Tirupur',
    feeRange: '₹15,000 - ₹40,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'sift_polytechnic',
    name: 'Sift Polytechnic College, Tirupur',
    type: 'private',
    category: 'polytechnic',
    courses: 'Diploma in Mechanical, Civil, ECE, EEE',
    address: 'Tirupur',
    feeRange: '₹15,000 - ₹40,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'maharani_polytechnic',
    name: 'Maharani Polytechnic College, Dharapuram',
    type: 'private',
    category: 'polytechnic',
    courses: 'Diploma in Mechanical, Civil, ECE, EEE',
    address: 'Dharapuram, Tirupur',
    feeRange: '₹15,000 - ₹40,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'nv_polytechnic',
    name: 'NV Polytechnic College, Udumalpet',
    type: 'private',
    category: 'polytechnic',
    courses: 'Diploma in Mechanical, Civil, ECE, EEE',
    address: 'Udumalpet, Tirupur',
    feeRange: '₹15,000 - ₹40,000 per year',
    accreditation: 'AICTE Approved',
  },
  {
    id: 'rudhraveni_polytechnic',
    name: 'Rudhraveni Muthuswamy Polytechnic College, Udumalpet',
    type: 'private',
    category: 'polytechnic',
    courses: 'Diploma in Mechanical, Civil, ECE, EEE',
    address: 'Udumalpet, Tirupur',
    feeRange: '₹15,000 - ₹40,000 per year',
    accreditation: 'AICTE Approved',
  },
];
