import { EntranceExam, CategoryInfo } from './types';

export const examCategories: CategoryInfo[] = [
  {
    id: 'engineering',
    label: 'Engineering',
    tamilLabel: 'பொறியியல்',
    icon: '⚙️',
    color: 'text-[#1976D2]',
    bgColor: 'bg-[#E3F2FD]',
    borderColor: 'border-[#1976D2]',
  },
  {
    id: 'medical',
    label: 'Medical & Health',
    tamilLabel: 'மருத்துவம்',
    icon: '🏥',
    color: 'text-[#D32F2F]',
    bgColor: 'bg-[#FFEBEE]',
    borderColor: 'border-[#D32F2F]',
  },
  {
    id: 'management',
    label: 'Management & Law',
    tamilLabel: 'மேலாண்மை & சட்டம்',
    icon: '💼',
    color: 'text-[#7B1FA2]',
    bgColor: 'bg-[#F3E5F5]',
    borderColor: 'border-[#7B1FA2]',
  },
  {
    id: 'agriculture',
    label: 'Agriculture',
    tamilLabel: 'வேளாண்மை',
    icon: '🌾',
    color: 'text-[#2E7D32]',
    bgColor: 'bg-[#E8F5E9]',
    borderColor: 'border-[#2E7D32]',
  },
  {
    id: 'design',
    label: 'Design & Arts',
    tamilLabel: 'வடிவமைப்பு',
    icon: '🎨',
    color: 'text-[#F59E0B]',
    bgColor: 'bg-[#FFF8E1]',
    borderColor: 'border-[#F59E0B]',
  },
];

export const entranceExams: EntranceExam[] = [
  // ============ ENGINEERING EXAMS ============
  {
    id: 'tnea',
    name: 'TNEA',
    tamilName: 'தமிழ்நாடு பொறியியல் சேர்க்கை',
    fullForm: 'Tamil Nadu Engineering Admissions',
    conductingBody: 'Anna University, Chennai',
    examMode: 'Merit Based (No Exam)',
    duration: 'N/A - Based on 12th marks',
    syllabus: [
      'No entrance exam — Merit based on 12th HSC marks',
      'TNEA Score = Physics×2 + Chemistry×1 + Maths×1 = out of 400',
      'Admissions via online counselling based on rank list',
    ],
    eligibility: [
      '12th HSC passed with PCM/PCB',
      'Min 50% (General), 45% (OBC), 40% (SC/ST)',
      'TN domicile or studied in TN',
    ],
    tnEligibility: 'Must be Tamil Nadu domicile or have studied in TN for 7+ years',
    importantDates: {
      registration: 'May 2026',
      examDate: 'N/A (Merit based)',
      resultDate: 'July 2026',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Anna University CEG, Chennai',
      'Anna University MIT, Chennai',
      'GCT Coimbatore',
      'PSG Tech, Coimbatore',
      'TCE Madurai',
      '455+ TN Engineering Colleges, 1.34 Lakh+ Seats',
    ],
    officialWebsite: 'https://www.tneaonline.org',
    category: 'engineering',
    hasJKKN: true,
    jkknColleges: [],
  },
  {
    id: 'jee-main',
    name: 'JEE Main',
    tamilName: 'ஜேஇஇ மெயின்',
    fullForm: 'Joint Entrance Examination Main',
    conductingBody: 'National Testing Agency (NTA)',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 hours',
    syllabus: [
      'Physics - 30 Questions (20 MCQ + 10 Numerical, attempt 25)',
      'Chemistry - 30 Questions (20 MCQ + 10 Numerical, attempt 25)',
      'Mathematics - 30 Questions (20 MCQ + 10 Numerical, attempt 25)',
      'Total: 90 Questions, 75 attempted | 300 Marks | 3 hrs',
      'MCQ: +4/-1 | Numerical: +4/0 (no negative)',
    ],
    eligibility: [
      '12th pass with PCM',
      '75% in 12th or top 20 percentile (65% for SC/ST)',
      '2 sessions per year (Jan & April)',
    ],
    tnEligibility: 'TN students can apply for NITs (15% All India + 85% State quota at NIT Trichy)',
    importantDates: {
      registration: 'November 2024',
      examDate: 'January & April 2026',
      resultDate: 'February & May 2026',
    },
    applicationFee: {
      general: '₹1,000',
      scst: '₹500',
    },
    tnCollegesAccepting: [
      'NIT Trichy (Top NIT)',
      'IIIT Tiruchirappalli',
      'IIT Madras (via JEE Advanced)',
      'Other NITs across India',
    ],
    officialWebsite: 'https://jeemain.nta.nic.in',
    category: 'engineering',
  },
  {
    id: 'jee-advanced',
    name: 'JEE Advanced',
    tamilName: 'ஜேஇஇ அட்வான்ஸ்ட்',
    fullForm: 'Joint Entrance Examination Advanced',
    conductingBody: 'IIT Madras (2026)',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 hours each (Paper 1 & 2)',
    syllabus: [
      'Paper 1 (3 hrs): Physics + Chemistry + Mathematics',
      'Paper 2 (3 hrs): Physics + Chemistry + Mathematics',
      'Each paper: ~54 Questions | ~360 Marks total',
      'Question types: MCQ (single/multi correct), Numerical, Matching',
      'Topics: Class 11-12 NCERT + deeper conceptual problems',
      'Partial marking for multi-correct MCQs',
    ],
    eligibility: [
      'Top 2,50,000 in JEE Main',
      'Age: Born after Oct 1, 2001 (approx)',
      'Maximum 2 consecutive attempts',
    ],
    tnEligibility: 'TN students eligible for IIT Madras (Chennai) - Premier institute in TN',
    importantDates: {
      registration: 'April 2026',
      examDate: 'May 2026',
      resultDate: 'June 2026',
    },
    applicationFee: {
      general: '₹2,800',
      scst: '₹1,400',
    },
    tnCollegesAccepting: [
      'IIT Madras, Chennai (#1 in India)',
      '23 IITs across India',
    ],
    officialWebsite: 'https://jeeadv.ac.in',
    category: 'engineering',
  },
  {
    id: 'viteee',
    name: 'VITEEE',
    tamilName: 'விஐடிஇஇஇ',
    fullForm: 'VIT Engineering Entrance Examination',
    conductingBody: 'VIT University, Vellore (TN)',
    examMode: 'Computer Based Test (CBT)',
    duration: '2 hours 30 minutes',
    syllabus: [
      'Physics - 35 Questions (140 marks)',
      'Chemistry - 35 Questions (140 marks)',
      'Maths/Biology - 40 Questions (160 marks)',
      'Aptitude - 10 Questions (40 marks)',
      'English - 5 Questions (20 marks)',
      'Total: 125 MCQs | 500 Marks | +4/-1 Marking',
    ],
    eligibility: [
      '12th with PCM/PCB',
      'Minimum 60% in PCM/PCB',
      'Born after July 1, 2003',
    ],
    tnEligibility: 'VIT Vellore is located in TN - Home state advantage for TN students',
    importantDates: {
      registration: 'November 2024',
      examDate: 'April-May 2026',
      resultDate: 'May 2026',
    },
    applicationFee: {
      general: '₹1,350',
      scst: '₹1,350',
    },
    tnCollegesAccepting: [
      'VIT Vellore (Main Campus, TN)',
      'VIT Chennai Campus',
      'VIT AP, VIT Bhopal',
    ],
    officialWebsite: 'https://viteee.vit.ac.in',
    category: 'engineering',
  },
  {
    id: 'srmjeee',
    name: 'SRMJEEE',
    tamilName: 'எஸ்ஆர்எம்ஜேஇஇஇ',
    fullForm: 'SRM Joint Engineering Entrance Examination',
    conductingBody: 'SRM Institute, Chennai (TN)',
    examMode: 'Computer Based Test (CBT)',
    duration: '2 hours 30 minutes',
    syllabus: [
      'Physics - 35 Questions (35 marks)',
      'Chemistry - 35 Questions (35 marks)',
      'Maths/Biology - 40 Questions (40 marks)',
      'English & Aptitude - 20 Questions (20 marks)',
      'Total: 130 MCQs | 130 Marks | +1/0 | No Negative Marking',
    ],
    eligibility: [
      '12th with PCM/PCB',
      'Minimum 50% aggregate',
      'No age limit',
    ],
    tnEligibility: 'SRM Kattankulathur is TN based - Priority for TN students in counselling',
    importantDates: {
      registration: 'October 2024',
      examDate: 'April-May 2026',
      resultDate: 'May 2026',
    },
    applicationFee: {
      general: '₹1,200',
      scst: '₹1,200',
    },
    tnCollegesAccepting: [
      'SRM Kattankulathur (Main, TN)',
      'SRM Ramapuram, Chennai',
      'SRM Vadapalani, Chennai',
    ],
    officialWebsite: 'https://srmist.edu.in',
    category: 'engineering',
  },
  {
    id: 'bitsat',
    name: 'BITSAT',
    tamilName: 'பிட்சாட்',
    fullForm: 'BITS Admission Test',
    conductingBody: 'BITS Pilani',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 hours',
    syllabus: [
      'Physics - 30 Questions (90 marks)',
      'Chemistry - 30 Questions (90 marks)',
      'English Proficiency - 10 Questions (30 marks)',
      'Logical Reasoning - 20 Questions (60 marks)',
      'Mathematics - 40 Questions (120 marks)',
      'Total: 130 MCQs | 390 Marks | +3/-1 Marking',
      '12 bonus questions if all 130 attempted',
    ],
    eligibility: [
      '12th with PCM',
      '75% aggregate, 60% each in PCM',
      'No age limit',
    ],
    tnEligibility: 'TN students eligible - BITS centers available in Chennai for exam',
    importantDates: {
      registration: 'January 2026',
      examDate: 'May-June 2026',
      resultDate: 'July 2026',
    },
    applicationFee: {
      general: '₹4,500',
      scst: '₹4,500',
    },
    tnCollegesAccepting: [
      'BITS Pilani',
      'BITS Goa',
      'BITS Hyderabad',
    ],
    officialWebsite: 'https://www.bitsadmission.com',
    category: 'engineering',
  },
  {
    id: 'aeee',
    name: 'AEEE ⭐',
    tamilName: 'அம்ரிதா பொறியியல் நுழைவுத் தேர்வு',
    fullForm: 'Amrita Engineering Entrance Examination — TN Campus!',
    conductingBody: 'Amrita Vishwa Vidyapeetham, Coimbatore',
    examMode: 'Computer Based Test (CBT)',
    duration: '2 hours 30 minutes',
    syllabus: [
      'Physics (30 MCQ, 90 marks): Mechanics (Newton Laws, WEP, Rotational), Thermodynamics, Waves & Oscillations, Optics (Ray + Wave), Electrostatics, Current Electricity, Magnetism, EM Induction, Modern Physics (Photoelectric, Bohr model, Nuclear) — Class 11 & 12 NCERT',
      'Chemistry (30 MCQ, 90 marks): Physical (Mole Concept, Equilibrium, Thermodynamics, Electrochemistry, Kinetics), Organic (GOC, Hydrocarbons, Haloalkanes, Alcohols, Aldehydes, Amines), Inorganic (Periodic Table, p-block, d-block, Coordination, Metallurgy) — NCERT based',
      'Mathematics (40 MCQ, 120 marks — Highest weightage): Algebra (Complex Numbers, Matrices, PnC, Binomial), Calculus (Limits, Differentiation, Integration, Differential Equations), Coordinate Geometry (Straight Lines, Circles, Conics), Trigonometry, Vectors & 3D, Probability',
      'Total: 100 MCQs | 300 Marks | 2.5 Hours | +3/-1 Marking | CBT Mode',
      'For Amrita Vishwa Vidyapeetham — campuses in Coimbatore, Chennai, Bangalore, Amritapuri',
    ],
    eligibility: [
      '12th with PCM — 55% aggregate',
      '55% individually in Maths, Physics, Chemistry',
      'No age limit',
    ],
    tnEligibility: 'Amrita Coimbatore & Chennai campuses are in TN — Home state advantage for TN students!',
    importantDates: {
      registration: 'November 2025',
      examDate: 'April 2026',
      resultDate: 'May 2026',
    },
    applicationFee: {
      general: '₹1,200',
      scst: '₹1,200',
    },
    tnCollegesAccepting: [
      'Amrita Vishwa Vidyapeetham, Coimbatore (Main TN Campus)',
      'Amrita Chennai Campus',
      'Amrita Bangalore, Amritapuri (Kerala)',
    ],
    officialWebsite: 'https://www.amrita.edu/admissions/btech',
    category: 'engineering',
  },

  // ============ MEDICAL & HEALTH EXAMS ============
  {
    id: 'neet-ug',
    name: 'NEET-UG ⭐',
    tamilName: 'நீட் - மருத்துவ நுழைவுத் தேர்வு',
    fullForm: 'National Eligibility cum Entrance Test (For MBBS/BDS/AYUSH/BVSc/B.Sc Nursing)',
    conductingBody: 'National Testing Agency (NTA)',
    examMode: 'Offline OMR Based (Pen & Paper)',
    duration: '3 hrs 20 min',
    syllabus: [
      '🧬 Biology (90Q, 360 marks, 50% — MOST IMPORTANT):',
      'Botany: Diversity in Living World (Taxonomy, 5-Kingdom), Plant Kingdom (Algae–Angiosperms), Morphology & Anatomy of Plants, Cell Biology (Organelles, Mitosis, Meiosis), Plant Physiology (Photosynthesis, Respiration, Transpiration, Mineral Nutrition), Reproduction in Plants, Genetics (Mendel\'s Laws, DNA Replication, Transcription, Translation), Evolution (Darwin, Hardy-Weinberg), Biotechnology (rDNA, GM organisms, Gene therapy), Ecology (Food chains, Biodiversity, Conservation, Pollution)',
      'Zoology: Animal Kingdom (Phyla classification), Structural Org (Cockroach, Frog), Human Physiology (Digestion, Respiration, Circulation, Excretion, Locomotion, Neural & Chemical Coordination — 12-15Q!), Reproduction (Gametogenesis, Fertilization, Reproductive Health, STDs, ART), Human Genetics (Sex determination, Genetic disorders), Human Health & Disease (Immunity, AIDS, Cancer), Animal Husbandry',
      '🧪 Chemistry (45Q, 180 marks, 25%):',
      'Physical: Mole concept, Atomic structure (Bohr, Quantum nos.), States of Matter, Thermodynamics, Equilibrium, Redox, Electrochemistry, Chemical Kinetics, Solutions, Surface Chemistry',
      'Inorganic: Periodic Table trends, Chemical Bonding (VSEPR, Hybridization), s/p/d/f Block Elements, Coordination Compounds (Ligands, IUPAC, Isomerism), Hydrogen, Environmental Chemistry',
      'Organic (15-18Q — Highest in Chemistry!): IUPAC nomenclature, Hydrocarbons, Haloalkanes (SN1/SN2), Alcohols/Phenols/Ethers, Aldehydes/Ketones/Carboxylic Acids, Amines, Biomolecules, Polymers, Chemistry in Everyday Life',
      '⚛️ Physics (45Q, 180 marks, 25%):',
      'Class 11: Units & Measurements, Kinematics, Newton\'s Laws & Friction, Work-Energy-Power, Rotational Motion, Gravitation, Properties of Matter (Elasticity, Viscosity, Surface Tension), Thermodynamics, Kinetic Theory, Oscillations (SHM), Waves (Doppler)',
      'Class 12: Electrostatics (Coulomb, Gauss — 3-4Q), Current Electricity (Ohm, Kirchhoff — 4-5Q!), Magnetism (Biot-Savart, Ampere), EMI & AC (Faraday, LCR), Ray Optics (Reflection, Refraction, Lenses — 5-6Q!), Wave Optics (Interference, Diffraction), Modern Physics (Photoelectric, Bohr, Nuclear — 4-5Q!), Semiconductors, EM Waves',
      'Total: 200 Questions (attempt 180) | 720 Marks | +4/-1 | ⭐ TAMIL Language Available',
      '📚 Strategy: NCERT Biology line-by-line 4-5 times > NCERT Chemistry (every example & footnote) > Physics numericals daily',
    ],
    eligibility: [
      '12th with PCB - 50% (40% SC/ST/OBC)',
      'Age: 17 years by Dec 31 of admission year',
      'Unlimited attempts',
      'MANDATORY for MBBS/BDS/BAMS/BHMS/BSMS/BVSc',
    ],
    tnEligibility: '85% State Quota for TN + 7.5% for TN Govt School Students | Tamil medium exam available | Govt college fee ~₹14,000/year!',
    importantDates: {
      registration: 'Feb 2026',
      examDate: 'May 3, 2026',
      resultDate: 'June 2026',
    },
    applicationFee: {
      general: '₹1,700',
      scst: '₹1,000',
    },
    tnCollegesAccepting: [
      '36 Govt Medical Colleges in TN (₹14,000/yr fee!)',
      'AIIMS Madurai (All India Quota via NEET)',
      'JIPMER Puducherry (via NEET)',
      'Madras Medical College, Chennai',
      'Stanley Medical College',
      'Coimbatore Medical College',
      'Madurai Medical College',
      'Private Medical Colleges (SRM, Saveetha, etc.)',
    ],
    officialWebsite: 'https://neet.nta.nic.in',
    category: 'medical',
  },
  {
    id: 'tn-neet-counselling',
    name: 'TN NEET Counselling ⭐',
    tamilName: 'தமிழ்நாடு மருத்துவ கலந்தாய்வு',
    fullForm: 'Tamil Nadu Medical Admission Counselling (85% Seats for TN!)',
    conductingBody: 'TN Medical Selection Committee',
    examMode: 'Online Counselling',
    duration: 'Based on NEET Rank',
    syllabus: [
      'No separate exam',
      'Based on NEET-UG Score',
      'Choice filling online',
      'Document verification',
    ],
    eligibility: [
      'Valid NEET-UG Score',
      'TN Domicile / TN Nativity',
      'Studied in TN for 7+ years',
      '7.5% for TN Govt School Students',
    ],
    tnEligibility: '85% seats reserved for TN students! Govt college fee only ~₹14,000/year!',
    importantDates: {
      registration: 'June 2026',
      examDate: 'N/A (Counselling)',
      resultDate: 'July-Aug 2026',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      '36 Govt Medical Colleges',
      '15 Self-Financing Colleges',
      'Deemed Universities (SRM, Saveetha)',
      'Fee: ~₹14,000/year (Govt)',
    ],
    officialWebsite: 'https://tnmedicalselection.net',
    category: 'medical',
  },
  {
    id: 'bds-dental',
    name: 'BDS - Dental',
    tamilName: 'பல் மருத்துவம்',
    fullForm: 'Bachelor of Dental Surgery',
    conductingBody: 'Through NEET Score',
    examMode: 'Via NEET Score',
    duration: '5 years course',
    syllabus: [
      'Admission through NEET',
      'Same NEET exam as MBBS',
      'Separate counselling for BDS',
    ],
    eligibility: [
      'Valid NEET Score',
      '12th with PCB - 50%',
      'Age: 17+ years',
    ],
    tnEligibility: 'TN state quota available - Govt Dental Colleges in Chennai & Madurai',
    importantDates: {
      registration: 'June 2026',
      examDate: 'Via NEET (May 3, 2026)',
      resultDate: 'July 2026',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Govt Dental College, Chennai',
      'Govt Dental College, Madurai',
      'Meenakshi Dental College',
      'SRM Dental College',
      'Private Dental Colleges',
    ],
    officialWebsite: 'https://tnmedicalselection.net',
    category: 'medical',
  },
  {
    id: 'ayush-bams-bhms-bsms',
    name: 'AYUSH - BAMS/BHMS/BSMS',
    tamilName: 'ஆயுஷ் - சித்தா/ஆயுர்வேதா',
    fullForm: 'BAMS (Ayurveda) / BHMS (Homeopathy) / BSMS (Siddha)',
    conductingBody: 'Through NEET Score',
    examMode: 'Via NEET Score',
    duration: '5.5 years course',
    syllabus: [
      'Admission through NEET',
      'BSMS - Siddha Medicine (TN Special!)',
      'BAMS - Ayurvedic Medicine',
      'BHMS - Homeopathy',
    ],
    eligibility: [
      'Valid NEET Score',
      '12th with PCB - 50%',
      'Lower cutoff than MBBS',
    ],
    tnEligibility: 'BSMS (Siddha) is Tamil Nadu specialty! Govt Siddha Colleges available',
    importantDates: {
      registration: 'June 2026',
      examDate: 'Via NEET (May 3, 2026)',
      resultDate: 'Aug 2026',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Govt Siddha Medical College, Palayamkottai',
      'Govt Siddha Medical College, Chennai',
      'Govt Homeopathy College, Tirumangalam',
      'Sri Sairam Siddha Medical College',
    ],
    officialWebsite: 'https://tnmedicalselection.net',
    category: 'medical',
  },
  {
    id: 'bsc-nursing',
    name: 'B.Sc Nursing ⭐',
    tamilName: 'செவிலியர் படிப்பு',
    fullForm: 'Bachelor of Science in Nursing',
    conductingBody: 'TN Dr. MGR Medical University',
    examMode: 'Merit Based (12th Marks)',
    duration: '4 years course',
    syllabus: [
      'Govt colleges: NEET score required',
      'Private colleges: Merit based (12th marks)',
      'AIIMS Nursing: Separate entrance exam',
      'JIPMER Nursing: Via NEET score',
    ],
    eligibility: [
      '12th with PCB - 45%',
      'Age: 17-35 years',
      'Female & Male both eligible',
    ],
    tnEligibility: 'Govt nursing colleges through TN counselling - Many private options available',
    importantDates: {
      registration: 'June 2026',
      examDate: 'N/A (Merit)',
      resultDate: 'July 2026',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Govt College of Nursing, Chennai',
      'MMC College of Nursing',
      'CMC Vellore Nursing',
      'Private Nursing Colleges',
    ],
    officialWebsite: 'https://tnmgrmu.ac.in',
    category: 'medical',
    hasJKKN: true,
    jkknColleges: [],
  },
  {
    id: 'bpharm',
    name: 'B.Pharm ⭐',
    tamilName: 'மருந்தியல் படிப்பு',
    fullForm: 'Bachelor of Pharmacy',
    conductingBody: 'TN Dr. MGR Medical University',
    examMode: 'Merit Based (12th Marks)',
    duration: '4 years course',
    syllabus: [
      'Based on 12th PCM/PCB Marks',
      'No entrance exam for most',
      'Direct merit admission',
    ],
    eligibility: [
      '12th with PCM or PCB - 50%',
      'Age: 17+ years',
      'Maths OR Biology accepted',
    ],
    tnEligibility: 'State quota for TN students in govt pharmacy colleges',
    importantDates: {
      registration: 'June 2026',
      examDate: 'N/A (Merit)',
      resultDate: 'July 2026',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Madras Medical College (Pharmacy)',
      'JSS College of Pharmacy, Ooty',
      'PSG College of Pharmacy',
      'SRM College of Pharmacy',
    ],
    officialWebsite: 'https://tnmgrmu.ac.in',
    category: 'medical',
    hasJKKN: true,
    jkknColleges: [],
  },
  {
    id: 'allied-health',
    name: 'Allied Health Sciences ⭐',
    tamilName: 'துணை சுகாதாரம்',
    fullForm: 'BPT / BOT / BMLT / B.Sc Radiology & more',
    conductingBody: 'TN Dr. MGR Medical University',
    examMode: 'Merit Based (12th Marks)',
    duration: '3-4 years course',
    syllabus: [
      'BPT - Physiotherapy',
      'BOT - Occupational Therapy',
      'BMLT - Medical Lab Technology',
      'B.Sc Radiology, Cardiac Tech',
      'Based on 12th PCB marks',
    ],
    eligibility: [
      '12th with PCB - 50%',
      'Age: 17-25 years',
      'TN domicile preferred',
    ],
    tnEligibility: 'Growing demand! Excellent job opportunities in hospitals across TN',
    importantDates: {
      registration: 'June 2026',
      examDate: 'N/A (Merit)',
      resultDate: 'July 2026',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'MMC Allied Health Sciences',
      'Stanley Medical College',
      'PSG IMS, Coimbatore',
      'SRM Allied Health',
    ],
    officialWebsite: 'https://tnmgrmu.ac.in',
    category: 'medical',
    hasJKKN: true,
    jkknColleges: [],
  },
  {
    id: 'jipmer-puducherry',
    name: 'JIPMER Puducherry',
    tamilName: 'ஜிப்மர் புதுச்சேரி',
    fullForm: 'Jawaharlal Institute of Postgraduate Medical Education',
    conductingBody: 'Through NEET Score',
    examMode: 'Via NEET Score',
    duration: '5.5 years MBBS',
    syllabus: [
      'Admission through NEET — no separate exam',
      'All India + Puducherry Quota',
      'MBBS, B.Sc Nursing, B.Sc Allied Health',
      'Same NEET syllabus: Master NEET = Get into JIPMER',
      'AIIMS Madurai also admits via NEET only',
      'Premier Medical Institute near TN — low fees, high quality',
    ],
    eligibility: [
      'Valid NEET Score',
      '12th with PCB - 50%',
      'High NEET rank required',
    ],
    tnEligibility: 'Near Tamil Nadu - Very popular among TN students! Puducherry quota available',
    importantDates: {
      registration: 'June 2026',
      examDate: 'Via NEET (May 3, 2026)',
      resultDate: 'July 2026',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'JIPMER Puducherry (Main)',
      'JIPMER Karaikal',
      'Government Institute',
      'Low fees, High quality',
    ],
    officialWebsite: 'https://jipmer.edu.in',
    category: 'medical',
  },
  {
    id: 'aiims-paramedical',
    name: 'AIIMS Paramedical Entrance',
    tamilName: 'எய்ம்ஸ் துணை மருத்துவ நுழைவுத் தேர்வு',
    fullForm: 'AIIMS B.Sc Paramedical / Allied Health Sciences Entrance',
    conductingBody: 'AIIMS, New Delhi',
    examMode: 'Computer Based Test (CBT)',
    duration: '90 minutes',
    syllabus: [
      '⚠️ NOT based on NEET — Separate entrance exam!',
      'Physics - 30 MCQs (NCERT Class 11 & 12)',
      'Chemistry - 30 MCQs (NCERT Class 11 & 12)',
      'Biology/Mathematics - 30 MCQs (NCERT Class 11 & 12)',
      'Total: 90 MCQs | Based on NCERT curriculum',
      'Courses: B.Sc in MLT, Radiology, OT Tech, Cardiac Tech, etc.',
    ],
    eligibility: [
      '12th pass with PCB or PCM',
      'Minimum 55% aggregate (50% SC/ST)',
      'Age: 17-21 years',
    ],
    tnEligibility: 'TN students eligible for AIIMS Madurai paramedical courses. Separate from NEET!',
    importantDates: {
      registration: 'April 2026',
      examDate: 'July 4, 2026',
      resultDate: 'August 2026',
    },
    applicationFee: {
      general: '₹1,500',
      scst: '₹1,200',
    },
    tnCollegesAccepting: [
      'AIIMS Madurai (TN)',
      'AIIMS New Delhi',
      'AIIMS Jodhpur, Bhopal, Rishikesh',
      'All AIIMS across India',
    ],
    officialWebsite: 'https://aiimsexams.ac.in',
    category: 'medical',
  },
  {
    id: 'aiims-bsc-nursing',
    name: 'AIIMS B.Sc Nursing Entrance',
    tamilName: 'எய்ம்ஸ் செவிலியர் நுழைவுத் தேர்வு',
    fullForm: 'AIIMS B.Sc (Hons.) Nursing & B.Sc (Post-Basic) Nursing Entrance',
    conductingBody: 'AIIMS, New Delhi',
    examMode: 'Computer Based Test (CBT)',
    duration: '90 minutes',
    syllabus: [
      '⚠️ NOT based on NEET — Separate AIIMS entrance exam!',
      'Physics - MCQs (NCERT Class 11 & 12)',
      'Chemistry - MCQs (NCERT Class 11 & 12)',
      'Biology - MCQs (NCERT Class 11 & 12)',
      'General Knowledge & Aptitude',
      'Same NCERT-based syllabus as NEET — prepare NEET topics = prepared for this too',
    ],
    eligibility: [
      '12th pass with PCB - 55% (50% SC/ST)',
      'Age: 17-25 years',
      'Female & Male both eligible',
    ],
    tnEligibility: 'Alternative to NEET-based nursing admission. AIIMS nursing is prestigious with low fees.',
    importantDates: {
      registration: 'April 2026',
      examDate: 'June 2026',
      resultDate: 'July 2026',
    },
    applicationFee: {
      general: '₹1,500',
      scst: '₹1,200',
    },
    tnCollegesAccepting: [
      'AIIMS New Delhi (Nursing)',
      'AIIMS Madurai (if nursing available)',
      'AIIMS Jodhpur, Bhopal',
      'All AIIMS Nursing Colleges',
    ],
    officialWebsite: 'https://aiimsexams.ac.in',
    category: 'medical',
  },

  // ============ MANAGEMENT & LAW ============
  {
    id: 'tndalu',
    name: 'TNDALU Merit Admission ⭐',
    tamilName: 'தமிழ்நாடு அம்பேத்கர் சட்டப் பல்கலை',
    fullForm: 'Tamil Nadu Dr. Ambedkar Law University — No Entrance Exam!',
    conductingBody: 'TNDALU, Chennai',
    examMode: 'Merit Based (12th Marks) — NO EXAM',
    duration: 'N/A — Based on 12th marks & counselling',
    syllabus: [
      '⭐ NO ENTRANCE EXAM REQUIRED',
      'Selection based on Class 12 marks only',
      'Rank list released → Online counselling',
      'Courses: BA LLB, BCom LLB, BBA LLB, BCA LLB, BSc LLB (5-year integrated)',
      'Also: 3-year LLB for graduates',
    ],
    eligibility: [
      '12th pass from any recognized board',
      'Minimum 70% marks in 12th',
      'TN domicile preferred for govt colleges',
    ],
    tnEligibility: 'Easiest route for TN students! No exam needed — just score 70%+ in 12th. Govt college fee is very low.',
    importantDates: {
      registration: 'April-May 2026',
      examDate: 'N/A (Merit based)',
      resultDate: 'June-July 2026 (Counselling)',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Dr. Ambedkar Govt Law College, Chennai',
      'Govt Law College, Madurai',
      'Govt Law College, Coimbatore',
      'Govt Law College, Tirunelveli',
      'School of Excellence in Law, Chennai',
      'Private affiliated law colleges across TN',
    ],
    officialWebsite: 'https://tndalu.ac.in',
    category: 'management',
  },
  {
    id: 'clat',
    name: 'CLAT',
    tamilName: 'சட்டப் படிப்பு நுழைவுத் தேர்வு',
    fullForm: 'Common Law Admission Test — #1 National Law Entrance Exam',
    conductingBody: 'Consortium of NLUs',
    examMode: 'Offline (Pen & Paper)',
    duration: '2 hours',
    syllabus: [
      'English Language (~24Q, ~20%): Reading Comprehension, Vocabulary in Context, Grammar & Errors, Summary & Paraphrasing, Para Jumbles — 450-word passages',
      'Current Affairs & GK (~30Q, 25%): National/International News, Govt Schemes, Sports & Awards, Science & Tech, Environment + Static GK: History, Geography, Polity, Constitution, International Orgs',
      'Legal Reasoning (~30Q, 25%): Legal Principles & Fact Application, Torts, Contracts, Criminal Law (IPC), Constitutional Law, Family Law, Legal Maxims — No prior law knowledge needed, all principles given in passage',
      'Logical Reasoning (~24Q, ~20%): Syllogisms, Assumptions & Inferences, Strengthen/Weaken Arguments, Cause & Effect, Analogies, Critical Reasoning passages',
      'Quantitative Techniques (~14Q, ~10%): Percentage, Profit & Loss, Ratio, SI/CI, Time-Speed-Distance, Averages, Basic Algebra, Data Interpretation — 10th standard level only',
      'Total: 120 MCQs | 120 Marks | 2 Hours | Offline (Pen-Paper) | –0.25 per wrong answer',
    ],
    eligibility: [
      '12th pass any stream',
      'Minimum 45% (40% for SC/ST)',
      'No upper age limit',
    ],
    tnEligibility: 'Gateway to TNNLU Trichy (Tamil Nadu National Law University) + 25 other NLUs across India!',
    importantDates: {
      registration: 'Aug-Nov 2026',
      examDate: 'December 6, 2026 (CLAT 2027)',
      resultDate: 'Jan 2027',
    },
    applicationFee: {
      general: '₹4,000',
      scst: '₹3,500',
    },
    tnCollegesAccepting: [
      'TNNLU Tiruchirappalli (TN)',
      'NLSIU Bangalore',
      'NALSAR Hyderabad',
      'NLU Jodhpur',
      '26 NLUs + many private colleges accept CLAT scores',
    ],
    officialWebsite: 'https://consortiumofnlus.ac.in',
    category: 'management',
  },
  {
    id: 'ailet',
    name: 'AILET (NLU Delhi)',
    tamilName: 'AILET (என்எல்யூ டெல்லி)',
    fullForm: 'All India Law Entrance Test — For NLU Delhi Only',
    conductingBody: 'National Law University, Delhi',
    examMode: 'Offline (Pen & Paper)',
    duration: '2 hours',
    syllabus: [
      'English Language (50Q, 50 marks, 33%): Reading Comprehension, Sentence Correction, Fill in Blanks, Vocabulary (Synonyms/Antonyms), Para Jumbles, Grammar & Errors, Idioms & Phrases',
      'Current Affairs & GK (30Q, 30 marks, 20%): National/International Events, Indian History/Geography/Polity, Science & Tech, Sports & Awards, Legal Updates & Landmark Judgments, Constitution, Important Personalities',
      'Logical Reasoning (70Q, 70 marks, 47% — Highest!): Legal Propositions & Fact Application, Legal Maxims, Analogical Reasoning, Syllogisms, Statement-Conclusion, Blood Relations, Direction Sense, Number/Letter Series, Critical Reasoning, Data Sufficiency',
      'Total: 150 MCQs | 150 Marks | 2 Hours | Offline | –0.25 per wrong answer | No Mathematics section',
    ],
    eligibility: [
      '12th pass any stream',
      'Minimum 50% marks in 12th',
      'No age limit',
    ],
    tnEligibility: 'For NLU Delhi — India\'s 2nd best law college. Exam held in 35+ cities including Chennai.',
    importantDates: {
      registration: 'Sep-Nov 2026',
      examDate: 'December 2026',
      resultDate: 'Jan 2027',
    },
    applicationFee: {
      general: '₹3,500',
      scst: '₹1,500',
    },
    tnCollegesAccepting: [
      'National Law University, Delhi (exclusively)',
      'BA LLB (Hons.) — 5 year integrated programme',
    ],
    officialWebsite: 'https://nludelhi.ac.in',
    category: 'management',
  },
  {
    id: 'lsat-india',
    name: 'LSAT India',
    tamilName: 'LSAT இந்தியா',
    fullForm: 'Law School Admission Test — India (Pure Reasoning — No Law/GK/Maths!)',
    conductingBody: 'Pearson VUE (licensed by LSAC, USA)',
    examMode: 'Online / Offline',
    duration: '~2.5 hours (35 min per section)',
    syllabus: [
      'Analytical Reasoning (~23-24Q, 35 min): Linear Ordering, Sequencing, Grouping, Arrangements, Logical Puzzles — analyze relationships between people/objects/events',
      'Logical Reasoning Section 1 (~24-26Q, 35 min): Inference, Assumptions, Strengthen/Weaken Arguments, Parallel Reasoning, Flaws in Arguments, Method of Reasoning',
      'Logical Reasoning Section 2 (~24-26Q, 35 min): Same as Section 1 — evaluate, strengthen, or challenge arguments',
      'Reading Comprehension (~26-28Q, 35 min): 4 long complex passages, Main Point & Purpose, Inference, Author\'s Attitude & Tone, Structure of Argument, Comparative Reading (2 related passages)',
      'Total: ~92-100 Qs | Scored on 420-480 scale | No Negative Marking | No GK, No Maths, No Law knowledge needed — pure reasoning & reading!',
    ],
    eligibility: [
      '12th pass any stream',
      'Minimum 45% marks',
      'No age limit',
    ],
    tnEligibility: 'Accepted by top private law schools across India. Good for students strong in reasoning.',
    importantDates: {
      registration: 'Oct 2025 - May 2026',
      examDate: 'Jan & June 2026',
      resultDate: '3-4 weeks after exam',
    },
    applicationFee: {
      general: '₹3,999',
      scst: '₹3,999',
    },
    tnCollegesAccepting: [
      'Jindal Global Law School',
      'UPES Dehradun',
      'Christ University',
      'Alliance University',
      'Many premium private law colleges',
    ],
    officialWebsite: 'https://www.lsatindia.in',
    category: 'management',
  },
  {
    id: 'slat',
    name: 'SLAT (Symbiosis)',
    tamilName: 'SLAT (சிம்பயோசிஸ்)',
    fullForm: 'Symbiosis Law Admission Test',
    conductingBody: 'Symbiosis International University, Pune',
    examMode: 'Online Test',
    duration: '1 hour',
    syllabus: [
      'Logical Reasoning (12Q, 12 marks): Statements & Assumptions, Conclusions, Syllogisms, Analogies, Series, Blood Relations, Direction Sense, Coding & Decoding, Cause & Effect',
      'Legal Reasoning (12Q, 12 marks): Principle-Fact Based Questions, Law of Torts, Criminal Law (IPC basics), Constitutional Law (Fundamental Rights, Directive Principles), Contract Law, Legal Maxims, Court Judgments',
      'Analytical Reasoning (12Q, 12 marks): Puzzles (Seating, Floor Plans), Logical Deductions, Input-Output, Data Arrangements, Venn Diagrams, Complex Statements',
      'Reading Comprehension (12Q, 12 marks): General & Legal passages, Vocabulary in Context, Main Idea & Theme, Inference, Grammar-based questions',
      'General Knowledge (12Q, 12 marks): Current National/International Affairs, Indian History/Geography/Polity, Govt Schemes, Sports & Awards, Science & Environment',
      'Total: 60 MCQs | 60 Marks | 1 Hour | CBT Mode | No Negative Marking | Also: WAT + PI after shortlisting',
    ],
    eligibility: [
      '12th pass any stream',
      'Minimum 45% marks',
      'No age limit',
    ],
    tnEligibility: 'For Symbiosis Law Schools in Pune, Hyderabad, Noida, Nagpur — ~1000 seats across campuses.',
    importantDates: {
      registration: 'Dec 2025 - May 2026',
      examDate: 'May 2026',
      resultDate: 'May-June 2026',
    },
    applicationFee: {
      general: '₹1,750',
      scst: '₹1,750',
    },
    tnCollegesAccepting: [
      'Symbiosis Law School, Pune',
      'Symbiosis Law School, Hyderabad',
      'Symbiosis Law School, Noida',
      'Symbiosis Law School, Nagpur',
      'BA LLB & BBA LLB programmes',
    ],
    officialWebsite: 'https://set-test.org',
    category: 'management',
  },
  {
    id: 'bba-bca-bcom-direct',
    name: 'BBA/BCA/B.Com (Direct) ⭐',
    tamilName: 'BBA/BCA/B.Com நேரடி சேர்க்கை',
    fullForm: 'Direct Admission - No Entrance Exam',
    conductingBody: 'All TN Universities',
    examMode: 'Merit Based (12th Marks)',
    duration: '3 years course',
    syllabus: [
      'No entrance exam',
      'Based on 12th marks only',
      'Any stream accepted',
    ],
    eligibility: [
      '12th pass any stream',
      'Minimum 50% (varies)',
      'No age limit',
    ],
    tnEligibility: 'All TN universities accept 12th marks - Easy admission for TN students!',
    importantDates: {
      registration: 'May-June 2026',
      examDate: 'N/A (Merit)',
      resultDate: 'June-July 2026',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Madras University',
      'Anna University',
      'Bharathiar University',
      'All TN Colleges',
    ],
    officialWebsite: 'https://unom.ac.in',
    category: 'management',
    hasJKKN: true,
    jkknColleges: [],
  },
  {
    id: 'ca-cs-cma-foundation',
    name: 'CA/CS/CMA Foundation',
    tamilName: 'CA/CS/CMA அடித்தளப் படிப்பு',
    fullForm: 'Chartered Accountant / Company Secretary / Cost Accountant',
    conductingBody: 'ICAI / ICSI / ICMAI',
    examMode: 'Pen & Paper / Online',
    duration: '4 months foundation',
    syllabus: [
      'CA Foundation (4 Papers, 8 hrs total): Paper 1 — Principles & Practice of Accounting (100 marks, Subjective): Journal entries, Ledger, Trial Balance, Depreciation, Partnership, Company Accounts, BRS',
      'CA Paper 2 — Business Laws & Business Correspondence (100 marks, Subjective): Indian Contract Act, Sale of Goods Act, Partnership Act, Business Letters, Precis Writing, Report Writing',
      'CA Paper 3 — Business Mathematics, Statistics & Logical Reasoning (100 marks, MCQ): Ratios, Indices, Logarithms, Equations, Permutations, Sequence, Statistics (Mean/Median/Mode), Correlation, Probability, Logical Reasoning',
      'CA Paper 4 — Business Economics & Business & Commercial Knowledge (100 marks, MCQ): Micro/Macro Economics, Demand-Supply, National Income, Money & Banking, Indian Economy, Business Environment, GST basics',
      'CS Foundation (4 Papers): Business Environment & Law, Business Management & Ethics, Business Economics, Fundamentals of Accounting & Auditing',
      'CMA Foundation (4 Papers): Fundamentals of Economics & Management, Fundamentals of Accounting, Fundamentals of Laws & Ethics, Fundamentals of Business Maths & Statistics',
    ],
    eligibility: [
      'Can register after 12th',
      'Any stream accepted',
      'No minimum marks',
    ],
    tnEligibility: 'Start professional courses right after 12th! Exam centers across TN',
    importantDates: {
      registration: 'Anytime after 12th',
      examDate: 'May & Nov (CA/CMA), June & Dec (CS)',
      resultDate: '2 months after exam',
    },
    applicationFee: {
      general: '₹11,000-15,000',
      scst: 'Varies',
    },
    tnCollegesAccepting: [
      'Self-study / Coaching',
      'CA: icai.org',
      'CS: icsi.edu',
      'CMA: icmai.in',
    ],
    officialWebsite: 'https://icai.org',
    category: 'management',
  },

  // ============ AGRICULTURE ============
  {
    id: 'tnau',
    name: 'TNAU ⭐',
    tamilName: 'தமிழ்நாடு வேளாண் பல்கலைக்கழகம்',
    fullForm: 'Tamil Nadu Agricultural University (NO EXAM!)',
    conductingBody: 'TNAU, Coimbatore',
    examMode: 'Merit Based (12th Marks)',
    duration: '4 years B.Sc Agri',
    syllabus: [
      '⭐ NO ENTRANCE EXAM',
      'Based on 12th PCB/PCM marks',
      'Agriculture subject preference',
      'Cutoff based on aggregate',
    ],
    eligibility: [
      '12th with PCB/PCM - 50%',
      'TN domicile mandatory',
      'Age: 17-21 years',
    ],
    tnEligibility: '100% State Quota - Only TN students eligible! Low fees govt education',
    importantDates: {
      registration: 'May 2026',
      examDate: 'N/A (Merit)',
      resultDate: 'July 2026 (Counselling)',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'TNAU Coimbatore (Main)',
      'AC&RI Madurai',
      'AC&RI Trichy',
      'AC&RI Killikulam',
      '14+ TNAU Campuses',
    ],
    officialWebsite: 'https://tnau.ac.in',
    category: 'agriculture',
    hasJKKN: true,
    jkknColleges: [],
  },
  {
    id: 'tanuvas',
    name: 'TANUVAS - Veterinary',
    tamilName: 'கால்நடை மருத்துவம்',
    fullForm: 'TN Veterinary & Animal Sciences University',
    conductingBody: 'TANUVAS, Chennai',
    examMode: 'Via NEET Score',
    duration: '5.5 years B.V.Sc',
    syllabus: [
      'B.V.Sc: Through NEET Score',
      'B.F.Sc (Fisheries): 12th marks',
      'B.Tech Food: 12th PCM marks',
    ],
    eligibility: [
      'B.V.Sc: Valid NEET Score',
      '12th with PCB - 50%',
      'TN domicile mandatory',
    ],
    tnEligibility: 'Only TN students - Madras Veterinary College is one of the oldest in Asia!',
    importantDates: {
      registration: 'June 2026',
      examDate: 'Via NEET',
      resultDate: 'Aug 2026',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Madras Veterinary College, Chennai',
      'VC&RI Namakkal',
      'VC&RI Tirunelveli',
      'Fisheries College, Thoothukudi',
    ],
    officialWebsite: 'https://tanuvas.ac.in',
    category: 'agriculture',
  },
  {
    id: 'icar-aieea',
    name: 'ICAR AIEEA',
    tamilName: 'ஐசிஏஆர் தேசிய தேர்வு',
    fullForm: 'ICAR All India Entrance Examination',
    conductingBody: 'NTA for ICAR',
    examMode: 'Computer Based Test',
    duration: '2.5 hours',
    syllabus: [
      'Physics (50 MCQ, 200 marks): Mechanics, Heat & Thermodynamics, Optics, Electrostatics, Current Electricity, Magnetic Effects, EM Waves, Modern Physics — Class 11 & 12 NCERT level',
      'Chemistry (50 MCQ, 200 marks): Physical Chemistry (Mole concept, Chemical Equilibrium, Electrochemistry), Organic Chemistry (Hydrocarbons, Biomolecules), Inorganic Chemistry (Periodic Table, p-block, d-block, Coordination) — NCERT based',
      'Biology/Mathematics (50 MCQ, 200 marks): Botany (Plant Physiology, Genetics, Ecology), Zoology (Human Physiology, Reproduction, Evolution) OR Mathematics (Algebra, Calculus, Coordinate Geometry, Trigonometry)',
      'Total: 150 MCQs | 600 Marks | 2.5 Hours | +4/-1 Marking | CBT Mode',
      'Agriculture stream: Choose Biology (PCB students). Engineering stream: Choose Mathematics (PCM students)',
    ],
    eligibility: [
      '12th with PCB/PCM - 50%',
      'Age: 16.5+ years',
      'All India applicants',
    ],
    tnEligibility: 'For Central Agricultural Universities - ICAR quota in TNAU also available',
    importantDates: {
      registration: 'March 2026',
      examDate: 'June 2026',
      resultDate: 'July 2026',
    },
    applicationFee: {
      general: '₹1,000',
      scst: '₹500',
    },
    tnCollegesAccepting: [
      'TNAU (ICAR Quota)',
      'IARI New Delhi',
      'NDRI Karnal',
      '75+ ICAR Institutes',
    ],
    officialWebsite: 'https://icar.nta.nic.in',
    category: 'agriculture',
  },

  // ============ DESIGN & ARTS ============
  {
    id: 'nift-chennai',
    name: 'NIFT Chennai ⭐',
    tamilName: 'நிஃப்ட் சென்னை',
    fullForm: 'National Institute of Fashion Technology (TN Campus!)',
    conductingBody: 'NIFT',
    examMode: 'CAT + GAT + Situation Test',
    duration: '4 years B.Des',
    syllabus: [
      'GAT — General Ability Test (B.Des: 50 MCQs, 2 hrs): Quantitative Ability (Class 10 Maths), Communication Ability (English Comprehension, Grammar), English Comprehension, Analytical Ability, GK (Art/Culture/Fashion/Design history), Current Affairs',
      'CAT — Creative Ability Test (B.Des: 3 hrs, Subjective): Material/Object manipulation, Innovate/Create from given elements, Illustration of concepts, Design thinking problems, Visual composition & aesthetics',
      'Situation Test (for shortlisted candidates): Hands-on 3D model making, Material manipulation, Spatial ability, Innovation under time pressure',
      'B.FTech (Fashion Technology): Only GAT — no CAT required',
      'Scoring: B.Des = GAT 30% + CAT 50% + Situation Test 20%. B.FTech = GAT 100%',
      'Key: Practice drawing daily, Study design history, Read about Indian textiles & crafts, Develop visual observation skills',
    ],
    eligibility: [
      '12th pass any stream',
      'No minimum marks',
      'Age: Below 24 years',
    ],
    tnEligibility: 'NIFT Chennai Campus in TN! Premier fashion design institute',
    importantDates: {
      registration: 'Oct-Dec 2024',
      examDate: 'Feb 2026',
      resultDate: 'April 2026',
    },
    applicationFee: {
      general: '₹2,500',
      scst: '₹1,250',
    },
    tnCollegesAccepting: [
      'NIFT Chennai (TN Campus)',
      'NIFT Delhi',
      'NIFT Mumbai',
      '18 NIFT Campuses',
    ],
    officialWebsite: 'https://nift.ac.in',
    category: 'design',
  },
  {
    id: 'nid-dat',
    name: 'NID DAT',
    tamilName: 'என்ஐடி வடிவமைப்பு தேர்வு',
    fullForm: 'National Institute of Design Entrance',
    conductingBody: 'NID, Ahmedabad',
    examMode: 'Prelims + Mains + Interview',
    duration: '4 years B.Des',
    syllabus: [
      'DAT Prelims (3 hrs, CBT + Drawing): Visual perception & observation, Color sensitivity & design elements, Problem solving through design, Spatial ability, 2D/3D visualization, Drawing & sketching ability',
      'DAT Mains (for shortlisted — at NID campus): Studio Test — hands-on design activity with given materials, Group Discussion, Personal Interview with portfolio review',
      'Key topics: Visual communication, Material understanding, Indian art & culture, Environmental awareness, Current design trends, Everyday object analysis',
      'No fixed syllabus — tests natural design aptitude. Prepare by: sketching daily, visiting museums, observing design in everyday objects, studying color theory',
      'NID campuses: Ahmedabad (main), Gandhinagar, Bangalore, Vijayawada, Kurukshetra, Jorhat, Bhopal',
    ],
    eligibility: [
      '12th pass any stream',
      'No minimum marks',
      'Age: Below 20 years',
    ],
    tnEligibility: 'Premier design institute - Product, Graphic, Textile design courses',
    importantDates: {
      registration: 'Oct 2024',
      examDate: 'Jan 2026',
      resultDate: 'March 2026',
    },
    applicationFee: {
      general: '₹3,000',
      scst: '₹1,500',
    },
    tnCollegesAccepting: [
      'NID Ahmedabad',
      'NID Bangalore',
      'NID Andhra Pradesh',
    ],
    officialWebsite: 'https://nid.edu',
    category: 'design',
  },
  {
    id: 'jee-paper2-barch',
    name: 'JEE Main Paper 2 - B.Arch',
    tamilName: 'ஜேஇஇ கட்டிடக்கலை',
    fullForm: 'JEE Main Paper 2 for Architecture',
    conductingBody: 'NTA',
    examMode: 'CBT + Drawing',
    duration: '3 hours',
    syllabus: [
      'Mathematics (20 MCQ + 5 Numerical, 100 marks): Sets & Relations, Complex Numbers, Quadratic Equations, Matrices & Determinants, Permutations & Combinations, Binomial Theorem, Sequences, Coordinate Geometry, 3D Geometry, Calculus, Statistics & Probability, Trigonometry — Same as JEE Main Paper 1',
      'Aptitude Test (50 MCQ, 200 marks): Awareness of architecture & buildings, Texture & objects, Mental ability (Visual, Numerical, Verbal), 3D perception & visualization, Architectural awareness, Color theory, Building materials',
      'Drawing Test (2 Questions, 100 marks): 2D/3D composition using geometric shapes, Urban landscape drawing, Architectural perspective drawing, Design creation from given elements — done on paper with pencil/colors',
      'Total: 77 Questions | 400 Marks | 3 Hours | Exam: April 2026',
      'Drawing is done on PAPER (not computer). Carry pencils, erasers, colors, geometry box',
    ],
    eligibility: [
      '12th with Maths - 50%',
      'Physics, Chemistry required',
      'No age limit',
    ],
    tnEligibility: 'For B.Arch at NIT Trichy & Anna University School of Architecture',
    importantDates: {
      registration: 'Nov 2024',
      examDate: 'April 2026',
      resultDate: 'May 2026',
    },
    applicationFee: {
      general: '₹1,000',
      scst: '₹500',
    },
    tnCollegesAccepting: [
      'Anna University SAP',
      'NIT Trichy (B.Arch)',
      'SRM Architecture',
      'VIT School of Architecture',
    ],
    officialWebsite: 'https://jeemain.nta.nic.in',
    category: 'design',
  },

  // ============ DEFENCE & OTHERS ============
  {
    id: 'nchmct-jee',
    name: 'NCHMCT JEE ⭐',
    tamilName: 'ஹோட்டல் மேலாண்மை',
    fullForm: 'Hotel Management Entrance - IHM Chennai in TN!',
    conductingBody: 'NTA for NCHMCT',
    examMode: 'Computer Based Test',
    duration: '3 hours',
    syllabus: [
      'Numerical Ability (30Q): Arithmetic (Percentage, Profit-Loss, Ratio, SI/CI), Number System, Algebra, Geometry, Data Interpretation, Time & Work, Speed & Distance',
      'Reasoning & Logical Deduction (30Q): Series Completion, Analogies, Classification, Coding, Blood Relations, Direction Test, Syllogisms, Seating Arrangement, Puzzles',
      'General Knowledge & Current Affairs (30Q): Indian History, Geography, Polity, Economy, Science, Culture, Tourism, Hospitality Industry, Famous Hotels, Awards, Sports',
      'English Language (60Q — Highest weightage!): Reading Comprehension (2-3 passages), Grammar (Tenses, Articles, Prepositions), Vocabulary (Synonyms, Antonyms, Idioms), Sentence Correction, Para Jumbles, Cloze Test',
      'Aptitude for Service Sector (50Q): Personality Traits, Hospitality Attitude, Teamwork, Problem Solving, Customer Handling, Situational Judgment',
      'Total: 200 MCQs | 800 Marks | 3 Hours | +4/-1 Marking | CBT Mode',
    ],
    eligibility: [
      '12th pass any stream',
      'Minimum 45% (40% SC/ST)',
      'Age: 25 years max (Gen)',
    ],
    tnEligibility: 'IHM Chennai is located in TN! State quota available for TN students',
    importantDates: {
      registration: 'Jan-March 2026',
      examDate: 'May 2026',
      resultDate: 'June 2026',
    },
    applicationFee: {
      general: '₹1,000',
      scst: '₹500',
    },
    tnCollegesAccepting: [
      'IHM Chennai (TN Campus)',
      'IHM Mumbai',
      'IHM Delhi',
      '21 Central IHMs',
    ],
    officialWebsite: 'https://nchmct.org',
    category: 'management',
  },
  // ═══ MISSING EXAMS ADDED — COMPLETE LIST FOR 12TH PASS ═══
  
  // ENGINEERING — State Level
  {
    id: 'cuet',
    name: 'CUET-UG',
    tamilName: 'மத்திய பல்கலை நுழைவுத் தேர்வு',
    fullForm: 'Common University Entrance Test — Undergraduate',
    conductingBody: 'National Testing Agency (NTA)',
    examMode: 'Computer Based Test (CBT)',
    duration: '45 min per section (Slot-wise)',
    syllabus: [
      'Section IA: 13 Languages (choose any)',
      'Section IB: 20 Languages (choose any)',
      'Section II: 27 Domain Subjects (choose up to 6) — Physics, Chemistry, Math, Biology, Economics, History, Political Science, etc.',
      'Section III: General Test — GK, Quantitative Reasoning, Logical Reasoning, Current Affairs, General Awareness',
      'Standard: Based on Class 12 NCERT syllabus',
      'Also for Allied Health & Biomedical Sciences at Central Universities',
    ],
    eligibility: [
      '12th Pass from any recognized board',
      'No minimum percentage for application',
      'University-specific cutoffs may apply',
    ],
    tnEligibility: 'TN HSC students eligible. Many central universities accept CUET for UG admissions.',
    importantDates: { registration: 'February 2026', examDate: 'May 2026', resultDate: 'June 2026' },
    applicationFee: { general: '₹650', scst: '₹550' },
    tnCollegesAccepting: [
      'Central University of Tamil Nadu (CUTN)',
      'Pondicherry University',
      'University of Delhi (DU)',
      'JNU, BHU, AMU, Jamia Millia',
      '261+ Central, State & Private Universities across India',
    ],
    officialWebsite: 'https://cuet.nta.nic.in',
    category: 'management',
  },
  {
    id: 'comedk',
    name: 'COMEDK UGET',
    tamilName: 'கொமெடிகே',
    fullForm: 'Consortium of Medical, Engineering & Dental Colleges of Karnataka',
    conductingBody: 'COMEDK',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 Hours',
    syllabus: [
      'Physics (60 MCQ): Mechanics (Kinematics, Newton Laws, Work-Energy, Rotation), Heat & Thermodynamics, Waves, Electrostatics, Current Electricity, Magnetism, EM Induction, Ray & Wave Optics, Modern Physics, Semiconductor Devices — 1st & 2nd PUC (Class 11-12) level',
      'Chemistry (60 MCQ): Physical (Solid State, Solutions, Electrochemistry, Chemical Kinetics, Surface Chemistry), Organic (Haloalkanes, Alcohols, Aldehydes, Carboxylic Acids, Amines, Biomolecules, Polymers), Inorganic (p-block, d-block, Coordination Compounds, Metallurgy)',
      'Mathematics (60 MCQ): Algebra (Matrices, Determinants, PnC, Probability, Complex Numbers), Calculus (Limits, Continuity, Differentiation, Integration, Differential Equations), Vectors & 3D Geometry, Coordinate Geometry (Conics), Relations & Functions',
      'Total: 180 MCQs | 180 Marks | 3 Hours | +1/0 (No negative marking!) | CBT Mode',
    ],
    eligibility: [
      '12th Pass with PCM (Physics, Chemistry, Mathematics)',
      'Minimum 45% in PCM (40% for SC/ST/OBC)',
      'Indian National or NRI/PIO/OCI',
    ],
    tnEligibility: 'TN students can apply for Karnataka private engineering colleges via COMEDK.',
    importantDates: { registration: 'January 2026', examDate: 'May 2026', resultDate: 'June 2026' },
    applicationFee: { general: '₹1,800', scst: '₹1,800' },
    tnCollegesAccepting: ['700+ Private Engineering Colleges in Karnataka', 'RV College, BMS, MSRIT, PES University, etc.'],
    officialWebsite: 'https://www.comedk.org',
    category: 'engineering',
  },
  {
    id: 'wbjee',
    name: 'WBJEE',
    tamilName: 'மேற்கு வங்காள ஜேஇஇ',
    fullForm: 'West Bengal Joint Entrance Examination',
    conductingBody: 'WBJEEB',
    examMode: 'Offline (OMR)',
    duration: '2 Hours per paper',
    syllabus: [
      'Paper I — Mathematics (75 MCQ, 100 marks): Algebra (AP/GP, Quadratics, Complex Numbers, Matrices, PnC, Binomial), Trigonometry, Coordinate Geometry (Circles, Conics), Calculus (Limits, Differentiation, Integration, DE), Vectors, 3D Geometry, Probability, Sets & Relations',
      'Paper II — Physics (40 MCQ, 50 marks): Mechanics, Heat, Waves, Electrostatics, Current Electricity, Magnetism, Optics, Modern Physics, Semiconductors — West Bengal Board + NCERT syllabus',
      'Paper II — Chemistry (40 MCQ, 50 marks): Atomic Structure, Chemical Bonding, States of Matter, Equilibrium, Redox, Organic Chemistry (Hydrocarbons to Biomolecules), Inorganic (Periodic Table, p-block, d-block, Coordination)',
      'Total: 155 MCQs | 200 Marks | Paper I: 2 hrs, Paper II: 2 hrs | Category I (+1/0), Category II (+2/-0.5), Category III (+2/-0.5) — 3 difficulty levels!',
    ],
    eligibility: ['12th Pass with PCM', 'Minimum 45% in PCM aggregate'],
    tnEligibility: 'Open to all Indian students for WB engineering colleges.',
    importantDates: { registration: 'December 2025', examDate: 'April 2026', resultDate: 'June 2026' },
    applicationFee: { general: '₹500', scst: '₹400' },
    tnCollegesAccepting: ['Jadavpur University', 'IIEST Shibpur', 'Heritage Institute', '200+ WB Engineering Colleges'],
    officialWebsite: 'https://wbjeeb.nic.in',
    category: 'engineering',
  },
  {
    id: 'mht-cet',
    name: 'MHT CET',
    tamilName: 'மகாராஷ்டிரா CET',
    fullForm: 'Maharashtra Common Entrance Test',
    conductingBody: 'State CET Cell, Maharashtra',
    examMode: 'Computer Based Test (CBT)',
    duration: '90 Minutes per paper',
    syllabus: [
      'Physics (50 MCQ): Mechanics, Rotational Dynamics, Oscillations, Elasticity, Surface Tension, Wave Motion, Optics, Electrostatics, Current Electricity, Magnetic Effect, EM Induction, AC, Dual Nature, Atoms & Nuclei, Semiconductors — Maharashtra Board + NCERT Class 11 & 12',
      'Chemistry (50 MCQ): Solid State, Solutions, Ionic Equilibria, Chemical Thermodynamics, Electrochemistry, Chemical Kinetics, p/d/f Block, Coordination, Halogen Derivatives, Alcohols/Phenols/Ethers, Aldehydes/Ketones/Acids, Amines, Biomolecules, Polymers, Chemistry in Action',
      'Mathematics (50 MCQ, Paper I only): Trigonometry, Straight Line, Circle, Conics, Pairs of Lines, Vectors, 3D, Linear Programming, Matrices, Differentiation, Integration, DE, Probability, Statistics, Continuity, Applications of Derivatives',
      'Biology (50 MCQ, Paper II only): Genetics & Evolution, Biotechnology, Biology & Human Welfare, Plant Physiology, Human Reproduction, Ecology',
      'PCM: 150 MCQ, 200 marks (Maths +2, Phy/Chem +1) | PCB: 150 MCQ, 200 marks | 3 Hours | No Negative Marking',
    ],
    eligibility: ['12th Pass with PCM or PCB', 'Minimum 50% in PCM/PCB (45% for reserved)'],
    tnEligibility: 'Open to all Indian students for Maharashtra engineering/medical colleges.',
    importantDates: { registration: 'February 2026', examDate: 'April-May 2026', resultDate: 'June 2026' },
    applicationFee: { general: '₹800', scst: '₹600' },
    tnCollegesAccepting: ['COEP Pune', 'VJTI Mumbai', 'ICT Mumbai', '400+ Maharashtra Engineering Colleges'],
    officialWebsite: 'https://cetcell.mahacet.org',
    category: 'engineering',
  },
  {
    id: 'kcet',
    name: 'KCET',
    tamilName: 'கர்நாடகா CET',
    fullForm: 'Karnataka Common Entrance Test',
    conductingBody: 'Karnataka Examinations Authority (KEA)',
    examMode: 'Offline (OMR)',
    duration: '80 Minutes per paper',
    syllabus: [
      'Physics (60 MCQ): Physical World, Units, Kinematics, Laws of Motion, Work-Energy, Rotational Motion, Gravitation, Elasticity, Fluid Mechanics, Thermal Properties, Thermodynamics, Kinetic Theory, Oscillations, Waves, Electrostatics, Current, Magnetism, EMI, AC, EM Waves, Optics, Dual Nature, Atoms, Nuclei, Semiconductors',
      'Chemistry (60 MCQ): Atomic Structure, Classification, Chemical Bonding, States of Matter, Thermodynamics, Equilibrium, Redox, Hydrogen, s-block, p-block, Hydrocarbons, Environmental, Solid State, Solutions, Electrochemistry, Kinetics, Surface, d/f-block, Coordination, Haloalkanes, Alcohols, Aldehydes, Amines, Biomolecules',
      'Mathematics (60 MCQ — Engineering): Sets, Relations, Trigonometry, Complex Numbers, PnC, Binomial, Sequences, Straight Lines, Conics, Limits, Calculus, Mathematical Reasoning, Statistics, Probability, Vectors, 3D, Linear Programming',
      'Biology (60 MCQ — Medical/Agriculture): Diversity, Plant & Animal Kingdom, Cell Biology, Biomolecules, Morphology, Anatomy, Plant Physiology, Human Physiology, Reproduction, Genetics, Evolution, Biotechnology, Ecology, Human Health',
      'Total: 180 MCQ (PCM) or 180 MCQ (PCB) | 180 Marks | +1/0 No Negative | 1st & 2nd PUC Karnataka syllabus',
    ],
    eligibility: ['12th Pass (PUC) with PCM or PCB', 'Karnataka domicile preferred for government seat quota'],
    tnEligibility: 'TN students can apply for NRI/Management seats in Karnataka colleges.',
    importantDates: { registration: 'January 2026', examDate: 'April 2026', resultDate: 'May 2026' },
    applicationFee: { general: '₹650', scst: '₹500' },
    tnCollegesAccepting: ['RVCE Bangalore', 'BMS College', 'NIE Mysore', '200+ Karnataka Engineering Colleges'],
    officialWebsite: 'https://cetonline.karnataka.gov.in/kea',
    category: 'engineering',
  },
  {
    id: 'ap-eamcet',
    name: 'AP EAMCET',
    tamilName: 'ஆந்திர EAMCET',
    fullForm: 'Andhra Pradesh Engineering, Agriculture & Medical Common Entrance Test',
    conductingBody: 'JNTU (on behalf of APSCHE)',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 Hours',
    syllabus: [
      'Engineering — Mathematics (80 MCQ, 80 marks — 50%!): Algebra (Matrices, Quadratics, PnC, Binomial, Partial Fractions), Trigonometry, Vector Algebra, Probability, Coordinate Geometry (2D & 3D), Calculus (Limits, Differentiation, Integration, DE) — AP Intermediate syllabus',
      'Engineering — Physics (40 MCQ, 40 marks): Mechanics, Waves, Thermodynamics, Optics, Electrostatics, Current Electricity, Magnetism, EMI, AC, Modern Physics, Semiconductors',
      'Engineering — Chemistry (40 MCQ, 40 marks): Physical (Atomic Structure, States of Matter, Thermodynamics, Equilibrium, Kinetics, Electrochemistry), Organic (Hydrocarbons to Biomolecules), Inorganic (Periodic Table, p/d-block, Coordination)',
      'Agriculture/Medical — Biology (80 MCQ, 80 marks): Botany (Taxonomy, Morphology, Cell Biology, Plant Physiology, Genetics, Ecology) + Zoology (Animal Diversity, Human Physiology, Reproduction, Evolution, Biotechnology)',
      'Total: 160 MCQs | 160 Marks | 3 Hours | +1/0 No Negative | CBT Mode',
    ],
    eligibility: ['12th Pass (Intermediate) with PCM or PCB', 'Minimum 45% in relevant subjects'],
    tnEligibility: 'Open to students from AP and other states for AP engineering/medical colleges.',
    importantDates: { registration: 'March 2026', examDate: 'May 2026', resultDate: 'June 2026' },
    applicationFee: { general: '₹800', scst: '₹400' },
    tnCollegesAccepting: ['JNTU Kakinada, Hyderabad', 'SV University Tirupati', '300+ AP Engineering Colleges'],
    officialWebsite: 'https://cets.apsche.ap.gov.in',
    category: 'engineering',
  },

  // MANAGEMENT — Additional
  {
    id: 'ipm-iim',
    name: 'IPM Aptitude Test (IIM)',
    tamilName: 'IPM திறன் தேர்வு (IIM)',
    fullForm: 'Integrated Programme in Management — IIM Indore, Ranchi, Bodh Gaya, Jammu',
    conductingBody: 'IIM Indore / IIM Ranchi',
    examMode: 'Computer Based Test (CBT)',
    duration: '2 Hours',
    syllabus: [
      'Short Answer Test — SAT (60 MCQ, 60 min): Quantitative Ability — Arithmetic (Percentage, Profit-Loss, Time-Work, Mixtures), Algebra (Equations, Inequalities, Functions), Geometry (Triangles, Circles, Mensuration), Number System, Data Interpretation (Tables, Charts)',
      'Verbal Ability — SAT: Reading Comprehension (2-3 passages), Grammar (Error Detection, Sentence Correction), Vocabulary (Synonyms, Antonyms, Analogies), Para Jumbles, Sentence Completion',
      'Analytical & Logical Reasoning — SAT: Series, Coding-Decoding, Blood Relations, Syllogisms, Arrangements, Puzzles, Direction Sense, Data Sufficiency',
      'Written Ability Test — WAT (40 MCQ, 40 min): Extended Quantitative + Verbal + Logical questions at higher difficulty',
      'Total: 100 MCQs | 100 Minutes | +4/-1 Marking | Difficulty: Higher than CUET, similar to CAT-basics',
      'IIMs offering IPM: IIM Indore (flagship), IIM Ranchi, IIM Bodh Gaya, IIM Jammu, IIM Rohtak',
    ],
    eligibility: [
      '12th Pass (appearing/passed) with min 60% (55% for SC/ST)',
      'Must be born on or after August 1, 2003 (approximate)',
      'Direct entry into IIM — 5-year Integrated Programme in Management',
    ],
    tnEligibility: 'Open to all Indian students. One of the few ways to enter IIM directly after 12th.',
    importantDates: { registration: 'February 2026', examDate: 'May 2026', resultDate: 'June 2026' },
    applicationFee: { general: '₹4,130', scst: '₹2,065' },
    tnCollegesAccepting: ['IIM Indore (5-Year IPM)', 'IIM Ranchi (5-Year IPM)', 'IIM Bodh Gaya', 'IIM Jammu'],
    officialWebsite: 'https://www.iimidr.ac.in/academic-programmes/five-year-integrated-programme-in-management',
    category: 'management',
  },
  {
    id: 'set-symbiosis',
    name: 'SET (Symbiosis)',
    tamilName: 'SET (சிம்பயோசிஸ்)',
    fullForm: 'Symbiosis Entrance Test',
    conductingBody: 'Symbiosis International University, Pune',
    examMode: 'Online Test',
    duration: '2.5 Hours',
    syllabus: [
      'General English (16 MCQ): Reading Comprehension (2 passages), Verbal Reasoning, Vocabulary (Synonyms/Antonyms), Grammar (Error Detection, Sentence Completion), Idioms & Phrases, Para Jumbles',
      'Quantitative (16 MCQ): Arithmetic (Percentage, Ratio, SI/CI, Profit-Loss), Algebra, Data Interpretation (Tables, Charts, Graphs), Data Sufficiency, Number System, Geometry basics',
      'General Awareness (16 MCQ): Current National/International Affairs, Business & Economy news, Awards & Honours, Books & Authors, Science & Technology, Indian Polity & Constitution, Sports',
      'Analytical & Logical Reasoning (27 MCQ — Highest!): Series Completion, Analogies, Classification, Coding-Decoding, Blood Relations, Direction, Syllogisms, Seating Arrangement, Puzzles, Critical Reasoning, Input-Output',
      'Total: 75 MCQs | 75 Marks | 60 Minutes | +1/0 No Negative | CBT Mode | For all Symbiosis Pune UG programmes',
    ],
    eligibility: ['12th Pass (appearing/passed)', 'No minimum percentage required to apply'],
    tnEligibility: 'Open to all Indian students for Symbiosis Pune programmes.',
    importantDates: { registration: 'December 2025', examDate: 'May 2026', resultDate: 'May 2026' },
    applicationFee: { general: '₹1,750', scst: '₹1,750' },
    tnCollegesAccepting: ['SCMS Pune (BBA)', 'SSBF Pune (BBA Finance)', 'SLS Pune (BBA LLB)', 'All Symbiosis Pune campuses'],
    officialWebsite: 'https://set-test.org',
    category: 'management',
  },

  // DESIGN — Additional
  {
    id: 'uceed',
    name: 'UCEED (IIT Design)',
    tamilName: 'UCEED (IIT வடிவமைப்பு)',
    fullForm: 'Undergraduate Common Entrance Examination for Design',
    conductingBody: 'IIT Bombay (on rotation)',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 Hours',
    syllabus: [
      'Part A — Computer Based (240 marks, 2.5 hrs): Visualization & Spatial Ability (3D objects from 2D, Paper folding/cutting, Rotation, Mirror images), Observation & Design Sensitivity (Color theory, Visual patterns, Aesthetics, Typography, Design in everyday objects), Analytical & Logical Reasoning (Number/Letter series, Puzzles, Analogies), Language & Creativity (Storytelling, Lateral thinking), Environmental & Social Awareness',
      'Part B — Drawing on Paper (60 marks, 30 min): Freehand sketching, Drawing from memory, Perspective drawing, Proportion & scale, Composition using given shapes',
      'Total: 300 Marks | 3 Hours | Part A: MSQ (+4/-1) + NAT (+4/0) + MCQ (+3/-0.71)',
      'No fixed syllabus — tests natural design aptitude. Prepare by: drawing daily, observing everyday objects, studying color theory, visiting museums, practicing visual puzzles',
      'For IIT B.Des programmes at IIT Bombay, IIT Delhi, IIT Guwahati, IIITDM Jabalpur',
    ],
    eligibility: ['12th Pass (appearing/passed) in any stream', 'Maximum 2 attempts allowed', 'Born on or after October 1, 2001 (approximate)'],
    tnEligibility: 'Open to all Indian students. Gateway to IIT B.Des programmes.',
    importantDates: { registration: 'October 2025', examDate: 'January 2026', resultDate: 'March 2026' },
    applicationFee: { general: '₹3,600', scst: '₹1,800' },
    tnCollegesAccepting: ['IIT Bombay (B.Des)', 'IIT Delhi (B.Des)', 'IIT Guwahati (B.Des)', 'IIITDM Jabalpur (B.Des)'],
    officialWebsite: 'https://uceed.iitb.ac.in',
    category: 'design',
  },

  // DEFENCE — Additional
];


// Utility functions
export const getExamsByCategory = (category: string): EntranceExam[] => {
  return entranceExams.filter((exam) => exam.category === category);
};

export const getExamById = (id: string): EntranceExam | undefined => {
  return entranceExams.find((exam) => exam.id === id);
};

export const getCategoryInfo = (categoryId: string): CategoryInfo | undefined => {
  return examCategories.find((cat) => cat.id === categoryId);
};
