import { EntranceExam, CategoryInfo } from './types';

export const examCategories: CategoryInfo[] = [
  {
    id: 'engineering',
    label: 'Engineering',
    tamilLabel: 'பொறியியல்',
    icon: '⚙️',
    color: 'text-[#1976D2]',
    bgColor: 'bg-[#E3F2FD]',
    borderColor: 'border-[#1976D2]',
  },
  {
    id: 'medical',
    label: 'Medical & Health',
    tamilLabel: 'மருத்துவம்',
    icon: '🏥',
    color: 'text-[#D32F2F]',
    bgColor: 'bg-[#FFEBEE]',
    borderColor: 'border-[#D32F2F]',
  },
  {
    id: 'management',
    label: 'Management & Law',
    tamilLabel: 'மேலாண்மை & சட்டம்',
    icon: '💼',
    color: 'text-[#7B1FA2]',
    bgColor: 'bg-[#F3E5F5]',
    borderColor: 'border-[#7B1FA2]',
  },
  {
    id: 'agriculture',
    label: 'Agriculture',
    tamilLabel: 'வேளாண்மை',
    icon: '🌾',
    color: 'text-[#2E7D32]',
    bgColor: 'bg-[#E8F5E9]',
    borderColor: 'border-[#2E7D32]',
  },
  {
    id: 'design',
    label: 'Design & Arts',
    tamilLabel: 'வடிவமைப்பு',
    icon: '🎨',
    color: 'text-[#F59E0B]',
    bgColor: 'bg-[#FFF8E1]',
    borderColor: 'border-[#F59E0B]',
  },
];

export const entranceExams: EntranceExam[] = [
  // ============ ENGINEERING EXAMS ============
  {
    id: 'tnea',
    name: 'TNEA',
    tamilName: 'தமிழ்நாடு பொறியியல் சேர்க்கை',
    fullForm: 'Tamil Nadu Engineering Admissions',
    conductingBody: 'Anna University, Chennai',
    examMode: 'Merit Based (No Exam)',
    duration: 'N/A - Based on 12th marks',
    syllabus: [
      'No entrance exam — Merit based on 12th HSC marks',
      'TNEA Score = Physics×2 + Chemistry×1 + Maths×1 = out of 400',
      'Admissions via online counselling based on rank list',
    ],
    eligibility: [
      '12th HSC passed with PCM/PCB',
      'Min 50% (General), 45% (OBC), 40% (SC/ST)',
      'TN domicile or studied in TN',
    ],
    tnEligibility: 'Must be Tamil Nadu domicile or have studied in TN for 7+ years',
    importantDates: {
      registration: 'May 2026',
      examDate: 'N/A (Merit based)',
      resultDate: 'July 2026',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Anna University CEG, Chennai',
      'Anna University MIT, Chennai',
      'GCT Coimbatore',
      'PSG Tech, Coimbatore',
      'TCE Madurai',
      '455+ TN Engineering Colleges, 1.34 Lakh+ Seats',
    ],
    officialWebsite: 'https://www.tneaonline.org',
    category: 'engineering',
    hasJKKN: true,
    jkknColleges: [],
  },
  {
    id: 'jee-main',
    name: 'JEE Main',
    tamilName: 'ஜேஇஇ மெயின்',
    fullForm: 'Joint Entrance Examination Main',
    conductingBody: 'National Testing Agency (NTA)',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 hours',
    syllabus: [
      'Physics - 30 Questions (20 MCQ + 10 Numerical, attempt 25)',
      'Chemistry - 30 Questions (20 MCQ + 10 Numerical, attempt 25)',
      'Mathematics - 30 Questions (20 MCQ + 10 Numerical, attempt 25)',
      'Total: 90 Questions, 75 attempted | 300 Marks | 3 hrs',
      'MCQ: +4/-1 | Numerical: +4/0 (no negative)',
    ],
    eligibility: [
      '12th pass with PCM',
      '75% in 12th or top 20 percentile (65% for SC/ST)',
      '2 sessions per year (Jan & April)',
    ],
    tnEligibility: 'TN students can apply for NITs (15% All India + 85% State quota at NIT Trichy)',
    importantDates: {
      registration: 'November 2024',
      examDate: 'January & April 2026',
      resultDate: 'February & May 2026',
    },
    applicationFee: {
      general: '₹1,000',
      scst: '₹500',
    },
    tnCollegesAccepting: [
      'NIT Trichy (Top NIT)',
      'IIIT Tiruchirappalli',
      'IIT Madras (via JEE Advanced)',
      'Other NITs across India',
    ],
    officialWebsite: 'https://jeemain.nta.nic.in',
    category: 'engineering',
  },
  {
    id: 'jee-advanced',
    name: 'JEE Advanced',
    tamilName: 'ஜேஇஇ அட்வான்ஸ்ட்',
    fullForm: 'Joint Entrance Examination Advanced',
    conductingBody: 'IIT Madras (2026)',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 hours each (Paper 1 & 2)',
    syllabus: [
      'Paper 1 (3 hrs): Physics + Chemistry + Mathematics',
      'Paper 2 (3 hrs): Physics + Chemistry + Mathematics',
      'Each paper: ~54 Questions | ~360 Marks total',
      'Question types: MCQ (single/multi correct), Numerical, Matching',
      'Topics: Class 11-12 NCERT + deeper conceptual problems',
      'Partial marking for multi-correct MCQs',
    ],
    eligibility: [
      'Top 2,50,000 in JEE Main',
      'Age: Born after Oct 1, 2001 (approx)',
      'Maximum 2 consecutive attempts',
    ],
    tnEligibility: 'TN students eligible for IIT Madras (Chennai) - Premier institute in TN',
    importantDates: {
      registration: 'April 2026',
      examDate: 'May 2026',
      resultDate: 'June 2026',
    },
    applicationFee: {
      general: '₹2,800',
      scst: '₹1,400',
    },
    tnCollegesAccepting: [
      'IIT Madras, Chennai (#1 in India)',
      '23 IITs across India',
    ],
    officialWebsite: 'https://jeeadv.ac.in',
    category: 'engineering',
  },
  {
    id: 'viteee',
    name: 'VITEEE',
    tamilName: 'விஐடிஇஇஇ',
    fullForm: 'VIT Engineering Entrance Examination',
    conductingBody: 'VIT University, Vellore (TN)',
    examMode: 'Computer Based Test (CBT)',
    duration: '2 hours 30 minutes',
    syllabus: [
      'Physics - 35 Questions (140 marks)',
      'Chemistry - 35 Questions (140 marks)',
      'Maths/Biology - 40 Questions (160 marks)',
      'Aptitude - 10 Questions (40 marks)',
      'English - 5 Questions (20 marks)',
      'Total: 125 MCQs | 500 Marks | +4/-1 Marking',
    ],
    eligibility: [
      '12th with PCM/PCB',
      'Minimum 60% in PCM/PCB',
      'Born after July 1, 2003',
    ],
    tnEligibility: 'VIT Vellore is located in TN - Home state advantage for TN students',
    importantDates: {
      registration: 'November 2024',
      examDate: 'April-May 2026',
      resultDate: 'May 2026',
    },
    applicationFee: {
      general: '₹1,350',
      scst: '₹1,350',
    },
    tnCollegesAccepting: [
      'VIT Vellore (Main Campus, TN)',
      'VIT Chennai Campus',
      'VIT AP, VIT Bhopal',
    ],
    officialWebsite: 'https://viteee.vit.ac.in',
    category: 'engineering',
  },
  {
    id: 'srmjeee',
    name: 'SRMJEEE',
    tamilName: 'எஸ்ஆர்எம்ஜேஇஇஇ',
    fullForm: 'SRM Joint Engineering Entrance Examination',
    conductingBody: 'SRM Institute, Chennai (TN)',
    examMode: 'Computer Based Test (CBT)',
    duration: '2 hours 30 minutes',
    syllabus: [
      'Physics - 35 Questions (35 marks)',
      'Chemistry - 35 Questions (35 marks)',
      'Maths/Biology - 40 Questions (40 marks)',
      'English & Aptitude - 20 Questions (20 marks)',
      'Total: 130 MCQs | 130 Marks | +1/0 | No Negative Marking',
    ],
    eligibility: [
      '12th with PCM/PCB',
      'Minimum 50% aggregate',
      'No age limit',
    ],
    tnEligibility: 'SRM Kattankulathur is TN based - Priority for TN students in counselling',
    importantDates: {
      registration: 'October 2024',
      examDate: 'April-May 2026',
      resultDate: 'May 2026',
    },
    applicationFee: {
      general: '₹1,200',
      scst: '₹1,200',
    },
    tnCollegesAccepting: [
      'SRM Kattankulathur (Main, TN)',
      'SRM Ramapuram, Chennai',
      'SRM Vadapalani, Chennai',
    ],
    officialWebsite: 'https://srmist.edu.in',
    category: 'engineering',
  },
  {
    id: 'bitsat',
    name: 'BITSAT',
    tamilName: 'பிட்சாட்',
    fullForm: 'BITS Admission Test',
    conductingBody: 'BITS Pilani',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 hours',
    syllabus: [
      'Physics - 30 Questions (90 marks)',
      'Chemistry - 30 Questions (90 marks)',
      'English Proficiency - 10 Questions (30 marks)',
      'Logical Reasoning - 20 Questions (60 marks)',
      'Mathematics - 40 Questions (120 marks)',
      'Total: 130 MCQs | 390 Marks | +3/-1 Marking',
      '12 bonus questions if all 130 attempted',
    ],
    eligibility: [
      '12th with PCM',
      '75% aggregate, 60% each in PCM',
      'No age limit',
    ],
    tnEligibility: 'TN students eligible - BITS centers available in Chennai for exam',
    importantDates: {
      registration: 'January 2026',
      examDate: 'May-June 2026',
      resultDate: 'July 2026',
    },
    applicationFee: {
      general: '₹4,500',
      scst: '₹4,500',
    },
    tnCollegesAccepting: [
      'BITS Pilani',
      'BITS Goa',
      'BITS Hyderabad',
    ],
    officialWebsite: 'https://www.bitsadmission.com',
    category: 'engineering',
  },
  {
    id: 'aeee',
    name: 'AEEE ⭐',
    tamilName: 'அம்ரிதா பொறியியல் நுழைவுத் தேர்வு',
    fullForm: 'Amrita Engineering Entrance Examination — TN Campus!',
    conductingBody: 'Amrita Vishwa Vidyapeetham, Coimbatore',
    examMode: 'Computer Based Test (CBT)',
    duration: '2 hours 30 minutes',
    syllabus: [
      'Physics - 30 Questions (90 marks)',
      'Chemistry - 30 Questions (90 marks)',
      'Mathematics - 40 Questions (120 marks)',
      'Total: 100 MCQs | 300 Marks | +3/-1 Marking',
      'Syllabus: Class 11 & 12 NCERT (similar to JEE Main)',
    ],
    eligibility: [
      '12th with PCM — 55% aggregate',
      '55% individually in Maths, Physics, Chemistry',
      'No age limit',
    ],
    tnEligibility: 'Amrita Coimbatore & Chennai campuses are in TN — Home state advantage for TN students!',
    importantDates: {
      registration: 'November 2025',
      examDate: 'April 2026',
      resultDate: 'May 2026',
    },
    applicationFee: {
      general: '₹1,200',
      scst: '₹1,200',
    },
    tnCollegesAccepting: [
      'Amrita Vishwa Vidyapeetham, Coimbatore (Main TN Campus)',
      'Amrita Chennai Campus',
      'Amrita Bangalore, Amritapuri (Kerala)',
    ],
    officialWebsite: 'https://www.amrita.edu/admissions/btech',
    category: 'engineering',
  },

  // ============ MEDICAL & HEALTH EXAMS ============
  {
    id: 'neet-ug',
    name: 'NEET-UG ⭐',
    tamilName: 'நீட் - மருத்துவ நுழைவுத் தேர்வு',
    fullForm: 'National Eligibility cum Entrance Test (For MBBS/BDS/AYUSH/BVSc/B.Sc Nursing)',
    conductingBody: 'National Testing Agency (NTA)',
    examMode: 'Offline OMR Based',
    duration: '3 hrs 20 min',
    syllabus: [
      'Physics - 50 Questions (Section A: 35 mandatory + Section B: 15, attempt 10) = 180 marks',
      'Chemistry - 50 Questions (35 + 15, attempt 10) = 180 marks',
      'Botany - 50 Questions (35 + 15, attempt 10) = 180 marks',
      'Zoology - 50 Questions (35 + 15, attempt 10) = 180 marks',
      'Total: 200 Questions, 180 attempted | 720 Marks | +4/-1',
      '⭐ TAMIL Language Available ✓',
    ],
    eligibility: [
      '12th with PCB - 50% (40% SC/ST/OBC)',
      'Age: 17 years by Dec 31 of admission year',
      'Unlimited attempts',
      'MANDATORY for MBBS/BDS/BAMS/BHMS/BVSc',
    ],
    tnEligibility: '85% State Quota for TN + 7.5% for TN Govt School Students | Tamil medium exam available',
    importantDates: {
      registration: 'Feb 2026',
      examDate: 'May 4, 2026',
      resultDate: 'June 2026',
    },
    applicationFee: {
      general: '₹1,700',
      scst: '₹1,000',
    },
    tnCollegesAccepting: [
      '36 Govt Medical Colleges in TN',
      'AIIMS Madurai (All India Quota)',
      'Madras Medical College, Chennai',
      'Stanley Medical College',
      'Coimbatore Medical College',
      'Madurai Medical College',
      'Private Medical Colleges',
    ],
    officialWebsite: 'https://neet.nta.nic.in',
    category: 'medical',
  },
  {
    id: 'tn-neet-counselling',
    name: 'TN NEET Counselling ⭐',
    tamilName: 'தமிழ்நாடு மருத்துவ கலந்தாய்வு',
    fullForm: 'Tamil Nadu Medical Admission Counselling (85% Seats for TN!)',
    conductingBody: 'TN Medical Selection Committee',
    examMode: 'Online Counselling',
    duration: 'Based on NEET Rank',
    syllabus: [
      'No separate exam',
      'Based on NEET-UG Score',
      'Choice filling online',
      'Document verification',
    ],
    eligibility: [
      'Valid NEET-UG Score',
      'TN Domicile / TN Nativity',
      'Studied in TN for 7+ years',
      '7.5% for TN Govt School Students',
    ],
    tnEligibility: '85% seats reserved for TN students! Govt college fee only ~₹14,000/year!',
    importantDates: {
      registration: 'June 2026',
      examDate: 'N/A (Counselling)',
      resultDate: 'July-Aug 2026',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      '36 Govt Medical Colleges',
      '15 Self-Financing Colleges',
      'Deemed Universities (SRM, Saveetha)',
      'Fee: ~₹14,000/year (Govt)',
    ],
    officialWebsite: 'https://tnmedicalselection.net',
    category: 'medical',
  },
  {
    id: 'bds-dental',
    name: 'BDS - Dental',
    tamilName: 'பல் மருத்துவம்',
    fullForm: 'Bachelor of Dental Surgery',
    conductingBody: 'Through NEET Score',
    examMode: 'Via NEET Score',
    duration: '5 years course',
    syllabus: [
      'Admission through NEET',
      'Same NEET exam as MBBS',
      'Separate counselling for BDS',
    ],
    eligibility: [
      'Valid NEET Score',
      '12th with PCB - 50%',
      'Age: 17+ years',
    ],
    tnEligibility: 'TN state quota available - Govt Dental Colleges in Chennai & Madurai',
    importantDates: {
      registration: 'June 2026',
      examDate: 'Via NEET (May 2026)',
      resultDate: 'July 2026',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Govt Dental College, Chennai',
      'Govt Dental College, Madurai',
      'Meenakshi Dental College',
      'SRM Dental College',
      'Private Dental Colleges',
    ],
    officialWebsite: 'https://tnmedicalselection.net',
    category: 'medical',
  },
  {
    id: 'ayush-bams-bhms-bsms',
    name: 'AYUSH - BAMS/BHMS/BSMS',
    tamilName: 'ஆயுஷ் - சித்தா/ஆயுர்வேதா',
    fullForm: 'BAMS (Ayurveda) / BHMS (Homeopathy) / BSMS (Siddha)',
    conductingBody: 'Through NEET Score',
    examMode: 'Via NEET Score',
    duration: '5.5 years course',
    syllabus: [
      'Admission through NEET',
      'BSMS - Siddha Medicine (TN Special!)',
      'BAMS - Ayurvedic Medicine',
      'BHMS - Homeopathy',
    ],
    eligibility: [
      'Valid NEET Score',
      '12th with PCB - 50%',
      'Lower cutoff than MBBS',
    ],
    tnEligibility: 'BSMS (Siddha) is Tamil Nadu specialty! Govt Siddha Colleges available',
    importantDates: {
      registration: 'June 2026',
      examDate: 'Via NEET (May 2026)',
      resultDate: 'Aug 2026',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Govt Siddha Medical College, Palayamkottai',
      'Govt Siddha Medical College, Chennai',
      'Govt Homeopathy College, Tirumangalam',
      'Sri Sairam Siddha Medical College',
    ],
    officialWebsite: 'https://tnmedicalselection.net',
    category: 'medical',
  },
  {
    id: 'bsc-nursing',
    name: 'B.Sc Nursing ⭐',
    tamilName: 'செவிலியர் படிப்பு',
    fullForm: 'Bachelor of Science in Nursing',
    conductingBody: 'TN Dr. MGR Medical University',
    examMode: 'Merit Based (12th Marks)',
    duration: '4 years course',
    syllabus: [
      'Govt colleges: NEET score required',
      'Private colleges: Merit based (12th marks)',
      'AIIMS Nursing: Separate entrance exam',
      'JIPMER Nursing: Via NEET score',
    ],
    eligibility: [
      '12th with PCB - 45%',
      'Age: 17-35 years',
      'Female & Male both eligible',
    ],
    tnEligibility: 'Govt nursing colleges through TN counselling - Many private options available',
    importantDates: {
      registration: 'June 2026',
      examDate: 'N/A (Merit)',
      resultDate: 'July 2026',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Govt College of Nursing, Chennai',
      'MMC College of Nursing',
      'CMC Vellore Nursing',
      'Private Nursing Colleges',
    ],
    officialWebsite: 'https://tnmgrmu.ac.in',
    category: 'medical',
    hasJKKN: true,
    jkknColleges: [],
  },
  {
    id: 'bpharm',
    name: 'B.Pharm ⭐',
    tamilName: 'மருந்தியல் படிப்பு',
    fullForm: 'Bachelor of Pharmacy',
    conductingBody: 'TN Dr. MGR Medical University',
    examMode: 'Merit Based (12th Marks)',
    duration: '4 years course',
    syllabus: [
      'Based on 12th PCM/PCB Marks',
      'No entrance exam for most',
      'Direct merit admission',
    ],
    eligibility: [
      '12th with PCM or PCB - 50%',
      'Age: 17+ years',
      'Maths OR Biology accepted',
    ],
    tnEligibility: 'State quota for TN students in govt pharmacy colleges',
    importantDates: {
      registration: 'June 2026',
      examDate: 'N/A (Merit)',
      resultDate: 'July 2026',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Madras Medical College (Pharmacy)',
      'JSS College of Pharmacy, Ooty',
      'PSG College of Pharmacy',
      'SRM College of Pharmacy',
    ],
    officialWebsite: 'https://tnmgrmu.ac.in',
    category: 'medical',
    hasJKKN: true,
    jkknColleges: [],
  },
  {
    id: 'allied-health',
    name: 'Allied Health Sciences ⭐',
    tamilName: 'துணை சுகாதாரம்',
    fullForm: 'BPT / BOT / BMLT / B.Sc Radiology & more',
    conductingBody: 'TN Dr. MGR Medical University',
    examMode: 'Merit Based (12th Marks)',
    duration: '3-4 years course',
    syllabus: [
      'BPT - Physiotherapy',
      'BOT - Occupational Therapy',
      'BMLT - Medical Lab Technology',
      'B.Sc Radiology, Cardiac Tech',
      'Based on 12th PCB marks',
    ],
    eligibility: [
      '12th with PCB - 50%',
      'Age: 17-25 years',
      'TN domicile preferred',
    ],
    tnEligibility: 'Growing demand! Excellent job opportunities in hospitals across TN',
    importantDates: {
      registration: 'June 2026',
      examDate: 'N/A (Merit)',
      resultDate: 'July 2026',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'MMC Allied Health Sciences',
      'Stanley Medical College',
      'PSG IMS, Coimbatore',
      'SRM Allied Health',
    ],
    officialWebsite: 'https://tnmgrmu.ac.in',
    category: 'medical',
    hasJKKN: true,
    jkknColleges: [],
  },
  {
    id: 'jipmer-puducherry',
    name: 'JIPMER Puducherry',
    tamilName: 'ஜிப்மர் புதுச்சேரி',
    fullForm: 'Jawaharlal Institute of Postgraduate Medical Education',
    conductingBody: 'Through NEET Score',
    examMode: 'Via NEET Score',
    duration: '5.5 years MBBS',
    syllabus: [
      'Admission through NEET',
      'All India + Puducherry Quota',
      'MBBS, B.Sc Nursing, B.Sc Allied Health',
      'B.Sc Nursing now also via NEET (no separate exam)',
      'Premier Medical Institute near TN',
    ],
    eligibility: [
      'Valid NEET Score',
      '12th with PCB - 50%',
      'High NEET rank required',
    ],
    tnEligibility: 'Near Tamil Nadu - Very popular among TN students! Puducherry quota available',
    importantDates: {
      registration: 'June 2026',
      examDate: 'Via NEET (May 2026)',
      resultDate: 'July 2026',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'JIPMER Puducherry (Main)',
      'JIPMER Karaikal',
      'Government Institute',
      'Low fees, High quality',
    ],
    officialWebsite: 'https://jipmer.edu.in',
    category: 'medical',
  },
  {
    id: 'aiims-paramedical',
    name: 'AIIMS Paramedical Entrance',
    tamilName: 'எய்ம்ஸ் துணை மருத்துவ நுழைவுத் தேர்வு',
    fullForm: 'AIIMS B.Sc Paramedical / Allied Health Sciences Entrance',
    conductingBody: 'AIIMS, New Delhi',
    examMode: 'Computer Based Test (CBT)',
    duration: '90 minutes',
    syllabus: [
      '⚠️ NOT based on NEET — Separate exam!',
      'Physics - 30 MCQs',
      'Chemistry - 30 MCQs',
      'Biology/Mathematics - 30 MCQs',
      'Total: 90 MCQs',
    ],
    eligibility: [
      '12th pass with PCB or PCM',
      'Minimum 55% aggregate (50% SC/ST)',
      'Age: 17-21 years',
    ],
    tnEligibility: 'TN students eligible for AIIMS Madurai paramedical courses. Separate from NEET!',
    importantDates: {
      registration: 'April 2026',
      examDate: 'July 4, 2026',
      resultDate: 'August 2026',
    },
    applicationFee: {
      general: '₹1,500',
      scst: '₹1,200',
    },
    tnCollegesAccepting: [
      'AIIMS Madurai (TN)',
      'AIIMS New Delhi',
      'AIIMS Jodhpur, Bhopal, Rishikesh',
      'All AIIMS across India',
    ],
    officialWebsite: 'https://aiimsexams.ac.in',
    category: 'medical',
  },
  {
    id: 'aiims-bsc-nursing',
    name: 'AIIMS B.Sc Nursing Entrance',
    tamilName: 'எய்ம்ஸ் செவிலியர் நுழைவுத் தேர்வு',
    fullForm: 'AIIMS B.Sc (Hons.) Nursing & B.Sc (Post-Basic) Nursing Entrance',
    conductingBody: 'AIIMS, New Delhi',
    examMode: 'Computer Based Test (CBT)',
    duration: '90 minutes',
    syllabus: [
      '⚠️ NOT based on NEET — Separate exam!',
      'Physics, Chemistry, Biology — MCQs',
      'General Knowledge & Aptitude',
      'Based on 10+2 level',
    ],
    eligibility: [
      '12th pass with PCB - 55% (50% SC/ST)',
      'Age: 17-25 years',
      'Female & Male both eligible',
    ],
    tnEligibility: 'Alternative to NEET-based nursing admission. AIIMS nursing is prestigious with low fees.',
    importantDates: {
      registration: 'April 2026',
      examDate: 'June 2026',
      resultDate: 'July 2026',
    },
    applicationFee: {
      general: '₹1,500',
      scst: '₹1,200',
    },
    tnCollegesAccepting: [
      'AIIMS New Delhi (Nursing)',
      'AIIMS Madurai (if nursing available)',
      'AIIMS Jodhpur, Bhopal',
      'All AIIMS Nursing Colleges',
    ],
    officialWebsite: 'https://aiimsexams.ac.in',
    category: 'medical',
  },

  // ============ MANAGEMENT & LAW ============
  {
    id: 'tndalu',
    name: 'TNDALU Merit Admission ⭐',
    tamilName: 'தமிழ்நாடு அம்பேத்கர் சட்டப் பல்கலை',
    fullForm: 'Tamil Nadu Dr. Ambedkar Law University — No Entrance Exam!',
    conductingBody: 'TNDALU, Chennai',
    examMode: 'Merit Based (12th Marks) — NO EXAM',
    duration: 'N/A — Based on 12th marks & counselling',
    syllabus: [
      '⭐ NO ENTRANCE EXAM REQUIRED',
      'Selection based on Class 12 marks only',
      'Rank list released → Online counselling',
      'Courses: BA LLB, BCom LLB, BBA LLB, BCA LLB, BSc LLB (5-year integrated)',
      'Also: 3-year LLB for graduates',
    ],
    eligibility: [
      '12th pass from any recognized board',
      'Minimum 70% marks in 12th',
      'TN domicile preferred for govt colleges',
    ],
    tnEligibility: 'Easiest route for TN students! No exam needed — just score 70%+ in 12th. Govt college fee is very low.',
    importantDates: {
      registration: 'April-May 2026',
      examDate: 'N/A (Merit based)',
      resultDate: 'June-July 2026 (Counselling)',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Dr. Ambedkar Govt Law College, Chennai',
      'Govt Law College, Madurai',
      'Govt Law College, Coimbatore',
      'Govt Law College, Tirunelveli',
      'School of Excellence in Law, Chennai',
      'Private affiliated law colleges across TN',
    ],
    officialWebsite: 'https://tndalu.ac.in',
    category: 'management',
  },
  {
    id: 'clat',
    name: 'CLAT',
    tamilName: 'சட்டப் படிப்பு நுழைவுத் தேர்வு',
    fullForm: 'Common Law Admission Test — #1 National Law Entrance Exam',
    conductingBody: 'Consortium of NLUs',
    examMode: 'Offline (Pen & Paper)',
    duration: '2 hours',
    syllabus: [
      'English Language (~24Q, ~20%): Reading Comprehension, Vocabulary in Context, Grammar & Errors, Summary & Paraphrasing, Para Jumbles — 450-word passages',
      'Current Affairs & GK (~30Q, 25%): National/International News, Govt Schemes, Sports & Awards, Science & Tech, Environment + Static GK: History, Geography, Polity, Constitution, International Orgs',
      'Legal Reasoning (~30Q, 25%): Legal Principles & Fact Application, Torts, Contracts, Criminal Law (IPC), Constitutional Law, Family Law, Legal Maxims — No prior law knowledge needed, all principles given in passage',
      'Logical Reasoning (~24Q, ~20%): Syllogisms, Assumptions & Inferences, Strengthen/Weaken Arguments, Cause & Effect, Analogies, Critical Reasoning passages',
      'Quantitative Techniques (~14Q, ~10%): Percentage, Profit & Loss, Ratio, SI/CI, Time-Speed-Distance, Averages, Basic Algebra, Data Interpretation — 10th standard level only',
      'Total: 120 MCQs | 120 Marks | 2 Hours | Offline (Pen-Paper) | –0.25 per wrong answer',
    ],
    eligibility: [
      '12th pass any stream',
      'Minimum 45% (40% for SC/ST)',
      'No upper age limit',
    ],
    tnEligibility: 'Gateway to TNNLU Trichy (Tamil Nadu National Law University) + 25 other NLUs across India!',
    importantDates: {
      registration: 'Aug-Nov 2026',
      examDate: 'December 6, 2026 (CLAT 2027)',
      resultDate: 'Jan 2027',
    },
    applicationFee: {
      general: '₹4,000',
      scst: '₹3,500',
    },
    tnCollegesAccepting: [
      'TNNLU Tiruchirappalli (TN)',
      'NLSIU Bangalore',
      'NALSAR Hyderabad',
      'NLU Jodhpur',
      '26 NLUs + many private colleges accept CLAT scores',
    ],
    officialWebsite: 'https://consortiumofnlus.ac.in',
    category: 'management',
  },
  {
    id: 'ailet',
    name: 'AILET (NLU Delhi)',
    tamilName: 'AILET (என்எல்யூ டெல்லி)',
    fullForm: 'All India Law Entrance Test — For NLU Delhi Only',
    conductingBody: 'National Law University, Delhi',
    examMode: 'Offline (Pen & Paper)',
    duration: '2 hours',
    syllabus: [
      'English Language (50Q, 50 marks, 33%): Reading Comprehension, Sentence Correction, Fill in Blanks, Vocabulary (Synonyms/Antonyms), Para Jumbles, Grammar & Errors, Idioms & Phrases',
      'Current Affairs & GK (30Q, 30 marks, 20%): National/International Events, Indian History/Geography/Polity, Science & Tech, Sports & Awards, Legal Updates & Landmark Judgments, Constitution, Important Personalities',
      'Logical Reasoning (70Q, 70 marks, 47% — Highest!): Legal Propositions & Fact Application, Legal Maxims, Analogical Reasoning, Syllogisms, Statement-Conclusion, Blood Relations, Direction Sense, Number/Letter Series, Critical Reasoning, Data Sufficiency',
      'Total: 150 MCQs | 150 Marks | 2 Hours | Offline | –0.25 per wrong answer | No Mathematics section',
    ],
    eligibility: [
      '12th pass any stream',
      'Minimum 50% marks in 12th',
      'No age limit',
    ],
    tnEligibility: 'For NLU Delhi — India\'s 2nd best law college. Exam held in 35+ cities including Chennai.',
    importantDates: {
      registration: 'Sep-Nov 2026',
      examDate: 'December 2026',
      resultDate: 'Jan 2027',
    },
    applicationFee: {
      general: '₹3,500',
      scst: '₹1,500',
    },
    tnCollegesAccepting: [
      'National Law University, Delhi (exclusively)',
      'BA LLB (Hons.) — 5 year integrated programme',
    ],
    officialWebsite: 'https://nludelhi.ac.in',
    category: 'management',
  },
  {
    id: 'lsat-india',
    name: 'LSAT India',
    tamilName: 'LSAT இந்தியா',
    fullForm: 'Law School Admission Test — India (Pure Reasoning — No Law/GK/Maths!)',
    conductingBody: 'Pearson VUE (licensed by LSAC, USA)',
    examMode: 'Online / Offline',
    duration: '~2.5 hours (35 min per section)',
    syllabus: [
      'Analytical Reasoning (~23-24Q, 35 min): Linear Ordering, Sequencing, Grouping, Arrangements, Logical Puzzles — analyze relationships between people/objects/events',
      'Logical Reasoning Section 1 (~24-26Q, 35 min): Inference, Assumptions, Strengthen/Weaken Arguments, Parallel Reasoning, Flaws in Arguments, Method of Reasoning',
      'Logical Reasoning Section 2 (~24-26Q, 35 min): Same as Section 1 — evaluate, strengthen, or challenge arguments',
      'Reading Comprehension (~26-28Q, 35 min): 4 long complex passages, Main Point & Purpose, Inference, Author\'s Attitude & Tone, Structure of Argument, Comparative Reading (2 related passages)',
      'Total: ~92-100 Qs | Scored on 420-480 scale | No Negative Marking | No GK, No Maths, No Law knowledge needed — pure reasoning & reading!',
    ],
    eligibility: [
      '12th pass any stream',
      'Minimum 45% marks',
      'No age limit',
    ],
    tnEligibility: 'Accepted by top private law schools across India. Good for students strong in reasoning.',
    importantDates: {
      registration: 'Oct 2025 - May 2026',
      examDate: 'Jan & June 2026',
      resultDate: '3-4 weeks after exam',
    },
    applicationFee: {
      general: '₹3,999',
      scst: '₹3,999',
    },
    tnCollegesAccepting: [
      'Jindal Global Law School',
      'UPES Dehradun',
      'Christ University',
      'Alliance University',
      'Many premium private law colleges',
    ],
    officialWebsite: 'https://www.lsatindia.in',
    category: 'management',
  },
  {
    id: 'slat',
    name: 'SLAT (Symbiosis)',
    tamilName: 'SLAT (சிம்பயோசிஸ்)',
    fullForm: 'Symbiosis Law Admission Test',
    conductingBody: 'Symbiosis International University, Pune',
    examMode: 'Online Test',
    duration: '1 hour',
    syllabus: [
      'Logical Reasoning (12Q, 12 marks): Statements & Assumptions, Conclusions, Syllogisms, Analogies, Series, Blood Relations, Direction Sense, Coding & Decoding, Cause & Effect',
      'Legal Reasoning (12Q, 12 marks): Principle-Fact Based Questions, Law of Torts, Criminal Law (IPC basics), Constitutional Law (Fundamental Rights, Directive Principles), Contract Law, Legal Maxims, Court Judgments',
      'Analytical Reasoning (12Q, 12 marks): Puzzles (Seating, Floor Plans), Logical Deductions, Input-Output, Data Arrangements, Venn Diagrams, Complex Statements',
      'Reading Comprehension (12Q, 12 marks): General & Legal passages, Vocabulary in Context, Main Idea & Theme, Inference, Grammar-based questions',
      'General Knowledge (12Q, 12 marks): Current National/International Affairs, Indian History/Geography/Polity, Govt Schemes, Sports & Awards, Science & Environment',
      'Total: 60 MCQs | 60 Marks | 1 Hour | CBT Mode | No Negative Marking | Also: WAT + PI after shortlisting',
    ],
    eligibility: [
      '12th pass any stream',
      'Minimum 45% marks',
      'No age limit',
    ],
    tnEligibility: 'For Symbiosis Law Schools in Pune, Hyderabad, Noida, Nagpur — ~1000 seats across campuses.',
    importantDates: {
      registration: 'Dec 2025 - May 2026',
      examDate: 'May 2026',
      resultDate: 'May-June 2026',
    },
    applicationFee: {
      general: '₹1,750',
      scst: '₹1,750',
    },
    tnCollegesAccepting: [
      'Symbiosis Law School, Pune',
      'Symbiosis Law School, Hyderabad',
      'Symbiosis Law School, Noida',
      'Symbiosis Law School, Nagpur',
      'BA LLB & BBA LLB programmes',
    ],
    officialWebsite: 'https://set-test.org',
    category: 'management',
  },
  {
    id: 'bba-bca-bcom-direct',
    name: 'BBA/BCA/B.Com (Direct) ⭐',
    tamilName: 'BBA/BCA/B.Com நேரடி சேர்க்கை',
    fullForm: 'Direct Admission - No Entrance Exam',
    conductingBody: 'All TN Universities',
    examMode: 'Merit Based (12th Marks)',
    duration: '3 years course',
    syllabus: [
      'No entrance exam',
      'Based on 12th marks only',
      'Any stream accepted',
    ],
    eligibility: [
      '12th pass any stream',
      'Minimum 50% (varies)',
      'No age limit',
    ],
    tnEligibility: 'All TN universities accept 12th marks - Easy admission for TN students!',
    importantDates: {
      registration: 'May-June 2026',
      examDate: 'N/A (Merit)',
      resultDate: 'June-July 2026',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Madras University',
      'Anna University',
      'Bharathiar University',
      'All TN Colleges',
    ],
    officialWebsite: 'https://unom.ac.in',
    category: 'management',
    hasJKKN: true,
    jkknColleges: [],
  },
  {
    id: 'ca-cs-cma-foundation',
    name: 'CA/CS/CMA Foundation',
    tamilName: 'CA/CS/CMA அடித்தளப் படிப்பு',
    fullForm: 'Chartered Accountant / Company Secretary / Cost Accountant',
    conductingBody: 'ICAI / ICSI / ICMAI',
    examMode: 'Pen & Paper / Online',
    duration: '4 months foundation',
    syllabus: [
      'CA: Accounts, Law, Maths',
      'CS: Law, Economics, Accounts',
      'CMA: Accounts, Maths, Economics',
    ],
    eligibility: [
      'Can register after 12th',
      'Any stream accepted',
      'No minimum marks',
    ],
    tnEligibility: 'Start professional courses right after 12th! Exam centers across TN',
    importantDates: {
      registration: 'Anytime after 12th',
      examDate: 'May & Nov (CA/CMA), June & Dec (CS)',
      resultDate: '2 months after exam',
    },
    applicationFee: {
      general: '₹11,000-15,000',
      scst: 'Varies',
    },
    tnCollegesAccepting: [
      'Self-study / Coaching',
      'CA: icai.org',
      'CS: icsi.edu',
      'CMA: icmai.in',
    ],
    officialWebsite: 'https://icai.org',
    category: 'management',
  },

  // ============ AGRICULTURE ============
  {
    id: 'tnau',
    name: 'TNAU ⭐',
    tamilName: 'தமிழ்நாடு வேளாண் பல்கலைக்கழகம்',
    fullForm: 'Tamil Nadu Agricultural University (NO EXAM!)',
    conductingBody: 'TNAU, Coimbatore',
    examMode: 'Merit Based (12th Marks)',
    duration: '4 years B.Sc Agri',
    syllabus: [
      '⭐ NO ENTRANCE EXAM',
      'Based on 12th PCB/PCM marks',
      'Agriculture subject preference',
      'Cutoff based on aggregate',
    ],
    eligibility: [
      '12th with PCB/PCM - 50%',
      'TN domicile mandatory',
      'Age: 17-21 years',
    ],
    tnEligibility: '100% State Quota - Only TN students eligible! Low fees govt education',
    importantDates: {
      registration: 'May 2026',
      examDate: 'N/A (Merit)',
      resultDate: 'July 2026 (Counselling)',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'TNAU Coimbatore (Main)',
      'AC&RI Madurai',
      'AC&RI Trichy',
      'AC&RI Killikulam',
      '14+ TNAU Campuses',
    ],
    officialWebsite: 'https://tnau.ac.in',
    category: 'agriculture',
    hasJKKN: true,
    jkknColleges: [],
  },
  {
    id: 'tanuvas',
    name: 'TANUVAS - Veterinary',
    tamilName: 'கால்நடை மருத்துவம்',
    fullForm: 'TN Veterinary & Animal Sciences University',
    conductingBody: 'TANUVAS, Chennai',
    examMode: 'Via NEET Score',
    duration: '5.5 years B.V.Sc',
    syllabus: [
      'B.V.Sc: Through NEET Score',
      'B.F.Sc (Fisheries): 12th marks',
      'B.Tech Food: 12th PCM marks',
    ],
    eligibility: [
      'B.V.Sc: Valid NEET Score',
      '12th with PCB - 50%',
      'TN domicile mandatory',
    ],
    tnEligibility: 'Only TN students - Madras Veterinary College is one of the oldest in Asia!',
    importantDates: {
      registration: 'June 2026',
      examDate: 'Via NEET',
      resultDate: 'Aug 2026',
    },
    applicationFee: {
      general: '₹500',
      scst: '₹250',
    },
    tnCollegesAccepting: [
      'Madras Veterinary College, Chennai',
      'VC&RI Namakkal',
      'VC&RI Tirunelveli',
      'Fisheries College, Thoothukudi',
    ],
    officialWebsite: 'https://tanuvas.ac.in',
    category: 'agriculture',
  },
  {
    id: 'icar-aieea',
    name: 'ICAR AIEEA',
    tamilName: 'ஐசிஏஆர் தேசிய தேர்வு',
    fullForm: 'ICAR All India Entrance Examination',
    conductingBody: 'NTA for ICAR',
    examMode: 'Computer Based Test',
    duration: '2.5 hours',
    syllabus: [
      'Physics - 50 Questions',
      'Chemistry - 50 Questions',
      'Biology/Maths - 50 Questions',
      'Total: 150 Q, 600 Marks',
    ],
    eligibility: [
      '12th with PCB/PCM - 50%',
      'Age: 16.5+ years',
      'All India applicants',
    ],
    tnEligibility: 'For Central Agricultural Universities - ICAR quota in TNAU also available',
    importantDates: {
      registration: 'March 2026',
      examDate: 'June 2026',
      resultDate: 'July 2026',
    },
    applicationFee: {
      general: '₹1,000',
      scst: '₹500',
    },
    tnCollegesAccepting: [
      'TNAU (ICAR Quota)',
      'IARI New Delhi',
      'NDRI Karnal',
      '75+ ICAR Institutes',
    ],
    officialWebsite: 'https://icar.nta.nic.in',
    category: 'agriculture',
  },

  // ============ DESIGN & ARTS ============
  {
    id: 'nift-chennai',
    name: 'NIFT Chennai ⭐',
    tamilName: 'நிஃப்ட் சென்னை',
    fullForm: 'National Institute of Fashion Technology (TN Campus!)',
    conductingBody: 'NIFT',
    examMode: 'CAT + GAT + Situation Test',
    duration: '4 years B.Des',
    syllabus: [
      'CAT - Creative Ability Test',
      'GAT - General Ability Test',
      'Situation Test (shortlisted)',
      'Drawing & Design skills',
    ],
    eligibility: [
      '12th pass any stream',
      'No minimum marks',
      'Age: Below 24 years',
    ],
    tnEligibility: 'NIFT Chennai Campus in TN! Premier fashion design institute',
    importantDates: {
      registration: 'Oct-Dec 2024',
      examDate: 'Feb 2026',
      resultDate: 'April 2026',
    },
    applicationFee: {
      general: '₹2,500',
      scst: '₹1,250',
    },
    tnCollegesAccepting: [
      'NIFT Chennai (TN Campus)',
      'NIFT Delhi',
      'NIFT Mumbai',
      '18 NIFT Campuses',
    ],
    officialWebsite: 'https://nift.ac.in',
    category: 'design',
  },
  {
    id: 'nid-dat',
    name: 'NID DAT',
    tamilName: 'என்ஐடி வடிவமைப்பு தேர்வு',
    fullForm: 'National Institute of Design Entrance',
    conductingBody: 'NID, Ahmedabad',
    examMode: 'Prelims + Mains + Interview',
    duration: '4 years B.Des',
    syllabus: [
      'Design Aptitude Test',
      'Creative Ability',
      'Problem Solving',
      'Studio Test + Interview',
    ],
    eligibility: [
      '12th pass any stream',
      'No minimum marks',
      'Age: Below 20 years',
    ],
    tnEligibility: 'Premier design institute - Product, Graphic, Textile design courses',
    importantDates: {
      registration: 'Oct 2024',
      examDate: 'Jan 2026',
      resultDate: 'March 2026',
    },
    applicationFee: {
      general: '₹3,000',
      scst: '₹1,500',
    },
    tnCollegesAccepting: [
      'NID Ahmedabad',
      'NID Bangalore',
      'NID Andhra Pradesh',
    ],
    officialWebsite: 'https://nid.edu',
    category: 'design',
  },
  {
    id: 'jee-paper2-barch',
    name: 'JEE Main Paper 2 - B.Arch',
    tamilName: 'ஜேஇஇ கட்டிடக்கலை',
    fullForm: 'JEE Main Paper 2 for Architecture',
    conductingBody: 'NTA',
    examMode: 'CBT + Drawing',
    duration: '3 hours',
    syllabus: [
      'Mathematics - 25 Questions',
      'Aptitude - 50 Questions',
      'Drawing - 2 Questions',
      'Total: 400 Marks',
    ],
    eligibility: [
      '12th with Maths - 50%',
      'Physics, Chemistry required',
      'No age limit',
    ],
    tnEligibility: 'For B.Arch at NIT Trichy & Anna University School of Architecture',
    importantDates: {
      registration: 'Nov 2024',
      examDate: 'April 2026',
      resultDate: 'May 2026',
    },
    applicationFee: {
      general: '₹1,000',
      scst: '₹500',
    },
    tnCollegesAccepting: [
      'Anna University SAP',
      'NIT Trichy (B.Arch)',
      'SRM Architecture',
      'VIT School of Architecture',
    ],
    officialWebsite: 'https://jeemain.nta.nic.in',
    category: 'design',
  },

  // ============ DEFENCE & OTHERS ============
  {
    id: 'nchmct-jee',
    name: 'NCHMCT JEE ⭐',
    tamilName: 'ஹோட்டல் மேலாண்மை',
    fullForm: 'Hotel Management Entrance - IHM Chennai in TN!',
    conductingBody: 'NTA for NCHMCT',
    examMode: 'Computer Based Test',
    duration: '3 hours',
    syllabus: [
      'Numerical Ability - 30 Q',
      'Reasoning & Aptitude - 30 Q',
      'General Knowledge - 30 Q',
      'English Language - 60 Q',
      'Service Aptitude - 50 Q',
    ],
    eligibility: [
      '12th pass any stream',
      'Minimum 45% (40% SC/ST)',
      'Age: 25 years max (Gen)',
    ],
    tnEligibility: 'IHM Chennai is located in TN! State quota available for TN students',
    importantDates: {
      registration: 'Jan-March 2026',
      examDate: 'May 2026',
      resultDate: 'June 2026',
    },
    applicationFee: {
      general: '₹1,000',
      scst: '₹500',
    },
    tnCollegesAccepting: [
      'IHM Chennai (TN Campus)',
      'IHM Mumbai',
      'IHM Delhi',
      '21 Central IHMs',
    ],
    officialWebsite: 'https://nchmct.org',
    category: 'management',
  },
  // ═══ MISSING EXAMS ADDED — COMPLETE LIST FOR 12TH PASS ═══
  
  // ENGINEERING — State Level
  {
    id: 'cuet',
    name: 'CUET-UG',
    tamilName: 'மத்திய பல்கலை நுழைவுத் தேர்வு',
    fullForm: 'Common University Entrance Test — Undergraduate',
    conductingBody: 'National Testing Agency (NTA)',
    examMode: 'Computer Based Test (CBT)',
    duration: '45 min per section (Slot-wise)',
    syllabus: [
      'Section IA: 13 Languages (choose any)',
      'Section IB: 20 Languages (choose any)',
      'Section II: 27 Domain Subjects (choose up to 6) — Physics, Chemistry, Math, Biology, Economics, History, Political Science, etc.',
      'Section III: General Test — GK, Quantitative Reasoning, Logical Reasoning, Current Affairs, General Awareness',
      'Standard: Based on Class 12 NCERT syllabus',
      'Also for Allied Health & Biomedical Sciences at Central Universities',
    ],
    eligibility: [
      '12th Pass from any recognized board',
      'No minimum percentage for application',
      'University-specific cutoffs may apply',
    ],
    tnEligibility: 'TN HSC students eligible. Many central universities accept CUET for UG admissions.',
    importantDates: { registration: 'February 2026', examDate: 'May 2026', resultDate: 'June 2026' },
    applicationFee: { general: '₹650', scst: '₹550' },
    tnCollegesAccepting: [
      'Central University of Tamil Nadu (CUTN)',
      'Pondicherry University',
      'University of Delhi (DU)',
      'JNU, BHU, AMU, Jamia Millia',
      '261+ Central, State & Private Universities across India',
    ],
    officialWebsite: 'https://cuet.nta.nic.in',
    category: 'engineering',
  },
  {
    id: 'comedk',
    name: 'COMEDK UGET',
    tamilName: 'கொமெடிகே',
    fullForm: 'Consortium of Medical, Engineering & Dental Colleges of Karnataka',
    conductingBody: 'COMEDK',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 Hours',
    syllabus: [
      'Physics: Mechanics, Electricity, Magnetism, Optics, Modern Physics (12th level)',
      'Chemistry: Physical, Organic, Inorganic Chemistry (12th level)',
      'Mathematics: Algebra, Calculus, Coordinate Geometry, Trigonometry, Probability',
      '180 MCQs — 60 each in Physics, Chemistry, Mathematics',
    ],
    eligibility: [
      '12th Pass with PCM (Physics, Chemistry, Mathematics)',
      'Minimum 45% in PCM (40% for SC/ST/OBC)',
      'Indian National or NRI/PIO/OCI',
    ],
    tnEligibility: 'TN students can apply for Karnataka private engineering colleges via COMEDK.',
    importantDates: { registration: 'January 2026', examDate: 'May 2026', resultDate: 'June 2026' },
    applicationFee: { general: '₹1,800', scst: '₹1,800' },
    tnCollegesAccepting: ['700+ Private Engineering Colleges in Karnataka', 'RV College, BMS, MSRIT, PES University, etc.'],
    officialWebsite: 'https://www.comedk.org',
    category: 'engineering',
  },
  {
    id: 'wbjee',
    name: 'WBJEE',
    tamilName: 'மேற்கு வங்காள ஜேஇஇ',
    fullForm: 'West Bengal Joint Entrance Examination',
    conductingBody: 'WBJEEB',
    examMode: 'Offline (OMR)',
    duration: '2 Hours per paper',
    syllabus: [
      'Paper I: Mathematics — 75 MCQs (Algebra, Calculus, Coordinate Geometry, Trigonometry)',
      'Paper II: Physics + Chemistry — 40 Physics + 40 Chemistry MCQs',
      'Difficulty: 12th Class (HSC) level, NCERT based',
    ],
    eligibility: ['12th Pass with PCM', 'Minimum 45% in PCM aggregate'],
    tnEligibility: 'Open to all Indian students for WB engineering colleges.',
    importantDates: { registration: 'December 2025', examDate: 'April 2026', resultDate: 'June 2026' },
    applicationFee: { general: '₹500', scst: '₹400' },
    tnCollegesAccepting: ['Jadavpur University', 'IIEST Shibpur', 'Heritage Institute', '200+ WB Engineering Colleges'],
    officialWebsite: 'https://wbjeeb.nic.in',
    category: 'engineering',
  },
  {
    id: 'mht-cet',
    name: 'MHT CET',
    tamilName: 'மகாராஷ்டிரா CET',
    fullForm: 'Maharashtra Common Entrance Test',
    conductingBody: 'State CET Cell, Maharashtra',
    examMode: 'Computer Based Test (CBT)',
    duration: '90 Minutes per paper',
    syllabus: [
      'Paper I (PCM): Physics (50 Qs), Chemistry (50 Qs), Mathematics (50 Qs) — 150 MCQs',
      'Paper II (PCB): Physics (50 Qs), Chemistry (50 Qs), Biology (50 Qs) — 150 MCQs',
      'Standard: Class 11 & 12 Maharashtra State Board + NCERT',
      'Marking: +2 for Maths, +1 for Physics/Chemistry/Biology',
    ],
    eligibility: ['12th Pass with PCM or PCB', 'Minimum 50% in PCM/PCB (45% for reserved)'],
    tnEligibility: 'Open to all Indian students for Maharashtra engineering/medical colleges.',
    importantDates: { registration: 'February 2026', examDate: 'April-May 2026', resultDate: 'June 2026' },
    applicationFee: { general: '₹800', scst: '₹600' },
    tnCollegesAccepting: ['COEP Pune', 'VJTI Mumbai', 'ICT Mumbai', '400+ Maharashtra Engineering Colleges'],
    officialWebsite: 'https://cetcell.mahacet.org',
    category: 'engineering',
  },
  {
    id: 'kcet',
    name: 'KCET',
    tamilName: 'கர்நாடகா CET',
    fullForm: 'Karnataka Common Entrance Test',
    conductingBody: 'Karnataka Examinations Authority (KEA)',
    examMode: 'Offline (OMR)',
    duration: '80 Minutes per paper',
    syllabus: [
      'Biology: 60 MCQs (for medical/dental/agriculture)',
      'Mathematics: 60 MCQs (for engineering)',
      'Physics: 60 MCQs',
      'Chemistry: 60 MCQs',
      'Standard: 1st & 2nd PUC (Class 11 & 12 Karnataka)',
    ],
    eligibility: ['12th Pass (PUC) with PCM or PCB', 'Karnataka domicile preferred for government seat quota'],
    tnEligibility: 'TN students can apply for NRI/Management seats in Karnataka colleges.',
    importantDates: { registration: 'January 2026', examDate: 'April 2026', resultDate: 'May 2026' },
    applicationFee: { general: '₹650', scst: '₹500' },
    tnCollegesAccepting: ['RVCE Bangalore', 'BMS College', 'NIE Mysore', '200+ Karnataka Engineering Colleges'],
    officialWebsite: 'https://cetonline.karnataka.gov.in/kea',
    category: 'engineering',
  },
  {
    id: 'ap-eamcet',
    name: 'AP EAMCET',
    tamilName: 'ஆந்திர EAMCET',
    fullForm: 'Andhra Pradesh Engineering, Agriculture & Medical Common Entrance Test',
    conductingBody: 'JNTU (on behalf of APSCHE)',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 Hours',
    syllabus: [
      'Engineering: Maths (80 Qs) + Physics (40 Qs) + Chemistry (40 Qs) = 160 MCQs',
      'Agriculture/Medical: Biology (80 Qs) + Physics (40 Qs) + Chemistry (40 Qs) = 160 MCQs',
      'Standard: Class 11 & 12 (Intermediate) level',
    ],
    eligibility: ['12th Pass (Intermediate) with PCM or PCB', 'Minimum 45% in relevant subjects'],
    tnEligibility: 'Open to students from AP and other states for AP engineering/medical colleges.',
    importantDates: { registration: 'March 2026', examDate: 'May 2026', resultDate: 'June 2026' },
    applicationFee: { general: '₹800', scst: '₹400' },
    tnCollegesAccepting: ['JNTU Kakinada, Hyderabad', 'SV University Tirupati', '300+ AP Engineering Colleges'],
    officialWebsite: 'https://cets.apsche.ap.gov.in',
    category: 'engineering',
  },

  // MANAGEMENT — Additional
  {
    id: 'ipm-iim',
    name: 'IPM Aptitude Test (IIM)',
    tamilName: 'IPM திறன் தேர்வு (IIM)',
    fullForm: 'Integrated Programme in Management — IIM Indore, Ranchi, Bodh Gaya, Jammu',
    conductingBody: 'IIM Indore / IIM Ranchi',
    examMode: 'Computer Based Test (CBT)',
    duration: '2 Hours',
    syllabus: [
      'Quantitative Ability: Arithmetic, Algebra, Geometry, Data Interpretation',
      'Verbal Ability: Reading Comprehension, Grammar, Vocabulary, Para Jumbles',
      'Logical Reasoning: Puzzles, Arrangements, Blood Relations, Coding',
      '60 MCQs, 60 Minutes + 40 MCQs, 40 Minutes = 100 MCQs total',
    ],
    eligibility: [
      '12th Pass (appearing/passed) with min 60% (55% for SC/ST)',
      'Must be born on or after August 1, 2003 (approximate)',
      'Direct entry into IIM — 5-year Integrated Programme in Management',
    ],
    tnEligibility: 'Open to all Indian students. One of the few ways to enter IIM directly after 12th.',
    importantDates: { registration: 'February 2026', examDate: 'May 2026', resultDate: 'June 2026' },
    applicationFee: { general: '₹4,130', scst: '₹2,065' },
    tnCollegesAccepting: ['IIM Indore (5-Year IPM)', 'IIM Ranchi (5-Year IPM)', 'IIM Bodh Gaya', 'IIM Jammu'],
    officialWebsite: 'https://www.iimidr.ac.in/academic-programmes/five-year-integrated-programme-in-management',
    category: 'management',
  },
  {
    id: 'set-symbiosis',
    name: 'SET (Symbiosis)',
    tamilName: 'SET (சிம்பயோசிஸ்)',
    fullForm: 'Symbiosis Entrance Test',
    conductingBody: 'Symbiosis International University, Pune',
    examMode: 'Online Test',
    duration: '2.5 Hours',
    syllabus: [
      'General English: Reading Comprehension, Verbal Reasoning, Verbal Ability',
      'Quantitative: Data Interpretation, Data Sufficiency, Analytical & Logical Reasoning',
      'General Awareness: Current Affairs, Business/Economy, Static GK',
      '75 MCQs total',
    ],
    eligibility: ['12th Pass (appearing/passed)', 'No minimum percentage required to apply'],
    tnEligibility: 'Open to all Indian students for Symbiosis Pune programmes.',
    importantDates: { registration: 'December 2025', examDate: 'May 2026', resultDate: 'May 2026' },
    applicationFee: { general: '₹1,750', scst: '₹1,750' },
    tnCollegesAccepting: ['SCMS Pune (BBA)', 'SSBF Pune (BBA Finance)', 'SLS Pune (BBA LLB)', 'All Symbiosis Pune campuses'],
    officialWebsite: 'https://set-test.org',
    category: 'management',
  },

  // DESIGN — Additional
  {
    id: 'uceed',
    name: 'UCEED (IIT Design)',
    tamilName: 'UCEED (IIT வடிவமைப்பு)',
    fullForm: 'Undergraduate Common Entrance Examination for Design',
    conductingBody: 'IIT Bombay (on rotation)',
    examMode: 'Computer Based Test (CBT)',
    duration: '3 Hours',
    syllabus: [
      'Part A (Computer Based): Visualization & Spatial Ability, Observation & Design Sensitivity, Analytical & Logical Reasoning, Language & Creativity, Design Thinking',
      'Part B (Drawing — on paper): Sketching ability, Drawing skills, Proportion & Perspective',
      'No fixed syllabus — tests innate design aptitude and creativity',
    ],
    eligibility: ['12th Pass (appearing/passed) in any stream', 'Maximum 2 attempts allowed', 'Born on or after October 1, 2001 (approximate)'],
    tnEligibility: 'Open to all Indian students. Gateway to IIT B.Des programmes.',
    importantDates: { registration: 'October 2025', examDate: 'January 2026', resultDate: 'March 2026' },
    applicationFee: { general: '₹3,600', scst: '₹1,800' },
    tnCollegesAccepting: ['IIT Bombay (B.Des)', 'IIT Delhi (B.Des)', 'IIT Guwahati (B.Des)', 'IIITDM Jabalpur (B.Des)'],
    officialWebsite: 'https://uceed.iitb.ac.in',
    category: 'design',
  },

  // DEFENCE — Additional
];


// Utility functions
export const getExamsByCategory = (category: string): EntranceExam[] => {
  return entranceExams.filter((exam) => exam.category === category);
};

export const getExamById = (id: string): EntranceExam | undefined => {
  return entranceExams.find((exam) => exam.id === id);
};

export const getCategoryInfo = (categoryId: string): CategoryInfo | undefined => {
  return examCategories.find((cat) => cat.id === categoryId);
};
