import { PracticeQuestion } from './types';

// ═══════════════════════════════════════════════════════════════
// NEET UG — 60 Questions (Biology 30, Chemistry 15, Physics 15)
// Chapter-wise, NCERT-based, real exam difficulty
// ═══════════════════════════════════════════════════════════════
export const neetQuestions: PracticeQuestion[] = [
  // BOTANY — Class 11
  { id: 'nb-1', question: 'Which of the following is NOT a characteristic of Kingdom Monera?', options: ['Prokaryotic cells', 'Membrane-bound organelles', 'Cell wall present', 'Binary fission'], answer: 1, explanation: 'Monera (bacteria) are prokaryotic — they lack membrane-bound organelles like mitochondria, ER, and nucleus.', subject: 'Biology', difficulty: 'easy' },
  { id: 'nb-2', question: 'Transpiration pull theory was proposed by:', options: ['J.C. Bose', 'Dixon and Joly', 'Münch', 'Curtis'], answer: 1, explanation: 'Dixon and Joly (1894) proposed the Cohesion-Tension Theory (transpiration pull) explaining ascent of sap in tall trees.', subject: 'Biology', difficulty: 'medium' },
  { id: 'nb-3', question: 'In C4 plants, the primary CO₂ acceptor is:', options: ['RuBisCO', 'PEP carboxylase', 'PGA', 'OAA'], answer: 1, explanation: 'In C4 plants (like sugarcane, maize), PEP carboxylase fixes CO₂ into OAA in mesophyll cells. RuBisCO works only in bundle sheath cells.', subject: 'Biology', difficulty: 'medium' },
  { id: 'nb-4', question: 'During which phase of the cell cycle does DNA replication occur?', options: ['G1 phase', 'S phase', 'G2 phase', 'M phase'], answer: 1, explanation: 'DNA synthesis/replication occurs during the S (Synthesis) phase of interphase. DNA content doubles from 2n to 4n.', subject: 'Biology', difficulty: 'easy' },
  { id: 'nb-5', question: 'Kranz anatomy is a characteristic of:', options: ['C3 plants', 'C4 plants', 'CAM plants', 'All plants'], answer: 1, explanation: 'Kranz anatomy (wreath-like arrangement of bundle sheath cells with large chloroplasts) is characteristic of C4 plants.', subject: 'Biology', difficulty: 'medium' },
  { id: 'nb-6', question: 'The enzyme that catalyzes the conversion of pyruvate to acetyl CoA is:', options: ['Pyruvate kinase', 'Pyruvate dehydrogenase', 'Pyruvate carboxylase', 'Phosphofructokinase'], answer: 1, explanation: 'Pyruvate dehydrogenase complex converts pyruvate to acetyl CoA (with release of CO₂ and NADH) in the mitochondrial matrix.', subject: 'Biology', difficulty: 'medium' },
  { id: 'nb-7', question: 'Which phytohormone is known as the "stress hormone"?', options: ['Auxin', 'Gibberellin', 'Abscisic acid', 'Cytokinin'], answer: 2, explanation: 'Abscisic acid (ABA) is called the stress hormone because it helps plants respond to drought, salinity, and cold stress by closing stomata.', subject: 'Biology', difficulty: 'easy' },
  // BOTANY — Class 12
  { id: 'nb-8', question: 'Double fertilization in angiosperms involves fusion of:', options: ['One sperm with egg and another with polar nuclei', 'Two sperms with egg only', 'One sperm with synergids', 'Two eggs with pollen'], answer: 0, explanation: 'Double fertilization: one sperm fuses with egg → zygote (2n), other sperm fuses with two polar nuclei → Primary Endosperm Nucleus (3n).', subject: 'Biology', difficulty: 'easy' },
  { id: 'nb-9', question: 'In Mendel\'s dihybrid cross, the phenotypic ratio in F₂ is:', options: ['3:1', '9:3:3:1', '1:2:1', '1:1:1:1'], answer: 1, explanation: 'Mendel\'s dihybrid cross (RrYy × RrYy) gives 9:3:3:1 ratio — 9 round yellow : 3 round green : 3 wrinkled yellow : 1 wrinkled green.', subject: 'Biology', difficulty: 'easy' },
  { id: 'nb-10', question: 'The process of copying genetic information from one strand of DNA to RNA is called:', options: ['Translation', 'Transcription', 'Replication', 'Transduction'], answer: 1, explanation: 'Transcription is the process of synthesizing mRNA from a DNA template, catalyzed by RNA polymerase.', subject: 'Biology', difficulty: 'easy' },
  { id: 'nb-11', question: 'Which of the following is NOT a feature of genetic code?', options: ['Triplet', 'Degenerate', 'Ambiguous', 'Universal'], answer: 2, explanation: 'The genetic code is NOT ambiguous — each codon codes for only ONE amino acid. It IS degenerate (multiple codons for same amino acid).', subject: 'Biology', difficulty: 'medium' },
  { id: 'nb-12', question: 'Hardy-Weinberg equilibrium is disturbed by all EXCEPT:', options: ['Gene flow', 'Genetic drift', 'Random mating', 'Natural selection'], answer: 2, explanation: 'Random mating maintains Hardy-Weinberg equilibrium. Gene flow, drift, mutation, selection, and non-random mating disturb it.', subject: 'Biology', difficulty: 'medium' },
  { id: 'nb-13', question: 'Bt toxin kills insects by:', options: ['Blocking nerve signals', 'Creating pores in gut lining', 'Destroying DNA', 'Inhibiting respiration'], answer: 1, explanation: 'Bt toxin (Cry protein) creates pores in the midgut epithelial cells of insects, causing cell swelling, lysis and death.', subject: 'Biology', difficulty: 'medium' },
  { id: 'nb-14', question: 'In an ecosystem, the flow of energy is:', options: ['Bidirectional', 'Unidirectional', 'Cyclic', 'Multidirectional'], answer: 1, explanation: 'Energy flow in an ecosystem is always unidirectional — from sun → producers → consumers. It cannot be recycled (unlike nutrients).', subject: 'Biology', difficulty: 'easy' },
  { id: 'nb-15', question: 'The 10% law of energy transfer was given by:', options: ['Odum', 'Lindeman', 'Tansley', 'Haeckel'], answer: 1, explanation: 'Lindeman (1942) proposed the 10% law: only ~10% of energy is transferred from one trophic level to the next.', subject: 'Biology', difficulty: 'medium' },
  // ZOOLOGY — Class 11
  { id: 'nz-1', question: 'The excretory organs of earthworm are:', options: ['Flame cells', 'Malpighian tubules', 'Nephridia', 'Green glands'], answer: 2, explanation: 'Earthworms have nephridia for excretion. Flame cells are in Platyhelminthes. Malpighian tubules in insects. Green glands in crustaceans.', subject: 'Biology', difficulty: 'easy' },
  { id: 'nz-2', question: 'SA node is called the pacemaker of the heart because it:', options: ['Is the largest node', 'Generates electrical impulses that initiate heartbeat', 'Supplies blood to the heart', 'Controls blood pressure'], answer: 1, explanation: 'SA (Sinoatrial) node in the right atrium generates rhythmic electrical impulses (70-75/min) that initiate each heartbeat.', subject: 'Biology', difficulty: 'easy' },
  { id: 'nz-3', question: 'Which part of the nephron is impermeable to water?', options: ['PCT', 'DCT', 'Ascending limb of loop of Henle', 'Collecting duct'], answer: 2, explanation: 'The ascending limb of the loop of Henle is impermeable to water but permeable to NaCl — this creates the concentration gradient for counter-current mechanism.', subject: 'Biology', difficulty: 'medium' },
  { id: 'nz-4', question: 'Synapse is the gap between:', options: ['Two bones', 'Two muscle cells', 'Two neurons', 'Neuron and muscle'], answer: 2, explanation: 'A synapse is the junction between two neurons where nerve impulses are transmitted via neurotransmitters (like acetylcholine).', subject: 'Biology', difficulty: 'easy' },
  { id: 'nz-5', question: 'Which hormone is secreted by the corpus luteum?', options: ['Estrogen only', 'Progesterone mainly', 'FSH', 'LH'], answer: 1, explanation: 'The corpus luteum (formed from ruptured Graafian follicle after ovulation) primarily secretes progesterone, which maintains the uterine endometrium for pregnancy.', subject: 'Biology', difficulty: 'medium' },
  // ZOOLOGY — Class 12
  { id: 'nz-6', question: 'The process of formation of sperms from spermatogonia is called:', options: ['Oogenesis', 'Spermiogenesis', 'Spermatogenesis', 'Spermiation'], answer: 2, explanation: 'Spermatogenesis is the complete process: spermatogonia → primary spermatocyte → secondary spermatocyte → spermatids → sperms.', subject: 'Biology', difficulty: 'easy' },
  { id: 'nz-7', question: 'Down syndrome is caused by trisomy of chromosome number:', options: ['18', '21', '13', '23'], answer: 1, explanation: 'Down syndrome (47 chromosomes) is caused by trisomy of chromosome 21 (three copies instead of two). Also called Trisomy 21.', subject: 'Biology', difficulty: 'easy' },
  { id: 'nz-8', question: 'Which type of immunity is provided by vaccination?', options: ['Natural active immunity', 'Artificial active immunity', 'Natural passive immunity', 'Artificial passive immunity'], answer: 1, explanation: 'Vaccination provides artificial active immunity — antigens are artificially introduced, and the body produces its own antibodies and memory cells.', subject: 'Biology', difficulty: 'medium' },
  { id: 'nz-9', question: 'HIV attacks which type of cells in the human body?', options: ['Red blood cells', 'Helper T cells (CD4+)', 'B cells only', 'Platelets'], answer: 1, explanation: 'HIV primarily attacks helper T cells (CD4+ lymphocytes), destroying them and weakening the immune system, leading to AIDS.', subject: 'Biology', difficulty: 'easy' },
  { id: 'nz-10', question: 'Cancer cells differ from normal cells because they show:', options: ['Contact inhibition', 'Uncontrolled division', 'Differentiation', 'Apoptosis'], answer: 1, explanation: 'Cancer cells lose contact inhibition and divide uncontrollably, forming tumors. Normal cells stop dividing when they contact other cells.', subject: 'Biology', difficulty: 'easy' },
  // NEET PHYSICS (15 questions)
  { id: 'np-1', question: 'A body is thrown vertically upward. At the highest point:', options: ['Both velocity and acceleration are zero', 'Velocity is zero but acceleration is g', 'Velocity is maximum', 'Acceleration is zero'], answer: 1, explanation: 'At highest point: velocity = 0 (momentarily stops) but acceleration = g (9.8 m/s²) downward always acts due to gravity.', subject: 'Physics', difficulty: 'easy' },
  { id: 'np-2', question: 'Two identical charged spheres are touched and separated. If initial charges are +6μC and -2μC, charge on each after touching:', options: ['+4μC', '+2μC', '+3μC', '-2μC'], answer: 1, explanation: 'When identical spheres touch, total charge distributes equally. Total = +6 + (-2) = +4μC. Each gets +4/2 = +2μC.', subject: 'Physics', difficulty: 'easy' },
  { id: 'np-3', question: 'The equivalent resistance of 2Ω and 3Ω in parallel is:', options: ['5Ω', '1.2Ω', '6Ω', '0.83Ω'], answer: 1, explanation: '1/R = 1/2 + 1/3 = (3+2)/6 = 5/6. So R = 6/5 = 1.2Ω. Parallel resistance is always less than the smallest individual resistance.', subject: 'Physics', difficulty: 'easy' },
  { id: 'np-4', question: 'The focal length of a concave mirror is 10 cm. An object is placed at 15 cm. The image is:', options: ['Virtual and erect', 'Real and inverted, at 30 cm', 'Virtual and magnified', 'At infinity'], answer: 1, explanation: 'Using 1/f = 1/v + 1/u: 1/(-10) = 1/v + 1/(-15). 1/v = -1/10 + 1/15 = (-3+2)/30 = -1/30. v = -30 cm. Real, inverted, magnified.', subject: 'Physics', difficulty: 'medium' },
  { id: 'np-5', question: 'In photoelectric effect, the maximum kinetic energy of photoelectrons depends on:', options: ['Intensity of light', 'Frequency of light', 'Number of photons', 'Area of metal surface'], answer: 1, explanation: 'KEmax = hf - φ (Einstein equation). KE depends on frequency (f) of incident light, NOT intensity. Higher frequency = higher KE.', subject: 'Physics', difficulty: 'medium' },
  { id: 'np-6', question: 'The dimension of Planck\'s constant is same as:', options: ['Energy', 'Angular momentum', 'Linear momentum', 'Force'], answer: 1, explanation: 'Planck constant h has units J·s = kg·m²/s. Angular momentum (L = mvr) also has units kg·m²/s. Same dimensions: [ML²T⁻¹].', subject: 'Physics', difficulty: 'medium' },
  { id: 'np-7', question: 'A transformer has 100 turns in primary and 500 in secondary. If input voltage is 220V, output voltage is:', options: ['44V', '1100V', '880V', '220V'], answer: 1, explanation: 'Vs/Vp = Ns/Np. Vs = 220 × (500/100) = 220 × 5 = 1100V. This is a step-up transformer.', subject: 'Physics', difficulty: 'easy' },
  { id: 'np-8', question: 'The work done in moving a charge of 5C across a potential difference of 12V is:', options: ['60 J', '2.4 J', '17 J', '7 J'], answer: 0, explanation: 'W = qV = 5 × 12 = 60 J. Work done = charge × potential difference.', subject: 'Physics', difficulty: 'easy' },
  { id: 'np-9', question: 'In a pure inductive AC circuit, current lags voltage by:', options: ['0°', '90°', '180°', '45°'], answer: 1, explanation: 'In a pure inductor, current lags behind voltage by exactly 90° (π/2 radians). Mnemonic: ELI (E leads I in inductor L).', subject: 'Physics', difficulty: 'medium' },
  { id: 'np-10', question: 'The binding energy per nucleon is maximum for:', options: ['Hydrogen', 'Uranium-238', 'Iron-56', 'Helium-4'], answer: 2, explanation: 'Iron-56 has the highest binding energy per nucleon (~8.8 MeV). This is why elements lighter than Fe undergo fusion and heavier ones undergo fission.', subject: 'Physics', difficulty: 'medium' },
  // NEET CHEMISTRY (15 questions)
  { id: 'nc-1', question: 'The number of moles of CO₂ that contain 3.011 × 10²³ molecules is:', options: ['0.25', '0.5', '1', '2'], answer: 1, explanation: '1 mole = 6.022 × 10²³. Moles = 3.011 × 10²³ / 6.022 × 10²³ = 0.5 moles.', subject: 'Chemistry', difficulty: 'easy' },
  { id: 'nc-2', question: 'The hybridization of carbon in ethene (C₂H₄) is:', options: ['sp', 'sp²', 'sp³', 'sp³d'], answer: 1, explanation: 'In ethene, each carbon forms 3 sigma bonds (2 C-H + 1 C-C) and 1 pi bond. Three sigma bonds require sp² hybridization (trigonal planar, 120°).', subject: 'Chemistry', difficulty: 'easy' },
  { id: 'nc-3', question: 'Which of the following is the strongest acid?', options: ['HF', 'HCl', 'HBr', 'HI'], answer: 3, explanation: 'Acid strength increases down the group: HF < HCl < HBr < HI. HI is the strongest because the H-I bond is weakest and easiest to break.', subject: 'Chemistry', difficulty: 'medium' },
  { id: 'nc-4', question: 'In SN1 reaction, the rate depends on:', options: ['Both substrate and nucleophile', 'Only substrate concentration', 'Only nucleophile concentration', 'Solvent only'], answer: 1, explanation: 'SN1 is unimolecular — Rate = k[substrate]. The slow step is carbocation formation, which depends only on substrate concentration.', subject: 'Chemistry', difficulty: 'medium' },
  { id: 'nc-5', question: 'The IUPAC name of CH₃-CO-CH₃ is:', options: ['Acetone', 'Propanone', 'Propanal', 'Propanoic acid'], answer: 1, explanation: 'CH₃COCH₃ is a ketone with 3 carbons. IUPAC: propan- (3C) + -one (ketone) = Propanone. Acetone is the common name.', subject: 'Chemistry', difficulty: 'easy' },
  { id: 'nc-6', question: 'Which of the following has the highest lattice energy?', options: ['NaCl', 'NaBr', 'NaI', 'NaF'], answer: 3, explanation: 'Lattice energy ∝ (charge)/(size). NaF has the smallest anion (F⁻), so it has the highest lattice energy among sodium halides.', subject: 'Chemistry', difficulty: 'medium' },
  { id: 'nc-7', question: 'The coordination number of Fe in [Fe(CN)₆]⁴⁻ is:', options: ['2', '4', '6', '8'], answer: 2, explanation: 'Coordination number = number of ligands directly bonded to metal. CN⁻ is a monodentate ligand. 6 CN⁻ ligands → coordination number = 6.', subject: 'Chemistry', difficulty: 'easy' },
  { id: 'nc-8', question: 'Which polymer is a natural polymer?', options: ['PVC', 'Nylon', 'Cellulose', 'Teflon'], answer: 2, explanation: 'Cellulose is a natural polymer of glucose. PVC, Nylon, and Teflon are all synthetic polymers.', subject: 'Chemistry', difficulty: 'easy' },
  { id: 'nc-9', question: 'The element with electronic configuration [Ar] 3d⁵ 4s¹ is:', options: ['Mn', 'Fe', 'Cr', 'V'], answer: 2, explanation: 'Chromium (Cr, Z=24) has [Ar] 3d⁵ 4s¹ (not 3d⁴ 4s²) due to extra stability of half-filled d orbitals.', subject: 'Chemistry', difficulty: 'medium' },
  { id: 'nc-10', question: 'Aspirin is chemically known as:', options: ['Methyl salicylate', 'Acetyl salicylic acid', 'Benzoic acid', 'Phenol'], answer: 1, explanation: 'Aspirin = Acetyl salicylic acid. It is an analgesic (pain reliever) and antipyretic (fever reducer) used widely as a drug.', subject: 'Chemistry', difficulty: 'easy' },
];

// ═══════════════════════════════════════════════════════════════
// JEE MAIN — 50 Questions (Physics 17, Chemistry 16, Maths 17)
// ═══════════════════════════════════════════════════════════════
export const jeeMainQuestions: PracticeQuestion[] = [
  // JEE PHYSICS
  { id: 'jp-1', question: 'A ball is thrown vertically upward with velocity 20 m/s. The maximum height reached is (g = 10 m/s²):', options: ['10 m', '20 m', '30 m', '40 m'], answer: 1, explanation: 'Using v² = u² - 2gh. At max height v=0: h = u²/2g = (20)²/(2×10) = 400/20 = 20 m.', subject: 'Physics', difficulty: 'easy' },
  { id: 'jp-2', question: 'A block of mass 5 kg on a rough surface (μ=0.4) needs a horizontal force to start moving (g=10):', options: ['10N', '20N', '30N', '40N'], answer: 1, explanation: 'F = μmg = 0.4 × 5 × 10 = 20N. This is the minimum force to overcome static friction.', subject: 'Physics', difficulty: 'easy' },
  { id: 'jp-3', question: 'Two capacitors 3μF and 6μF are connected in series. The equivalent capacitance is:', options: ['9μF', '2μF', '4.5μF', '1μF'], answer: 1, explanation: '1/C = 1/3 + 1/6 = (2+1)/6 = 3/6 = 1/2. C = 2μF. Series capacitance is always less than the smallest.', subject: 'Physics', difficulty: 'easy' },
  { id: 'jp-4', question: 'The de Broglie wavelength of an electron accelerated through potential V is:', options: ['√(2meV)/h', 'h/√(2meV)', '2meV/h', 'h²/2meV'], answer: 1, explanation: 'λ = h/p = h/√(2mKE) = h/√(2meV). Where KE = eV for an electron accelerated through potential V.', subject: 'Physics', difficulty: 'medium' },
  { id: 'jp-5', question: 'In Young\'s double slit experiment, if slit width is halved, fringe width:', options: ['Halved', 'Doubled', 'Unchanged', 'Quadrupled'], answer: 1, explanation: 'Fringe width β = λD/d. If d (slit separation) is halved, β doubles. Fringe width is inversely proportional to slit separation.', subject: 'Physics', difficulty: 'medium' },
  { id: 'jp-6', question: 'The moment of inertia of a solid sphere about its diameter is:', options: ['MR²', '2/5 MR²', '2/3 MR²', '1/2 MR²'], answer: 1, explanation: 'Moment of inertia of solid sphere about diameter = 2/5 MR². This is a standard result derived by integration.', subject: 'Physics', difficulty: 'medium' },
  { id: 'jp-7', question: 'The escape velocity from Earth is approximately:', options: ['7.9 km/s', '11.2 km/s', '15.4 km/s', '3.2 km/s'], answer: 1, explanation: 'Escape velocity Ve = √(2gR) = √(2 × 9.8 × 6400000) ≈ 11.2 km/s. Independent of mass of the object.', subject: 'Physics', difficulty: 'easy' },
  { id: 'jp-8', question: 'In an RC circuit, the time constant τ is:', options: ['R/C', 'RC', 'R+C', '1/RC'], answer: 1, explanation: 'Time constant τ = RC. It represents the time for capacitor to charge to 63.2% of maximum value (or discharge to 36.8%).', subject: 'Physics', difficulty: 'medium' },
  // JEE CHEMISTRY
  { id: 'jc-1', question: 'The number of moles in 36 g of water (H₂O, MW=18) is:', options: ['1', '2', '3', '4'], answer: 1, explanation: 'Moles = mass/MW = 36/18 = 2 moles.', subject: 'Chemistry', difficulty: 'easy' },
  { id: 'jc-2', question: 'For an exothermic reaction, ΔH is:', options: ['Positive', 'Negative', 'Zero', 'Cannot be determined'], answer: 1, explanation: 'Exothermic reactions release heat → products have lower energy than reactants → ΔH < 0 (negative).', subject: 'Chemistry', difficulty: 'easy' },
  { id: 'jc-3', question: 'The oxidation state of Mn in KMnO₄ is:', options: ['+2', '+4', '+5', '+7'], answer: 3, explanation: 'In KMnO₄: K is +1, each O is -2. +1 + x + 4(-2) = 0. x - 7 = 0. x = +7.', subject: 'Chemistry', difficulty: 'easy' },
  { id: 'jc-4', question: 'The pH of 0.01 M HCl solution is:', options: ['1', '2', '3', '0.01'], answer: 1, explanation: 'HCl is a strong acid, fully dissociates. [H⁺] = 0.01 = 10⁻². pH = -log(10⁻²) = 2.', subject: 'Chemistry', difficulty: 'easy' },
  { id: 'jc-5', question: 'Grignard reagent is:', options: ['RMgBr', 'RLi', 'RZnCl', 'RNa'], answer: 0, explanation: 'Grignard reagent = RMgX (where X = halide). e.g., CH₃MgBr. Used extensively in organic synthesis for C-C bond formation.', subject: 'Chemistry', difficulty: 'easy' },
  { id: 'jc-6', question: 'Which has maximum number of unpaired electrons?', options: ['Fe²⁺', 'Fe³⁺', 'Mn²⁺', 'Cu²⁺'], answer: 2, explanation: 'Mn²⁺ = [Ar]3d⁵ has 5 unpaired electrons (maximum). Fe³⁺ also has 5, but Mn²⁺ and Fe³⁺ tie. Fe²⁺ has 4, Cu²⁺ has 1.', subject: 'Chemistry', difficulty: 'medium' },
  { id: 'jc-7', question: 'Lucas reagent is used to distinguish between:', options: ['Alkenes and alkynes', '1°, 2°, and 3° alcohols', 'Aldehydes and ketones', 'Acids and esters'], answer: 1, explanation: 'Lucas reagent (conc. HCl + ZnCl₂) distinguishes alcohols: 3° reacts immediately (turbid), 2° in 5 min, 1° very slowly/no reaction.', subject: 'Chemistry', difficulty: 'medium' },
  { id: 'jc-8', question: 'The rate constant of a first-order reaction has units:', options: ['mol/L/s', 's⁻¹', 'L/mol/s', 'mol²/L²/s'], answer: 1, explanation: 'For first-order: Rate = k[A]. k = Rate/[A] = (mol/L/s)/(mol/L) = s⁻¹. The unit is always time inverse for first order.', subject: 'Chemistry', difficulty: 'medium' },
  // JEE MATHS
  { id: 'jm-1', question: 'If sin θ = 3/5, then cos θ is:', options: ['4/5', '3/4', '5/3', '5/4'], answer: 0, explanation: 'sin²θ + cos²θ = 1. cos²θ = 1 - 9/25 = 16/25. cos θ = 4/5 (in first quadrant).', subject: 'Maths', difficulty: 'easy' },
  { id: 'jm-2', question: 'The derivative of x³ with respect to x is:', options: ['x²', '3x²', '3x³', 'x³/3'], answer: 1, explanation: 'Power rule: d/dx(xⁿ) = nxⁿ⁻¹. d/dx(x³) = 3x².', subject: 'Maths', difficulty: 'easy' },
  { id: 'jm-3', question: '∫₀¹ 2x dx equals:', options: ['0', '1', '2', '½'], answer: 1, explanation: '∫₀¹ 2x dx = [x²]₀¹ = 1² - 0² = 1.', subject: 'Maths', difficulty: 'easy' },
  { id: 'jm-4', question: 'The number of ways to arrange 5 books on a shelf is:', options: ['25', '120', '60', '10'], answer: 1, explanation: '5! = 5 × 4 × 3 × 2 × 1 = 120. Arrangement of n distinct items = n!', subject: 'Maths', difficulty: 'easy' },
  { id: 'jm-5', question: 'In the expansion of (1+x)ⁿ, the coefficient of x² is:', options: ['n', 'n(n-1)/2', 'n²', '2n'], answer: 1, explanation: 'By binomial theorem: C(n,2) = n!/(2!(n-2)!) = n(n-1)/2.', subject: 'Maths', difficulty: 'medium' },
  { id: 'jm-6', question: 'The equation of a circle with centre (2,3) and radius 5 is:', options: ['(x-2)²+(y-3)²=25', '(x+2)²+(y+3)²=25', '(x-2)²+(y-3)²=5', 'x²+y²=25'], answer: 0, explanation: 'Standard form: (x-h)² + (y-k)² = r². Centre (2,3), r=5: (x-2)² + (y-3)² = 25.', subject: 'Maths', difficulty: 'easy' },
  { id: 'jm-7', question: 'The rank of the matrix [[1,2],[2,4]] is:', options: ['0', '1', '2', '3'], answer: 1, explanation: 'Row 2 = 2 × Row 1, so rows are linearly dependent. Rank = number of linearly independent rows = 1.', subject: 'Maths', difficulty: 'medium' },
  { id: 'jm-8', question: 'If a⃗ = 2î+3ĵ and b⃗ = î-ĵ, then a⃗·b⃗ is:', options: ['5', '-1', '1', '7'], answer: 1, explanation: 'a⃗·b⃗ = (2)(1) + (3)(-1) = 2 - 3 = -1. Dot product = sum of products of corresponding components.', subject: 'Maths', difficulty: 'easy' },
  { id: 'jm-9', question: 'The probability of getting exactly 2 heads in 3 tosses of a fair coin:', options: ['1/8', '3/8', '1/2', '1/4'], answer: 1, explanation: 'P = C(3,2) × (1/2)² × (1/2)¹ = 3 × 1/4 × 1/2 = 3/8. Using binomial probability.', subject: 'Maths', difficulty: 'medium' },
];

// ═══════════════════════════════════════════════════════════════
// CLAT — 40 Questions across 5 sections
// ═══════════════════════════════════════════════════════════════
export const clatQuestions: PracticeQuestion[] = [
  // LEGAL REASONING
  { id: 'cl-1', question: 'The minimum age to become a member of Rajya Sabha is:', options: ['25 years', '30 years', '35 years', '21 years'], answer: 1, explanation: 'Article 84 of the Constitution prescribes minimum age of 30 years for Rajya Sabha membership (25 for Lok Sabha).', subject: 'Legal Aptitude', difficulty: 'easy' },
  { id: 'cl-2', question: 'Right to Education is a fundamental right under which Article?', options: ['Article 19', 'Article 21', 'Article 21A', 'Article 14'], answer: 2, explanation: 'Article 21A (86th Amendment, 2002) makes free and compulsory education for children aged 6-14 a fundamental right.', subject: 'Legal Aptitude', difficulty: 'medium' },
  { id: 'cl-3', question: 'Writ of Habeas Corpus ensures:', options: ['Freedom of speech', 'Personal liberty of detained person', 'Right to property', 'Right to vote'], answer: 1, explanation: 'Habeas Corpus = "produce the body." It protects personal liberty by requiring a detained person to be brought before the court.', subject: 'Legal Aptitude', difficulty: 'easy' },
  { id: 'cl-4', question: 'The concept of Judicial Review was borrowed from:', options: ['UK', 'USA', 'Canada', 'France'], answer: 1, explanation: 'Judicial Review — courts can examine constitutionality of laws — borrowed from USA (established in Marbury v. Madison, 1803).', subject: 'Legal Aptitude', difficulty: 'medium' },
  { id: 'cl-5', question: 'Principle: Negligence means failure to exercise reasonable care. Fact: A doctor leaves surgical instruments inside a patient after surgery. The doctor is:', options: ['Not liable, as it was unintentional', 'Liable for negligence', 'Liable only if patient complains', 'Not liable due to informed consent'], answer: 1, explanation: 'Leaving instruments inside a patient is a clear breach of duty of care — this constitutes medical negligence under tort law.', subject: 'Legal Aptitude', difficulty: 'medium' },
  { id: 'cl-6', question: '"Ignorantia juris non excusat" means:', options: ['Ignorance of fact is excused', 'Ignorance of law is no excuse', 'Justice delayed is justice denied', 'Let the buyer beware'], answer: 1, explanation: 'This Latin maxim means ignorance of law is no excuse — a person cannot escape liability by claiming they did not know the law.', subject: 'Legal Aptitude', difficulty: 'easy' },
  { id: 'cl-7', question: 'The age of criminal responsibility in India is:', options: ['7 years', '12 years', '14 years', '18 years'], answer: 0, explanation: 'Under Section 82 IPC, nothing is an offence done by a child under 7 years. Children under 7 have complete immunity from criminal liability.', subject: 'Legal Aptitude', difficulty: 'medium' },
  { id: 'cl-8', question: 'A valid contract requires all EXCEPT:', options: ['Free consent', 'Lawful consideration', 'Written document', 'Competent parties'], answer: 2, explanation: 'A contract needs: offer, acceptance, free consent, lawful consideration, competent parties. A written document is NOT always required — oral contracts are valid.', subject: 'Legal Aptitude', difficulty: 'medium' },
  // ENGLISH
  { id: 'ce-1', question: 'Choose the synonym of "Prudent":', options: ['Reckless', 'Wise and careful', 'Arrogant', 'Lazy'], answer: 1, explanation: 'Prudent = acting with or showing care and thought for the future. Wise and careful is the closest synonym.', subject: 'English', difficulty: 'easy' },
  { id: 'ce-2', question: '"The ball is in your court" means:', options: ['Play a sport', 'It is your turn to act', 'You are guilty', 'Go to court'], answer: 1, explanation: 'This idiom means it is now your responsibility or turn to take action.', subject: 'English', difficulty: 'easy' },
  { id: 'ce-3', question: 'Choose the correctly punctuated sentence:', options: ['Its a lovely day.', "It's a lovely day.", "Its' a lovely day.", 'Its, a lovely day.'], answer: 1, explanation: '"It\'s" = contraction of "it is." "Its" (without apostrophe) is possessive.', subject: 'English', difficulty: 'easy' },
  { id: 'ce-4', question: 'Choose the antonym of "Benevolent":', options: ['Kind', 'Generous', 'Malevolent', 'Gentle'], answer: 2, explanation: 'Benevolent = well-meaning, kind. Malevolent = having evil intent. They are exact opposites.', subject: 'English', difficulty: 'easy' },
  // GK & CURRENT AFFAIRS
  { id: 'cg-1', question: 'Who is known as the Father of the Indian Constitution?', options: ['Nehru', 'B.R. Ambedkar', 'Gandhi', 'Patel'], answer: 1, explanation: 'Dr. B.R. Ambedkar was Chairman of the Drafting Committee and principal architect of the Indian Constitution.', subject: 'General Knowledge', difficulty: 'easy' },
  { id: 'cg-2', question: 'The Supreme Court of India was established on:', options: ['26 January 1950', '28 January 1950', '15 August 1947', '26 November 1949'], answer: 1, explanation: 'Supreme Court came into being on 28 January 1950, two days after India became a Republic.', subject: 'General Knowledge', difficulty: 'medium' },
  { id: 'cg-3', question: 'Which Article of Indian Constitution provides for equality before law?', options: ['Article 14', 'Article 19', 'Article 21', 'Article 32'], answer: 0, explanation: 'Article 14: "The State shall not deny to any person equality before the law or the equal protection of the laws."', subject: 'General Knowledge', difficulty: 'easy' },
  { id: 'cg-4', question: 'Panchayati Raj system was constitutionalized by which Amendment?', options: ['42nd', '44th', '73rd', '86th'], answer: 2, explanation: 'The 73rd Constitutional Amendment (1992) gave constitutional status to Panchayati Raj institutions (Part IX).', subject: 'General Knowledge', difficulty: 'medium' },
  // LOGICAL REASONING
  { id: 'clo-1', question: 'Statement: All lawyers are honest. All honest people are respected. Conclusion:', options: ['All lawyers are respected', 'Some respected are not lawyers', 'All respected are lawyers', 'None of the above'], answer: 0, explanation: 'All lawyers → honest → respected. Therefore: All lawyers are respected (valid syllogistic conclusion).', subject: 'Reasoning', difficulty: 'medium' },
  { id: 'clo-2', question: 'A is B\'s brother. C is A\'s mother. D is C\'s father. E is B\'s son. D is E\'s:', options: ['Grandfather', 'Great-grandfather', 'Father', 'Uncle'], answer: 1, explanation: 'D is C\'s father (grandfather of A & B). E is B\'s son (D\'s great-grandson). So D is E\'s great-grandfather.', subject: 'Reasoning', difficulty: 'hard' },
  { id: 'clo-3', question: 'If COMPUTER is coded as DPNQVUFS, then DATA is coded as:', options: ['EBUB', 'EBUC', 'ECUB', 'DBUB'], answer: 0, explanation: 'Each letter shifted +1: D→E, A→B, T→U, A→B = EBUB.', subject: 'Reasoning', difficulty: 'easy' },
  { id: 'clo-4', question: 'Complete: 2, 6, 12, 20, 30, ?', options: ['40', '42', '44', '36'], answer: 1, explanation: 'Pattern: n(n+1). 1×2=2, 2×3=6, 3×4=12, 4×5=20, 5×6=30, 6×7=42.', subject: 'Reasoning', difficulty: 'medium' },
  // QUANTITATIVE
  { id: 'cq-1', question: 'If a shirt costs ₹800 after 20% discount, the original price was:', options: ['₹960', '₹1000', '₹1100', '₹640'], answer: 1, explanation: '80% of original = 800. Original = 800/0.8 = ₹1000.', subject: 'Quantitative', difficulty: 'easy' },
  { id: 'cq-2', question: 'A train travels 240 km in 4 hours. Its speed is:', options: ['40 km/h', '60 km/h', '80 km/h', '120 km/h'], answer: 1, explanation: 'Speed = Distance/Time = 240/4 = 60 km/h.', subject: 'Quantitative', difficulty: 'easy' },
];

// ═══ REMAINING EXAMS — Enhanced questions ═══
export const cuetQuestions: PracticeQuestion[] = [
  { id: 'cuet-e1', question: 'Choose the synonym of "Abundant":', options: ['Scarce', 'Plentiful', 'Rare', 'Limited'], answer: 1, explanation: 'Abundant = existing in large quantities. Plentiful is the closest synonym.', subject: 'English', difficulty: 'easy' },
  { id: 'cuet-e2', question: '"Break the ice" means:', options: ['To break something', 'To start a conversation', 'To freeze water', 'To end a friendship'], answer: 1, explanation: '"Break the ice" = initiate a conversation or ease social tension.', subject: 'English', difficulty: 'easy' },
  { id: 'cuet-g1', question: 'The Tropic of Cancer passes through how many Indian states?', options: ['6', '7', '8', '9'], answer: 2, explanation: '8 states: Gujarat, Rajasthan, MP, Chhattisgarh, Jharkhand, West Bengal, Tripura, Mizoram.', subject: 'General Knowledge', difficulty: 'medium' },
  { id: 'cuet-g2', question: 'Who wrote "Jana Gana Mana"?', options: ['Bankim Chandra', 'Rabindranath Tagore', 'Sarojini Naidu', 'Subhash Chandra Bose'], answer: 1, explanation: 'Rabindranath Tagore wrote "Jana Gana Mana" in Bengali. Adopted as national anthem on 24 January 1950.', subject: 'General Knowledge', difficulty: 'easy' },
  { id: 'cuet-m1', question: 'If A = {1,2,3} and B = {2,3,4}, then A ∩ B is:', options: ['{1,2,3,4}', '{2,3}', '{1,4}', '{1}'], answer: 1, explanation: 'Intersection contains common elements: {2,3}.', subject: 'Maths', difficulty: 'easy' },
  { id: 'cuet-r1', question: 'Which article abolishes untouchability?', options: ['Article 14', 'Article 15', 'Article 17', 'Article 19'], answer: 2, explanation: 'Article 17 abolishes untouchability and forbids its practice in any form.', subject: 'General Knowledge', difficulty: 'medium' },
];

export const bitsatQuestions: PracticeQuestion[] = [
  { id: 'bit-p1', question: 'A body of mass 2 kg is moving with velocity 4 m/s. Its kinetic energy is:', options: ['8 J', '16 J', '32 J', '4 J'], answer: 1, explanation: 'KE = ½mv² = ½ × 2 × 16 = 16 J.', subject: 'Physics', difficulty: 'easy' },
  { id: 'bit-c1', question: 'Which of the following is a noble gas?', options: ['Nitrogen', 'Argon', 'Oxygen', 'Hydrogen'], answer: 1, explanation: 'Argon (Ar) is in Group 18, the noble gases. It has a complete octet.', subject: 'Chemistry', difficulty: 'easy' },
  { id: 'bit-m1', question: 'The value of log₁₀ 100 is:', options: ['1', '2', '10', '0.5'], answer: 1, explanation: 'log₁₀ 100 = log₁₀ 10² = 2 × log₁₀ 10 = 2 × 1 = 2.', subject: 'Maths', difficulty: 'easy' },
  { id: 'bit-e1', question: 'Choose the word that is spelt correctly:', options: ['Occurence', 'Occurrence', 'Ocurrence', 'Occurrance'], answer: 1, explanation: 'Occurrence — double c, double r. One of the most commonly misspelt English words.', subject: 'English', difficulty: 'easy' },
  { id: 'bit-r1', question: 'Which number comes next: 1, 1, 2, 3, 5, 8, ?', options: ['10', '11', '13', '15'], answer: 2, explanation: 'Fibonacci series: each number = sum of previous two. 5 + 8 = 13.', subject: 'Reasoning', difficulty: 'easy' },
];

export const viteeeQuestions: PracticeQuestion[] = [
  { id: 'vit-p1', question: 'The resistance of a wire is doubled when its length is doubled and area is halved because R ∝:', options: ['L/A', 'A/L', 'LA', 'L²/A'], answer: 0, explanation: 'R = ρL/A. Doubling L and halving A: R = ρ(2L)/(A/2) = 4ρL/A = 4R. R is proportional to L/A.', subject: 'Physics', difficulty: 'medium' },
  { id: 'vit-c1', question: 'Benzene undergoes which type of reaction predominantly?', options: ['Addition', 'Elimination', 'Electrophilic substitution', 'Nucleophilic substitution'], answer: 2, explanation: 'Benzene, due to aromatic stability, prefers electrophilic substitution (maintains the ring) over addition reactions.', subject: 'Chemistry', difficulty: 'medium' },
  { id: 'vit-m1', question: 'The area under the curve y = x² from x=0 to x=2 is:', options: ['4/3', '8/3', '4', '2'], answer: 1, explanation: '∫₀² x² dx = [x³/3]₀² = 8/3 - 0 = 8/3.', subject: 'Maths', difficulty: 'medium' },
  { id: 'vit-a1', question: 'If the ratio of boys to girls is 3:5 and total students are 40, boys are:', options: ['15', '25', '12', '20'], answer: 0, explanation: 'Boys = (3/8) × 40 = 15. Girls = (5/8) × 40 = 25.', subject: 'Aptitude', difficulty: 'easy' },
];

export const ndaQuestions: PracticeQuestion[] = [
  { id: 'nda-m1', question: 'The LCM of 12, 15 and 20 is:', options: ['60', '120', '30', '180'], answer: 0, explanation: '12=2²×3, 15=3×5, 20=2²×5. LCM = 2²×3×5 = 60.', subject: 'Maths', difficulty: 'easy' },
  { id: 'nda-g1', question: 'The Indian Navy Day is celebrated on:', options: ['October 8', 'December 4', 'January 15', 'November 14'], answer: 1, explanation: 'Navy Day: December 4 (commemorating Operation Trident, 1971). Army Day: January 15. Air Force Day: October 8.', subject: 'General Knowledge', difficulty: 'medium' },
  { id: 'nda-g2', question: 'Article 370 was related to:', options: ['Jammu & Kashmir', 'Northeast states', 'Goa', 'Puducherry'], answer: 0, explanation: 'Article 370 granted special autonomous status to J&K. It was abrogated on August 5, 2019.', subject: 'General Knowledge', difficulty: 'easy' },
];

export const tnauQuestions: PracticeQuestion[] = [
  { id: 'tnau-b1', question: 'The green revolution in India was led by:', options: ['Verghese Kurien', 'M.S. Swaminathan', 'Norman Borlaug', 'Both B and C'], answer: 3, explanation: 'Norman Borlaug (father of Green Revolution globally) and M.S. Swaminathan (father of Indian Green Revolution) together led it.', subject: 'Biology', difficulty: 'easy' },
  { id: 'tnau-b2', question: 'Nitrogen fixation in legumes is done by:', options: ['Azotobacter', 'Rhizobium', 'Blue-green algae', 'Clostridium'], answer: 1, explanation: 'Rhizobium lives in root nodules of legumes and fixes atmospheric N₂ into NH₃ (symbiotic nitrogen fixation).', subject: 'Biology', difficulty: 'easy' },
  { id: 'tnau-c1', question: 'The pH of acidic soil is:', options: ['Less than 7', 'Equal to 7', 'Greater than 7', 'Always 0'], answer: 0, explanation: 'pH < 7 = acidic. pH = 7 = neutral. pH > 7 = alkaline. Acidic soils need lime treatment for agriculture.', subject: 'Chemistry', difficulty: 'easy' },
];

export const srmjeeeQuestions: PracticeQuestion[] = [
  { id: 'srm-p1', question: 'The SI unit of power is:', options: ['Joule', 'Watt', 'Newton', 'Pascal'], answer: 1, explanation: 'Power = Work/Time. SI unit: Joule/second = Watt (W). Named after James Watt.', subject: 'Physics', difficulty: 'easy' },
  { id: 'srm-c1', question: 'Methane (CH₄) has the shape of:', options: ['Square planar', 'Trigonal planar', 'Tetrahedral', 'Linear'], answer: 2, explanation: 'CH₄: Carbon is sp³ hybridized with 4 bond pairs and 0 lone pairs → tetrahedral geometry (109.5°).', subject: 'Chemistry', difficulty: 'easy' },
  { id: 'srm-m1', question: 'The sum of first 10 natural numbers is:', options: ['45', '55', '65', '100'], answer: 1, explanation: 'Sum = n(n+1)/2 = 10(11)/2 = 55.', subject: 'Maths', difficulty: 'easy' },
];

// ═══ MAP TO EXAM IDs ═══
export const examPracticeQuestions: Record<string, PracticeQuestion[]> = {
  'jee-main': jeeMainQuestions,
  'neet-ug': neetQuestions,
  'cuet': cuetQuestions,
  'clat': clatQuestions,
  'nda': ndaQuestions,
  'bitsat': bitsatQuestions,
  'viteee': viteeeQuestions,
  'tnau': tnauQuestions,
  'srmjeee': srmjeeeQuestions,
};
